### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by ItachiSan** [royshil/obs-backgroundremoval#1]
Hello sir,

I saw both in the README and in the forum that you would like help for both Windows and Linux.

As I can help with that, I would like to know what is the process to help contributing. :)

**Comment by royshil** [comment]
Just fork the repo, build on Windows, make commits of the changes you had to do to get it to build and run, and open a pull request back here

**Comment by royshil** [comment]
it's now building on Windows and Linux . closing this issue
