### ISSUE TITLE
Chroma key with feather filter creates some color spill for me

### ISSUE THREAD

**Issue by claell** [royshil/obs-backgroundremoval#101]
I want to use this plugin with a virtual background. For that, it is suggested to use a chroma key filter.

However, together with the "Feather blend silhouette" option of this, the chroma key filter creates a color spill on the edges, which doesn't look nice:

![grafik](https://user-images.githubusercontent.com/6171135/176916159-52de5c80-3dc1-4605-b2d0-3e7344b55d40.png)

If I don't use the "Feather blend silhouette", the edges don't look good. I didn't find an option to later add the feather blend (for example, after or in chroma key filter).

Ideally, one could simply make the background transparent in this filter without the need of additional chroma key filter in the chain. Unfortunately, currently, the color picker doesn't give me that option.

Do you know a good solution or possibly can you add some?

For now, I just reduce the strength of "Feather blend silhouette" as a workaround.

**Comment by royshil** [comment]
last time i checked transparency wasn't possible.. had to pair it with a chroma key...
we'll look into the color bleed for sure

**Comment by royshil** [comment]
color bleed should be fixed in latest version coming out
