### ISSUE TITLE
How can I use this in GPU mode?

### ISSUE THREAD

**Issue by claell** [royshil/obs-backgroundremoval#102]
I tried setting the Inference device to "GPU - DirectML", but it did not seem to have effect on the CPU usage. Do I need some packages like CUDA installed to make it work?

**Comment by MrTeeXD** [comment]
I too am having the same issue.

**Comment by royshil** [comment]
on windows we suppoert directml
CUDA support is difficult because the libraries to be packed with this plugin are 100s of Mb, and many people don't have CUDA GPU
but DirectML has a very similar effect on Windows.
