### ISSUE TITLE
Problems with plugin innstallation in Ubuntu 22.04, OBS-Studio 27.2.4

### ISSUE THREAD

**Issue by ny2292000** [royshil/obs-backgroundremoval#103]
Dear Roy,

Thanks for the great plugin.

I don't think this is an issue with the code itself.  I think it is a problem with the installation, perhaps we are missing some details or functions.

Following strictly the instructions, result in an error and incompatibilities with libobs versions.  
It seems that apt only has the older version.
I spend a lot of time trying to learn by myself how to solve this problem.  
I failed, so I would like to ask for guidance.

I think the issue is that the plugin obs-backgroundremoval doesn't build properly 
in Ubuntu 22.04 with the obs-studio 27.2.4

The issue of missing Findlibobs.cmake and subsequent other Find functions, I tried to solve, but there
was always something that I couldn't solve. Perhaps you could double-check to see if there is really a problem.

BELOW ARE THE CONFIGURATION AND ACTIONS:

System is Ubuntu 22.04 5.15.0-40-generic

OBS-Studio 27.2.4 was installed
CUDA-Toolkit, CUDA-DNN was installed
libopencv was installed

OBS-Studio headers were installed using:
git clone --single-branch -b 27.2.4 git@github.com:obsproject/obs-studio.git
**ALTHOUGH I DON'T KNOW HOW THESE HEADERS INTERACT WITH THE BUILDING OF THE PLUGIN!!**

ONNXRUNTIME CPU installed using the provided commands:
$ export ONNX_VERSION=1.10.0
$ sudo apt install cuda libcudnn8
$ wget https://github.com/microsoft/onnxruntime/releases/download/v${ONNX_VERSION}/onnxruntime-linux-x64-gpu-${ONNX_VERSION}.tgz
$ sudo tar xzvf onnxruntime-linux-x64-gpu-${ONNX_VERSION}.tgz --strip-components=1 -C /usr/local/ --wildcards "*/include/*" "*/lib*/"

OTHER CONFIGURATION
cmake version 3.22.1
libopencv 4.5.6_dfsg-9ubuntu4
nvidia-cudnn/jammy,now 8.2.4.15~cuda11.4
nvidia-cuda-toolkit/jammy,now 11.5.1-1ubuntu1 

When installing dependencies:
 sudo apt install -y libobs-dev libopencv-dev language-pack-en wget git build-essential cmake libsimde-dev
 
 there is a problem:
 The following packages have unmet dependencies:
 obs-studio : Conflicts: libobs0 but 27.2.3+dfsg1-1 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

So, I proceeded without libobs-dev
sudo apt install -y libopencv-dev language-pack-en wget git build-essential cmake libsimde-dev

OTHER CONFIGURATION
build-essential is already the newest version (12.9ubuntu3).
cmake is already the newest version (3.22.1-1ubuntu1).
language-pack-en is already the newest version (1:22.04+20220415).
wget is already the newest version (1.21.2-2ubuntu1).
libopencv-dev is already the newest version (4.5.4+dfsg-9ubuntu4).
libsimde-dev is already the newest version (0.7.2-6).
git is already the newest version (1:2.34.1-1ubuntu1.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

LIBOBS IN /USR
This is what I find about installed libobs:

find /usr |grep -i libobs
/usr/share/obs/libobs
/usr/share/obs/libobs/deinterlace_yadif_2x.effect
/usr/share/obs/libobs/default.effect
/usr/share/obs/libobs/format_conversion.effect
/usr/share/obs/libobs/default_rect.effect
/usr/share/obs/libobs/deinterlace_base.effect
/usr/share/obs/libobs/deinterlace_linear_2x.effect
/usr/share/obs/libobs/deinterlace_yadif.effect
/usr/share/obs/libobs/area.effect
/usr/share/obs/libobs/solid.effect
/usr/share/obs/libobs/deinterlace_linear.effect
/usr/share/obs/libobs/deinterlace_discard.effect
/usr/share/obs/libobs/bicubic_scale.effect
/usr/share/obs/libobs/deinterlace_discard_2x.effect
/usr/share/obs/libobs/repeat.effect
/usr/share/obs/libobs/bilinear_lowres_scale.effect
/usr/share/obs/libobs/opaque.effect
/usr/share/obs/libobs/deinterlace_blend.effect
/usr/share/obs/libobs/premultiplied_alpha.effect
/usr/share/obs/libobs/lanczos_scale.effect
/usr/share/obs/libobs/deinterlace_blend_2x.effect
/usr/lib/libobs-frontend-api.so
/usr/lib/libobs-frontend-api.so.0
/usr/lib/x86_64-linux-gnu/pkgconfig/libobs.pc
/usr/lib/libobs-opengl.so.0.0
/usr/lib/libobs.so.0
/usr/lib/libobs.so
/usr/lib/libobsglad.so
/usr/lib/libobs-scripting.so
/usr/lib/libobs-opengl.so
/usr/lib/cmake/LibObs
/usr/lib/cmake/LibObs/LibObsConfig.cmake
/usr/lib/cmake/LibObs/LibObsConfigVersion.cmake
/usr/lib/cmake/LibObs/LibObsTarget.cmake
/usr/lib/cmake/LibObs/LibObsTarget-none.cmake
/usr/lib/libobs-opengl.so.0
/usr/lib/libobsglad.so.0
/usr/lib/libobs-frontend-api.so.0.0

This is about ONNXRUNTIME
find /usr |grep -i onnx
/usr/local/lib/libonnxruntime_providers_cuda.so
/usr/local/lib/libonnxruntime_providers_tensorrt.so
/usr/local/lib/libonnxruntime_providers_shared.so
/usr/local/lib/libonnxruntime.so
/usr/local/lib/libonnxruntime.so.1.10.0
/usr/local/include/onnxruntime_run_options_config_keys.h
/usr/local/include/onnxruntime_c_api.h
/usr/local/include/onnxruntime_session_options_config_keys.h
/usr/local/include/onnxruntime_cxx_api.h
/usr/local/include/onnxruntime_cxx_inline.h

THEN 

gh repo clone royshil/obs-backgroundremoval TO CREATE THE LOCAL COPY

THEN
$ cd obs-backgroundremoval
$ sudo ldconfig  # required if you have previously had a different version of onnxruntime installed
$ mkdir build && cd build
$ cmake -DWITH_CUDA=ON .. && cmake --build . && sudo cmake --install .

THIS IS THE FINAL ERROR:
cmake -DWITH_CUDA=ON ..
-- Found Git: /usr/bin/git (found version "2.34.1") 
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:106 (find_package):
  By not providing "Findlibobs.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "libobs", but
  CMake did not find one.

  Could not find a package configuration file provided by "libobs" with any
  of the following names:

    libobsConfig.cmake
    libobs-config.cmake

  Add the installation prefix of "libobs" to CMAKE_PREFIX_PATH or set
  "libobs_DIR" to a directory containing one of the above files.  If "libobs"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!

Any guidance would be welcomed, Roy

Thanks in advance.

**Comment by myself-rj** [comment]
It seems even the github CI failed for the latest commit https://github.com/royshil/obs-backgroundremoval/runs/6264276409

So, as a workaround, until @royshil replies, I use this:
git checkout bedcaf973424a05d2cfff1dc1295f5b516f82cd2
To go back to the latest buildable state and then build as usual (see [commit history](https://github.com/royshil/obs-backgroundremoval/commits/main))

**Comment by royshil** [comment]
latest versions take care of build and we have release for ubuntu

**Comment by ny2292000** [comment]
Thanks a million,. Roy
