### ISSUE TITLE
I don't see the filter at all 

### ISSUE THREAD

**Issue by clixmoney** [royshil/obs-backgroundremoval#105]
I have Windows 7, I did everything right, tried many times to close and reopen obs, but I don't see the filter at all. What should I do ?

**Comment by Karasiq** [comment]
Same

**Comment by tvl83** [comment]
I am on windows 10, just downloaded and am trying to follow a video to set this up. It does not show up under filters. I've restarted OBS 3-4 times.

**Comment by tvl83** [comment]
So, I did just find it. It's under filters for the **SOURCE** _not_ for the **SCENE**.

**Comment by royshil** [comment]
closing stale issue
