### ISSUE TITLE
Mac M1 native version with OBS 28?

### ISSUE THREAD

**Issue by tririver** [royshil/obs-backgroundremoval#109]
OBS 28 is in its Release Candidate stage. Would background removal be updated to natively run on Mac M1?

**Comment by pkej** [comment]
It seems several plugin-makers have github actions for building to Apple Silicone + QT6, [exeldro](https://github.com/exeldro), [univrsal](https://github.com/univrsal) and [WarmUpTill](https://github.com/WarmUpTill).

Thank you for the plugin, probably will make me stay on OBS 27 for now

**Comment by umireon** [comment]
I've released v0.5.8 on my own fork which can be installed with M1 OBS 28+.
https://github.com/umireon/obs-backgroundremoval/releases/tag/v0.5.8

**Comment by royshil** [comment]
this is implemented now
