### ISSUE TITLE
[RECOMENDATION] Do better tutorial to install, or do and .exe to install.

### ISSUE THREAD

**Issue by linuxmobile** [royshil/obs-backgroundremoval#11]
Hi, is hard to install this plugin. I already tried with the "tutorial" from the release page, and it's not working. I do the same that the "tutorial" say : 
```
To install
    Windows: Copy .dlls to e.g. C:\Program Files\obs-studio\obs-plugins\64bit, and .onnx file to e.g. C:\Program Files\obs-studio\data\obs-plugins\obs-backgroundremoval
```

**Comment by royshil** [comment]
The latest release https://github.com/royshil/obs-backgroundremoval/releases/tag/0.2-beta has a zip file which you unpack into the OBS directory, e.g. `C:\Program Files\obs-studio`.

I will work on an installer.

**Comment by linuxmobile** [comment]
> will work on an installer

Cool, i want to try then!!! thx for work on it! i really apreciate it

**Comment by royshil** [comment]
this is done.
