### ISSUE TITLE
mat dataend read memory from 0x7fece0290000 failed (0 of 1 bytes read)

### ISSUE THREAD

**Issue by chfeizy** [royshil/obs-backgroundremoval#110]
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/6427629/187448511-fabff3d1-29b4-44cc-91cc-f3464e096cdd.png">

**Comment by chfeizy** [comment]
the convertFrameToBGR failed

**Comment by royshil** [comment]
we upgraded opencv etc.
@chfeizy  see if the latest version also gives you this error

**Comment by royshil** [comment]
we've made several improvements, this shuold be good to close
