### ISSUE TITLE
CPU Usage Maxes Out Windows 11

### ISSUE THREAD

**Issue by jnitterauer** [royshil/obs-backgroundremoval#112]
I have installed this plugin in 3 different Windows machines. When active, the plugin causes CPU usage to spike to almost 100% utilization. No setting tweak will stop the CPU usage. Frames get dropped and video quality is terrible. Removing the filter instantly restored performance and lowers CPU use. I am running latest OBS on Windows 11.

Any ideas? Its useless unless the CPU usage gets reined in.

**Comment by uniqueum** [comment]
Could you check the FOS in OBS, please? This might just also be #23

**Comment by royshil** [comment]
try our latest release https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.5.1 !
we support DirectML, which on my system reduced CPU from ~40% to just 2%! (a 95% improvement)

**Comment by royshil** [comment]
DirectML should take care of CPU usage on Windows
