### ISSUE TITLE
Compilation on Linux+AMD broken - OrtSessionOptionsAppendExecutionProvider_DML

### ISSUE THREAD

**Issue by smirgol** [royshil/obs-backgroundremoval#114]
The changes to background-filter.cpp in commit cc9d4a5711f9388ed110230f9f793bb071577a23 broke compilation in Linux (Ubuntu 22.04) for me:

```
src/background-filter.cpp:215:31: error: ‘OrtSessionOptionsAppendExecutionProvider_DML’ was not declared in this scope; did you mean ‘OrtSessionOptionsAppendExecutionProvider_CPU’?
  215 |             Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_DML(sessionOptions, 0));
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                               OrtSessionOptionsAppendExecutionProvider_CPU
```
In earlier versions the part with using either `OrtSessionOptionsAppendExecutionProvider_DML` or `OrtSessionOptionsAppendExecutionProvider_CUDA` was used only on WIN32, but now it is also used for linux.

I'm on a AMD GPU and neither have CUDA nor DML, so it throws that error. I've fixed it like this:

```
    try {
#ifdef WITH_CUDA
        if (tf->useGPU == USEGPU_CUDA) {
            Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_CUDA(sessionOptions, 0));
        }
#elif _WIN32
        if (tf->useGPU == USEGPU_DML) {
            Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_DML(sessionOptions, 0));
        }
#endif
        tf->session.reset(new Ort::Session(*tf->env, tf->modelFilepath, sessionOptions));
    } catch (const std::exception& e) {
        blog(LOG_ERROR, "%s", e.what());
        return;
    }
```

That worked for me, but not sure if that is a proper solution. Compilation now works, but OBS segfaults, where I think that is a different issue with the new plugin system in OBS 28.x

**Comment by BriegerCA** [comment]
Hi Robert,
I got the same error when compiling. I see that you got one fixed, but how about the other?
Truly sad that the Author doesn't seem to react to any issues posted.

**Comment by royshil** [comment]
DML properly hidden from linux now
