### ISSUE TITLE
Support for OBS v28?

### ISSUE THREAD

**Issue by MadMartian** [royshil/obs-backgroundremoval#115]
Today (much to my chagrin) I noticed that OBS Studio upgraded from v27 to v28 and completely obliterated my background removal setup.  To add insult to injury, the previous version of OBS Studio I was using `27.1.3-0obsproject1~focal` no longer exists, so I cannot even downgrade and have been effectively kicked out into the rain and left holding the bag.  

Is there going to be an effort to add v28 support for this plugin in the near future? I am dead in the water until support for this plugin for OBS v28 is available.  I must say I am whole-heartedly against the _"move fast and break things"_ mantra now having been burnt by this too many times.

**Comment by Skullfurious** [comment]
Also looking to see what it would take to update this to v28

**Comment by umireon** [comment]
I could built OBS 28 version on my Mac easily #113

**Comment by ZXSwire3** [comment]
The windows build instructions don't seem as simple. I was trying to follow them, but I got stuck when I had to install `Microsoft.ML.OnnxRuntime.DirectML` and `Microsoft.ML.OnnxRuntime.Gpu` with nuget.

**Comment by umireon** [comment]
@ZXSwire3 You can fork this repo, fix the code, and update the build instructions as I do.
Nothing blocks you to contribute!
You can do it!

**Comment by MadMartian** [comment]
I added the Linux fix in #122

**Comment by zennmaster** [comment]
> I added the Linux fix in #122

Nice work, thank you!

**Comment by Technetium1** [comment]
@MadMartian why downgrade opencv? https://github.com/royshil/obs-backgroundremoval/pull/122/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR114

**Comment by umireon** [comment]
I've released v0.5.8 on my own fork which can be installed with M1 OBS 28+.
https://github.com/umireon/obs-backgroundremoval/releases/tag/v0.5.8

**Comment by royshil** [comment]
try our latest release https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.5.1 !

**Comment by royshil** [comment]
obs v28+ now supported
