### ISSUE TITLE
Crash onnxruntime - Resource temporarily unavailable

### ISSUE THREAD

**Issue by jmlipari** [royshil/obs-backgroundremoval#117]
After a long time fighting alone (to learn), I decided to ask for your help…:slight_smile: I installed obs-studio through snap onto Ubuntu 22.04.1

When I tried to run the backgroundremoval plugin, obs studio crash and I get this error:
Error: [obs-backgroundremoval] /onnxruntime_src/onnxruntime/core/platform/posix/env.cc:183 onnxruntime::{anonymous}::PosixThread::PosixThread(const char*, int, unsigned int (*)(int, Eigen::ThreadPoolInterface*), Eigen::ThreadPoolInterface*, const onnxruntime::ThreadOptions&) pthread_setaffinity_np failed, error code: 11 error msg: Resource temporarily unavailable
11th Gen Intel® Core™ i7-11700 @ 2.50GHz × 16
Graphics UHD Intel® 750

Any help? Thank you

**Comment by royshil** [comment]
try our new release https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.5.1 ! it's got .deb ubuntu package

**Comment by royshil** [comment]
stale issue. closing
