### ISSUE TITLE
Offer Universal Build for Mac

### ISSUE THREAD

**Issue by 3DCoded** [royshil/obs-backgroundremoval#119]
When using this with M1 Mac with M1 OBS, it doesn't show up in the properties. When I use Rosetta 2 to run Intel OBS, it shows, but is really slow. Please build this for universal Mac.

**Comment by snollygolly** [comment]
I'd really love to see this added as well

**Comment by Gabieler** [comment]
That'd be so cool! +1 🙏

**Comment by victordion** [comment]
+1

**Comment by jameskieley** [comment]
+1

**Comment by tsvoronos** [comment]
Also very interested in this.

**Comment by ekiim** [comment]
+1

**Comment by umireon** [comment]
I've released v0.5.8 on my own fork which can be installed with M1 OBS 28+.
https://github.com/umireon/obs-backgroundremoval/releases/tag/v0.5.8
I offer M1 native version

**Comment by Gabieler** [comment]
ありがとうございます! Any chance you could make it compatible with 29? Tried installing 0.5.9 (changing the location as per your instrunctions) but it didn't show up among my filters in the latest OBS version

**Comment by umireon** [comment]
@Gabieler Can you reinstall Apple Silicon OBS and arm64 pkg? If your OBS installation is Intel and this plugin is ARM64, this plugin won't load.
I have Apple Silicon OBS 29 and arm64 v0.5.8 and it works perfectly.

**Comment by umireon** [comment]
It should be noted that this plugin will appear in Audio/Video filters.

**Comment by Gabieler** [comment]
Sorry, my bad. Should've mentioned I'm on Apple Silicon, too. Also, I had only checked the "Effect" filters. Checked the "Audio/Video" filters and it's there. Thank you very much for this 🙏

**Comment by royshil** [comment]
try our latest release https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.5.1 !
it's got universal as well as arm (M1) support

**Comment by royshil** [comment]
universal mac build now released
