### ISSUE TITLE
Feature request: edge padding.

### ISSUE THREAD

**Issue by mctrafik** [royshil/obs-backgroundremoval#12]
Good day.

Love the plugin. Good work. I feel like a few things needed to make it usable.

Here's what I got when I tried to blur my background:

![Screen Shot 2021-04-30 at 6 06 03 PM](https://user-images.githubusercontent.com/1694347/116766392-1a5c7480-a9df-11eb-9ae2-4b277b22a139.png)

As you can see it doesn't think my hair, headset, forehead and eyebrows are part of me.  And around my shoulders the transition line is very hard.

Shoulder tracking is amazing... but the issues above make this ... "interesting" to use.

Anyway, I would like to ask for a feature where instead of filling the edge at the edge of the match, if we could do so within X pixels. I.e. for my use case I don't care if I reveal 30 pixels around my shoulders, but I would really like my eyebrows (and sometimes eyes) to not be considered "background".

Like... this is funny.... but I wouldn't get on a work call like this:

![Screen Shot 2021-04-30 at 6 12 28 PM](https://user-images.githubusercontent.com/1694347/116766504-b6867b80-a9df-11eb-9392-6dc562c2e678.png)

If not obvious, this happens at all `threshold` levels. Max 'usable' threshold level is `.95` which looks like this for me:

![Screen Shot 2021-04-30 at 6 14 37 PM](https://user-images.githubusercontent.com/1694347/116766554-ee8dbe80-a9df-11eb-96c3-3350737dd840.png)

The other dials only make things worse.

**Comment by royshil** [comment]
this may be fixed by using other segmentation models - which i'm working on..

**Comment by royshil** [comment]
@mctrafik can you try the new models and see how it goes? if it's good - plz close the issue

**Comment by ngoonee** [comment]
@royshil I saw the modnet model, it seems unusable for me (0.01 threshold gives a BIT of the image, otherwise it just filters everything out).

The SI model works the same as what @mctrafik has reported, everything above my lips isn't detected as face.
