### ISSUE TITLE
UBUNTU Tool crashing

### ISSUE THREAD

**Issue by BriegerCA** [royshil/obs-backgroundremoval#120]
I have spend quite some time trying to get this to run with UBUNTU without success.
People have send in detailed reports (segmentation faults, etc), but no response.
The SNAP solution doesn't work, the PIP installer doesn't work in UBUNTU either.
Is there anyone who got this to work with UBUNTU 22.04 and OBS 28 and wouldn't 
mind sharing the plugin?
As I said, plenty of failure reports have been filed already, doesn't add value to post
the same again.

Is there any will to get this solved for UBUNTU or should it be laid to rest?

**Comment by mircous** [comment]
same

**Comment by BriegerCA** [comment]
Hey,

if you run UBUNTU and OBS 28.xx the issue is fixed.
Not by the creator though. Still need info?

**Comment by royshil** [comment]
try our new release https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.5.1 ! got a .deb for Ubuntu

**Comment by royshil** [comment]
closing stale issue
