### ISSUE TITLE
Feature request: option to blur background instead of removing it

### ISSUE THREAD

**Issue by sc0ty** [royshil/obs-backgroundremoval#121]
Blurring is currently unnecessary complicated and requires use of external tools to duplicate webcam input. It would be much easier if we have this option built-in, even with some simple blurring algorithm.

Great plugin by the way, I was looking for something like this a long time.

**Comment by royshil** [comment]
this is a wonderful suggestion.. which can be implemented rather simply
i'll tag this for development

**Comment by royshil** [comment]
this was implemented in the latest version
