### ISSUE TITLE
Is it possible for a new release?

### ISSUE THREAD

**Issue by ngoonee** [royshil/obs-backgroundremoval#124]
Personally I'm interested in https://github.com/royshil/obs-backgroundremoval/pull/57 actually being released. Also the recent release of OBS v28 (and the PR for Mac compilation etc) probably should be merged and released.

**Comment by umireon** [comment]
I've released v0.5.8 on my own fork which can be installed with M1 OBS 28+.
https://github.com/umireon/obs-backgroundremoval/releases/tag/v0.5.8

**Comment by royshil** [comment]
try our new release https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.5.1 ! joint work with @umireon

**Comment by royshil** [comment]
we bumped onnxruntime to 1.14
ans we have M1 support released
