### ISSUE TITLE
‘OrtSessionOptionsAppendExecutionProvider_DML’ was not declared in this scope

### ISSUE THREAD

**Issue by LuisGFer** [royshil/obs-backgroundremoval#125]
In Ubuntu 22.04 when I try to cmake --build . following the installation instructions I get this error:

error: ‘OrtSessionOptionsAppendExecutionProvider_DML’ was not declared in this scope; did you mean ‘OrtSessionOptionsAppendExecutionProvider_CPU’?
  215 |             Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_DML(sessionOptions, 0));
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                               OrtSessionOptionsAppendExecutionProvider_CPU
gmake[2]: *** [CMakeFiles/obs-backgroundremoval.dir/build.make:76: CMakeFiles/obs-backgroundremoval.dir/src/background-filter.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/obs-backgroundremoval.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2

Some Idea to solve it? Thanks

**Comment by bobek** [comment]
Changing the mentioned line to `OrtSessionOptionsAppendExecutionProvider_CPU` (mind the `CPU` at the end) will result in successful build, with ONNX using just CPU (in my case it will result in 3 fully utilized cores).

DML stand for DirectML -- https://onnxruntime.ai/docs/execution-providers/DirectML-ExecutionProvider.html , which gets selected if `CUDA` is not available, but DML is not available on Linux (I am on Debian/sid).

Thus I would propose having `CPU` executor as a fallback.

**Comment by rigo** [comment]
Thanks @bobek I successfully compiled and used obs-backgroundremoval with OBS 28.0.1 on Ubuntu 22.10.
