### ISSUE TITLE
Support for flips and rotations from camera config

### ISSUE THREAD

**Issue by realSAH** [royshil/obs-backgroundremoval#127]
I changed config of my camera by applying flips (vertical, horizontal, clockwise and counterclockwise) both from camera config itself and from OBS filters, but it plugin failed to respond to those changes. E.g. the torso of my body shown in the opposite direction.

Can you please add support to account for those geometric transformations?

**Comment by royshil** [comment]
you can easily apply e.g. flips as a transform *after* the plugin by right clicking for example
<img width="350" alt="image" src="https://user-images.githubusercontent.com/441170/224564956-92d85bb2-aeb3-44a5-a40d-637d78fe3c04.png">
