### ISSUE TITLE
Crashes when clicking "Select colour"

### ISSUE THREAD

**Issue by lminiero** [royshil/obs-backgroundremoval#132]
Hi all,

I was testing the plugin (`v0.4.0`, but the same crash happens on `main` too), which seems to work nicely in pretty much everything except for one thing: when I click the "Select colour" button (which defaults to black) the plugin crashes OBS. This is what's printed on stderr when that happens:

```
(process:69345): Gtk-CRITICAL **: 13:07:01.013: _gtk_css_lookup_resolve: assertion '(((__extension__ ({ GTypeInstance *__inst = (GTypeInstance*) ((provider)); GType __t = ((_gtk_style_provider_private_get_type ())); gboolean __r; if (!__inst) __r = (0); else if (__inst->g_class && __inst->g_class->g_type == __t) __r = (!(0)); else __r = g_type_check_instance_is_a (__inst, __t); __r; }))))' failed

(process:69345): GLib-GObject-CRITICAL **: 13:07:01.013: g_object_set_data_full: assertion 'G_IS_OBJECT (object)' failed

(process:69345): Gtk-ERROR **: 13:07:01.013: Can't create a GtkStyleContext without a display connection
```

Does this ring any bell? I tried searching older issues but I couldn't find anything related, so I'm wondering if it may be an issue specific to my setup (which is nothing special, though). Please do let me know if I can provide more info to help look into this.

Thanks!

**Comment by umireon** [comment]
I've released v0.5.8 on my own fork which can be installed with Linux OBS 28+.
https://github.com/umireon/obs-backgroundremoval/releases/tag/v0.5.8
Build settings are changed so your problem may be gone.

**Comment by royshil** [comment]
try our new release https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.5.1 !

**Comment by lminiero** [comment]
Thanks, will do and will let you know!

**Comment by royshil** [comment]
no more select color...

**Comment by lminiero** [comment]
I still get the warning, though, so I can't compile :cry:
