### ISSUE TITLE
Not available OBS 29.0.0 (64 bit) Windows 10

### ISSUE THREAD

**Issue by dsmith000** [royshil/obs-backgroundremoval#134]
Just upgraded OBS Studio 29.0.0 and installed obs-background removal plugin.  It is not listed in the filters drop down menu...

![obs-filter](https://user-images.githubusercontent.com/38407785/212545544-526898c0-6ba2-49d0-8f60-c4b5336fca44.png)

**Comment by umireon** [comment]
I've released v0.5.8 on my own fork which can be installed with Windows OBS 28+.
And obs-backgroundremoval will appear in Audio/Video filters.
https://github.com/umireon/obs-backgroundremoval/releases/tag/v0.5.8

**Comment by royshil** [comment]
try our latest release https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.5.1 !

**Comment by royshil** [comment]
this should be taken care of on Windows
