### ISSUE TITLE
Scale video before calculating matte

### ISSUE THREAD

**Issue by Tiefseetauchner** [royshil/obs-backgroundremoval#138]
Is it possible to scale the video before calculating the matte? I think it might allow to reduce the CPU/GPU usage significantly while not diminishing quality by a lot (for example, scaling by 1/2 would allow to only calculate 1/4 the pixels, I don't know whether that would help the model performance wise, but then scaling the matte using e.g. bicubic interpolation might even help the matte look better)

I don't normally work in image processing, so I can't judge whether the scaling wouldn't take longer than the benefit of scaling, and if it's even possible

If you think it'd be a reasonable addition, I could look into it, dependent on complexity and time constraint (again, not my area of expertise by a long shot)

Best, Lena

**Comment by royshil** [comment]
we are downscaling to the model's input size, which is around 200x200 (some are a bit bigger at 320x240)
it's a good idea. i will do my best to add more models that are snappier, and maybe have smaller image input size and thus faster

**Comment by Tiefseetauchner** [comment]
Ahh, thanks for the info, I didn't think about it enough to think that a model with FHD input would be kind of extremely slow

**Comment by royshil** [comment]
closing this issue for now.
