### ISSUE TITLE
Appearing In Effect Filters

### ISSUE THREAD

**Issue by ddflink** [royshil/obs-backgroundremoval#141]
I would like to use this filter as a separate scene with source clone on my source camera. However background removal appears under audio/video filters instead effect filters. Is it possible for backgroundremoval to appear in effects filter like "NVIDIA Background Removal" which is available under effect filters.

**Comment by royshil** [comment]
unfortunately OBS makes a distinction between "effects" and regular filters.
effects use the extensible rendering pipeline, which NVidia is part of because they're the GPU
for us in this plugin it's not possible, as far as I know and can understand the OBS plugin APIs...

**Comment by umireon** [comment]
Implemented in v0.5.13 🎉
