### ISSUE TITLE
All Warnings Being Treated As Errors No Matter How

### ISSUE THREAD

**Issue by SteveSWang47** [royshil/obs-backgroundremoval#154]
```
.../obs-backgroundremoval-0.5.0/src/background-filter.cpp:436:29: error: operation on ‘tf->background_removal_filter::maskEveryXFramesCount’ may be undefined [-Werror=sequence-point]
  436 |   tf->maskEveryXFramesCount = ++(tf->maskEveryXFramesCount) % tf->maskEveryXFrames;
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

I tried configuring with `--compile-no-warning-as-error` and setting `CFLAGS="-Wno-error" CXXFLAGS="-Wno-error"` but this 'error' still occurred.

I don't know what to do.

**Comment by royshil** [comment]
fixed in `cmake/ObsPluginHelpers.cmake` , take a look at https://github.com/royshil/obs-backgroundremoval/pull/152/files#diff-6f18548d3e3f7768ed66e025cc4a67a5f4cf91bbbfd81d04571fffc7f3a8407d

**Comment by lminiero** [comment]
Looks like this has been reverted in #158?

**Comment by umireon** [comment]
I think all warning are removed so adding -Werror and /WX is safe
