### ISSUE TITLE
Any plan to notarize the Mac binaries and installers?

### ISSUE THREAD

**Issue by umireon** [royshil/obs-backgroundremoval#155]
It's great if the Mac installer and binaries are signed. Without the signature, users will be required to do some actions to circumvent security restrictions. 

The way to sign them is written on this page.
https://github.com/obsproject/obs-plugintemplate#signing-and-notarizing-on-macos

Note that notarizing needs a paid Apple Developer Account. I have a paid account and I can notarize my binaries.

**Comment by royshil** [comment]
yea it requires payment... i'll look into it and see if it's in my budget.

**Comment by umireon** [comment]
Can you open GitHub Sponsors? I can sponsor you ❤️

**Comment by royshil** [comment]
i set up a "sponsor" button in the main page of the reo - any help would be appreciated! any funds will be put towards registering and signing the plugin!

**Comment by umireon** [comment]
I sponsored you!

**Comment by royshil** [comment]
now notarized!
