### ISSUE TITLE
Thanks for the Update with OBS 29

### ISSUE THREAD

**Issue by BriegerCA** [royshil/obs-backgroundremoval#156]
I appreciate that you contacted me regarding the crashes experienced in the past when almost nothing worked for UBUNTU, but I got it compiled with help from someone else.

I have my OBS 26 Version running fine with OBS 29.

Are there any enhancements or "just" a .deb version?
Has this been tested?

Since I had spend a lot of time getting this to work, I don't want to screw it up.
Again, I appreciate the work you did and what I have works reasonably well.
Not as well as ZOOM, but then you aren't a big Company.

Fairly high CPU usage aside, I noticed that ZOOM (and others) work better with less light.
The outline appears to be a bit sharper as well.

Overall a great tool and should be part of standard OBS, which would hopefully help to resolve some kinks and your Wallet.

Thanks
Martin

**Comment by royshil** [comment]
for now - just the convenient installers
but we made changes to the infrastructure so putting up new work would be a whole lot easier and faster.
i'm hoping to integrate a new state of the art segmentation model soon, and add some requested features like background blur

**Comment by royshil** [comment]
@BriegerCA please see the latest version for additional features and improvements
