### ISSUE TITLE
The plugin does not work on Browser sources (They're commonly used for IP webcam stuff)

### ISSUE THREAD

**Issue by LeKukie** [royshil/obs-backgroundremoval#159]
Adding the filter to a browser source will end up just not working, it just doesn't appear on the filters after being added
This is bad for the people who don't have a webcam / have a wireless webcam and use an app that hosts their webcam in their local network, because the browser source is what gets used to have the webcam video feed into OBS.

**Comment by royshil** [comment]
the latest version allows adding the filter on browser sources
please check and report if it's working for you

**Comment by royshil** [comment]
@LeKukie can you test the latest version to see if it works on browser sources for you?

**Comment by umireon** [comment]
This feature was implemented in #220

**Comment by umireon** [comment]
@royshil Can we close this issue as completed?
