### ISSUE TITLE
PKGBUILD archlinux minor issues

### ISSUE THREAD

**Issue by krisezra87** [royshil/obs-backgroundremoval#16]
* pkgver_hyphen variable definition requires a tag on the latest git commit (which is not always the case).  This is easily fixed by either adding a tag for each commit, or something like:

pkgver_hyphen=$(git describe --exact-match --tags $(git rev-list --tags --max-count=1))

* Also a minor issue in the build file where SIPNet_Softmax.onnx is not included in the data folder.  I THINK it has worked by changing line 242 in the CmakeLists.txt to read `install(FILES "data/SINet_Softmax_simple.onnx"`

**Comment by krisezra87** [comment]
Despite what seems to be a good compile now, obs-studio doesn't see the plugin.  Even if I try the approaches the others in the issues list have recommended: moving into /usr/share and /usr/lib as well as into .config/obs-studio...

Not really sure what to make of that.

**Comment by royshil** [comment]
usually it fails to load because of missing dependencies...
can you inspect the shared library deps of your `obs-backgroundremoval.so` file?
perhaps it's just a e.g. `LD_LIBRARY_PATH` issue

**Comment by krisezra87** [comment]
Ah yes, I see I don't have libonnxruntime.so.  This is a real bear to get installed for some reason on arch.  I did a fresh pull from github from the link you have in the description and for some reason it won't build to completion.  The work continues.

**Comment by laundry-96** [comment]
@krisezra87 Have you been able to get this installed on Arch? I am not seemingly having any luck...

**Comment by krisezra87** [comment]
@laundry-96 no I have not been able to make it work yet unfortunately.  I have tried several onnx installs but nothing has generated that .so file for me yet.  You have reminded me that this was on my todo list.  I think I am going to nuke my install and start fresh.

**Comment by krisezra87** [comment]
@laundry-96 I got it!  I'm by no means an expert here, but it looks like the onnxruntime files are actually obtained during the make and perhaps cleaned up.  I went here:

https://github.com/microsoft/onnxruntime/releases/tag/v1.7.0

And downloaded / extracted the x64 tgz file for this release (it's the one that is shown as being necessary in the makeprg call and from `objdump -p /usr/local/lib/obs-plugins/obs-backgroundremoval.so`).  Inside the extracted tgz there is a lib folder that contains libonnxruntime.so and libonnxruntime.so.1.7.0.  I symlinked these both into /usr/lib.

I put the plugin in a variety of places at the advice of other people in the issues list and I'm not sure which one eventually loaded... but I'm fairly certain this is the key right here.

It's ugly, but it worked!

**Comment by royshil** [comment]
@krisezra87 please let me know if the latest release works https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.2.5-beta

**Comment by krisezra87** [comment]
@royshil this looks much better and is very close.  No longer need the ~/.config/obs-studio/plugins symbolic links which is great, and I didn't have to manually symlink libonnxruntime.so into /usr/lib.

Some minor issues I'm not sure how to fix in a pull request:

1.  The checksum is wrong.  I bypassed with `makepkg --skipchecksums -si`
2.  Install instructions are slightly wrong.  You need the `-i` flag above to get the .so files distributed.
3.  Minor: I can't actually start up the virtual camera in obs-studio without running as sudo.  There seems to be something slightly weird with the polkit settings and the agent prompts for password (but it won't take my password).

All told, running now with `makepkg --skipchecksums -si` in the scripts folder works properly out of the box, provided that obs is launched with sudo... which I don't like, but I'm willing to roll with for now :).

**Comment by laundry-96** [comment]
I'm able to build the latest commit with makepkg, and install with makepkg -i with no issues.

**Comment by royshil** [comment]
going to close this issue as most acute problems are resolved
