### ISSUE TITLE
Windows Defender detects Trojan:Win32/Spursint.F!cl in obs-backgroundremoval-0.5.12-windows-x64-Installer.exe

### ISSUE THREAD

**Issue by ScottRFrost** [royshil/obs-backgroundremoval#161]
The latest installer is testing hot on Windows Defender for https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fSpursint.F!cl&threatid=2147717281

Virus Total sees it as clean across the board though https://www.virustotal.com/gui/url/f8f30fd72fe201d2511b56b70cc012a89e681da58252f3473a7041db31d020c2?nocache=1

**Comment by umireon** [comment]
https://learn.microsoft.com/en-us/microsoft-365/security/intelligence/submission-guide?view=o365-worldwide

**Comment by Technetium1** [comment]
File a false positive report here: https://www.microsoft.com/en-us/wdsi/filesubmission/

**Comment by royshil** [comment]
#171  should fix it
version soon

**Comment by royshil** [comment]
i'm unable to detect anything with 0.5.13 on windows 11 with the Defender

can you verify on your end this is resolved? @ScottRFrost

**Comment by ScottRFrost** [comment]
obs-backgroundremoval-0.5.13-windows-x64-Installer.exe scans and installs without issue for me.  Closing issue.
