### ISSUE TITLE
v0.5.12 Windows 64 bit release not detected

### ISSUE THREAD

**Issue by UnaffiliatedCode** [royshil/obs-backgroundremoval#168]
Hello, I am a user of previous versions of this plugin. 

Upon upgrade to 0.5.12, the plugin no longer appears within the OBS window.
Upon downgrade to 0.4.0, plugin was restored. 

OBS Version: 27.1.3 (64 bit)

Verified on two different windows 10 machines (1 was a fresh environment).

**Comment by UnaffiliatedCode** [comment]
To be more specific, it stops appearing within the "Audio/Video filters" section. If I have a previously configured scene, upon upgrade it will appear in the "Effect Filters" section and be entirely broken.

**Comment by royshil** [comment]
yes the v0.5+ will need OBS v28+

**Comment by UnaffiliatedCode** [comment]
Missed that requirement. I'll mark as resolved ty.
