### ISSUE TITLE
Can you enable project tab?

### ISSUE THREAD

**Issue by umireon** [royshil/obs-backgroundremoval#179]
I want to use the project tab.

**Comment by royshil** [comment]
it's enabled!

**Comment by umireon** [comment]
Can you create a new project? Only repo admins can create a project that is usable on Projects tab.

**Comment by umireon** [comment]
I'm using Milestone to classify the issues which can be closed after candidate v0.5.14 is released. If you don't like the milestone, I can remove the milestone.

Many people use the issues tab as the forum, so we may also want to enable the Discussion tab. It would be great if the issues tab is full of feature suggestions.

**Comment by royshil** [comment]
i started a project.. not sura bout it. i've never used this on GH before

**Comment by umireon** [comment]
Thanks!
