### ISSUE TITLE
Update documentation to reflect that the filter is now an effect filter and not an audio/video filter

### ISSUE THREAD

**Issue by timkrief** [royshil/obs-backgroundremoval#181]
EDIT: Thanks @umireon . The filter was under the "Effect filters" an not under "Audio/Video" Filters as the old screenshots may suggest. I think it could be cool to update the documentation to avoid people thinking it's not working like me.

Hi. I'm using a fresh install of ubuntu 22. I did everything I could. I tried the .deb, I tried to build it myself, I tried with obs from ubuntu, obs from ppa, obs from flathub, 25, 27, 29. It never showed up. The best I could get was:

```
warning: Failed to load 'en-US' text for module: 'obs-backgroundremoval.so'
info: [obs-backgroundremoval] plugin loaded successfully (version 0.5.13)
```

But even when I got this it did not show up in obs in the list of filters in Audio/Video filters.

I had no success before on Ubuntu 20, I was never able to make it work yet.

**Comment by umireon** [comment]
Please check under the Effect filter and ensure you use OBS 28+.

**Comment by royshil** [comment]
`warning: Failed to load 'en-US' text for module: 'obs-backgroundremoval.so'` this is benign, fixed in a new version

**Comment by timkrief** [comment]
> Please check under the Effect filter and ensure you use OBS 28+.

Using 29.0.2, it is under the effect filter thank you very much. A lot of tutorials, issues and screenshots made me believe it was under Audio/Video filters. I think it was recently changed, we should update the screenshots in the readme to reflect that.

**Comment by umireon** [comment]
@royshil updated the README.md so closing this.
