### ISSUE TITLE
GCC build on Fedora and Arch is broken

### ISSUE THREAD

**Issue by umireon** [royshil/obs-backgroundremoval#182]
Due to https://github.com/microsoft/onnxruntime/issues/14923, the builds using GCC fail with some warnings.
We have to update the ONNX Runtime after this issue is resolved and there is almost nothing to fix this on our side.
This breaks the flatpak build, Fedora build, and Arch build.
Related #132 #172

**Comment by drieks** [comment]
As a workaround, I  added 
```
#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
```
as first line here: onnxruntime/core/mlas/lib/intrinsics/avx512/quantize_avx512f.cpp

**Comment by ngoonee** [comment]
Is my understanding correct that there's nothing to be done from obs-backgroundremoval side on this issue, and it is purely an upstream issue which can be worked around?

**Comment by umireon** [comment]
Resolved by #250
