### ISSUE TITLE
Filter not working on "Group"

### ISSUE THREAD

**Issue by jonnydcakes** [royshil/obs-backgroundremoval#183]
I have a group of webcams in my OBS scene, but the filter does not appear to be working when applied to the group. The same filters do work when copied and applied on the individual camera sources, but not at the group level.

My main application is with virtual camera. My default scene is the webcam with a blurred background. But at times I want to share my screen and remove the background so I can use my camera PIP style with the background removed. To accomplish this, I apply the filter to the group so I can have different filters on the camera(s) depending on scene.

**Comment by umireon** [comment]
I suppose you want to switch the blur filter and the background removal.
You can create separate AV capturing sources from the same cam and you can apply separate filter setting for them.

For example, you can create an AV capturing source with a blurring filter named BluredCamA from CamA, and you can create another AV capturing source with a background removal named NoBackgroundCamA from the same CamA.

**Comment by umireon** [comment]
@royshil Can we close this issue?
The requested feature is hardly feasible on the current OBS and IMO the described use case is not useful for many.
I suggested the author a workaround but no response has been made.
