### ISSUE TITLE
Windows 11 pro Antivirus removes this package

### ISSUE THREAD

**Issue by tormyvancool** [royshil/obs-backgroundremoval#184]
![image](https://user-images.githubusercontent.com/32305535/225702821-a6dde323-25a5-4797-b600-170df886d3f8.png)

**Comment by Technetium1** [comment]
Was this the newest version? Download with another browser and see if Defender tries to remove, or if it's just the accursed smartscreen blocking it in Edge. Hopefully not the same issue coming back: https://github.com/royshil/obs-backgroundremoval/issues/161#issuecomment-1472074159

**Comment by umireon** [comment]
Please describe the detail 🙇

**Comment by tormyvancool** [comment]
> Was this the newest version? Download with another browser and see if Defender tries to remove, or if it's just the accursed smartscreen blocking it in Edge. Hopefully not the same issue coming back: [#161 (comment)](https://github.com/royshil/obs-backgroundremoval/issues/161#issuecomment-1472074159)

This is the very last version. I downloaded immediately after you have published it on OBS Forum I also wrote there the same issue.
No, Also with other browsers is the same is WINDOWS DEFENDER that deletes (I said it) the file. Now ay. Please check the code. It's the only one plugin that behaves so :-/

@umireon there is nothing else to add. I downloaded the very last version, and this is what occurs.

**Comment by umireon** [comment]
@tormyvancool Thank you for describing the detail!
We need the log of Microsoft Defender, the name of your downloaded file, and the SHA256 hash value of the downloaded file for further investigation.
Could you paste them here, please?

**Comment by tormyvancool** [comment]
> @tormyvancool Thank you for describing the detail! We need the log of Microsoft Defender, the name of your downloaded file, and the SHA256 hash value of the downloaded file for further investigation. Could you paste them here, please?

Not lue where to find the log of defender.
As I sadi 2 times: the file was deleted by the Defender itself:
![image](https://user-images.githubusercontent.com/32305535/225875512-7365f081-93db-4fc3-8434-023814be11c7.png)

**Comment by tormyvancool** [comment]
> @tormyvancool You downloaded the old version. Please try v0.5.13!
> 
> https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.5.13

It was the one you published on OBS Forum. howver the new version is crashing OBS

![image](https://user-images.githubusercontent.com/32305535/225880390-a85d0881-33a5-47db-818b-96a05cc7f24e.png)

**Comment by umireon** [comment]
@tormyvancool Can you upload here the OBS log file when the OBS crashed?
The log file would be at "%APPDATA%\obs-studio\logs" and the extension is txt.

**Comment by tormyvancool** [comment]
> @tormyvancool Can you upload here the OBS log file when the OBS crashed? The log file would be at "%APPDATA%\obs-studio\logs" and the extension is txt.

But I already did it:
![image](https://user-images.githubusercontent.com/32305535/225883696-6bb607f0-9dae-4b96-ad27-a1cd26bd8f5a.png)

**Comment by umireon** [comment]
We need both the "log" and the "crashes". You already provided the "crashes" so we only need your "log" file 🙇

**Comment by umireon** [comment]
It seems that [2023-03-17 11-39-17.txt](https://github.com/royshil/obs-backgroundremoval/files/11000641/2023-03-17.11-39-17.txt) is not the log when the OBS was crashed.

Could you try to crash the OBS again and send us both the latest logs again right after the crash 🙇

**Comment by tormyvancool** [comment]
I removed all the logs and all the crashes
Re-installed the package
Started OBS
It crashed

Here below the 2 generated files:

[Crash 2023-03-17 12-27-31.txt](https://github.com/royshil/obs-backgroundremoval/files/11000820/Crash.2023-03-17.12-27-31.txt)
[2023-03-17 12-27-26.txt](https://github.com/royshil/obs-backgroundremoval/files/11000827/2023-03-17.12-27-26.txt)

**Comment by umireon** [comment]
Can you remove "C:\Program Files\obs-studio\obs-plugins\64-bit\onnxruntime.dll", "C:\Program Files\obs-studio\obs-plugins\64-bit\DirectML.dll", and "C:\Program Files\obs-studio\obs-plugins\64-bit\obs-backgroundremoval.dll" manually?

It seems that the obs-backgroundremoval plugin is loaded but crashed around https://github.com/royshil/obs-backgroundremoval/blob/main/src/background-filter.cpp#L219.

**Comment by umireon** [comment]
Can you try this zip? https://drive.google.com/file/d/13HLcIIcdlStZlKOQpYbFVYVBTyDQcKgr/view?usp=share_link
I suspect that this is caused by the difference between Intel and AMD.

**Comment by umireon** [comment]
I suspect tf->model is NULL.

If there are files on "C:\Program Files\obs-studio\data\obs-plugins\obs-backgroundremoval\*.onnx" and you used this plugin older than 0.5.0, this plugin would crash. ONNX models are moved into "models" directory recently.

You can circumvent this crash by deleting "C:\Program Files\obs-studio\data\obs-plugins\obs-backgroundremoval\*.onnx" files.
Removing this filter from all the sources and add this filter again would recover the crashes.
Alternatively, restore the filter default would also fix the problem.

**Comment by tormyvancool** [comment]
> I suspect tf->model is NULL.
> 
> If there are files on "C:\Program Files\obs-studio\data\obs-plugins\obs-backgroundremoval\*.onnx" and you used this plugin older than 0.5.0, this plugin would crash. ONNX models are moved into "models" directory recently.
> 
> You can circumvent this crash by deleting "C:\Program Files\obs-studio\data\obs-plugins\obs-backgroundremoval\*.onnx" files. Removing this filter from all the sources and add this filter again would recover the crashes. Alternatively, restore the filter default would also fix the problem.

Also the new version you asked me to try: crashed.
but when I removed the .onnx files as you suggested everything worked fine.
What version should I keep now?

**Comment by umireon** [comment]
> What version should I keep now?
v0.5.13 after removed *.onnx files should work.

**Comment by umireon** [comment]
#186 is the fix of this bug.

**Comment by tormyvancool** [comment]
> > What version should I keep now?
> 
> v0.5.13 after removed *.onnx files should work.

Ok I installed the 0.5.13 and without the .ONNX files it works. Thank you for the fix and to get in the next future the 0.5.14
