### ISSUE TITLE
[Part 1] The list of issues that we can close because they are too old and seem not to be applicable to the latest release

### ISSUE THREAD

**Issue by umireon** [royshil/obs-backgroundremoval#188]
- [ ] https://github.com/royshil/obs-backgroundremoval/issues/11 Implemented
- [ ] https://github.com/royshil/obs-backgroundremoval/issues/23 Implemented
- [ ] https://github.com/royshil/obs-backgroundremoval/issues/26 Implemented
- [ ] https://github.com/royshil/obs-backgroundremoval/issues/27 Topic messed
- [ ] https://github.com/royshil/obs-backgroundremoval/issues/32 Resolved
- [ ] https://github.com/royshil/obs-backgroundremoval/issues/35 Implemented
- [ ] https://github.com/royshil/obs-backgroundremoval/issues/36 Resolved
- [ ] https://github.com/royshil/obs-backgroundremoval/issues/37 Topic messed
- [ ] https://github.com/royshil/obs-backgroundremoval/issues/41 Stalled
- [ ] https://github.com/royshil/obs-backgroundremoval/issues/42 Resolved
- [ ] https://github.com/royshil/obs-backgroundremoval/issues/43 Stalled
- [ ] https://github.com/royshil/obs-backgroundremoval/issues/44 Resolved
- [ ] https://github.com/royshil/obs-backgroundremoval/issues/46 Implemented
- [ ] https://github.com/royshil/obs-backgroundremoval/issues/48 Resolved
- [ ] https://github.com/royshil/obs-backgroundremoval/issues/49 Resolved

Many of them are already implemented or proposed some resolution.
The issues that are marked topic messed have too many topics in them and they will gather off-topic comments so they should be closed to keep issues meaningful.
The author of stalled issues are missing for years.

**Comment by umireon** [comment]
@royshil I checked the issues on the 4th page and I suggest many of them can be closed. Can you look into them quickly?
If you are OK, could you close them? I want to organize issues to discuss future development.

**Comment by umireon** [comment]
Thank you for tackling this!

**Comment by royshil** [comment]
ok it's all closed. we can move forward

**Comment by umireon** [comment]
Amazing work, I'm so impressed!
I will check the 3rd page of issues next week and will open a similar issue with classification!
I want our things to be forward, of course!
