### ISSUE TITLE
Background removal plugin disappears after install. 

### ISSUE THREAD

**Issue by ShanghaiTimes** [royshil/obs-backgroundremoval#189]
So, I'm on an M2 Max Mini, Ventura. 2023.
The plugin for ARM appears to install correctly but disappears. I can't find it anywhere, and it doesn't show up in the Filters or Effects lists on OBS anywhere.

Log file.
09:40:11.945: Rosetta translation used: true
09:40:11.946: CPU Name: Apple M2
09:40:11.946: CPU Speed: 2400MHz
09:40:11.946: Physical Cores: 8, Logical Cores: 8
09:40:11.946: Physical Memory: 24576MB Total
09:40:11.946: OS Name: Mac OS X
09:40:11.946: OS Version: Version 13.2.1 (Build 22D68)
09:40:11.946: Kernel Version: 22.3.0
09:40:11.961: hotkeys-cocoa: Using layout 'com.apple.keylayout.British'
09:40:11.962: Current Date/Time: 2023-03-18, 09:40:11
09:40:11.962: Browser Hardware Acceleration: true
09:40:11.962: Qt Version: 5.15.2 (runtime), 5.15.2 (compiled)
09:40:11.962: Portable mode: false
09:40:12.131: OBS 27.2.4 (mac)
09:40:12.131: ---------------------------------
09:40:12.132: ---------------------------------
09:40:12.132: audio settings reset:
09:40:12.132: 	samples per sec: 48000
09:40:12.132: 	speakers:        2
09:40:12.136: ---------------------------------
09:40:12.136: Initializing OpenGL...
09:40:12.181: Loading up OpenGL on adapter Apple Apple M2
09:40:12.181: OpenGL loaded successfully, version 4.1 Metal - 83, shading language 4.10
09:40:12.265: ---------------------------------
09:40:12.265: video settings reset:
09:40:12.265: 	base resolution:   1920x1080
09:40:12.265: 	output resolution: 1920x1080
09:40:12.265: 	downscale filter:  Lanczos
09:40:12.265: 	fps:               30/1
09:40:12.265: 	format:            NV12
09:40:12.265: 	YUV mode:          709/Partial
09:40:12.265: NV12 texture support not available
09:40:12.265: Audio monitoring device:
09:40:12.265: 	name: Default
09:40:12.265: 	id: default
09:40:12.266: ---------------------------------
09:40:12.297: Failed to load 'en-GB' text for module: 'aja-output-ui.so'
09:40:12.298: No AJA devices found, skipping loading AJA UI plugin
09:40:12.298: Failed to initialize module 'aja-output-ui.so'
09:40:12.328: Failed to load 'en-GB' text for module: 'aja.so'
09:40:12.329: No AJA devices found, skipping loading AJA plugin
09:40:12.329: Failed to initialize module 'aja.so'
09:40:12.331: Failed to load 'en-GB' text for module: 'coreaudio-encoder.so'
09:40:12.332: Failed to load 'en-US' text for module: 'decklink-captions.so'
09:40:12.334: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
09:40:12.342: Failed to load 'en-GB' text for module: 'frontend-tools.so'
09:40:12.350: os_dlopen(libpython3.9.dylib->libpython3.9.dylib): dlopen(libpython3.9.dylib, 0x0101): tried: 'libpython3.9.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibpython3.9.dylib' (no such file), '/Applications/OBS.app/Contents/Frameworks/libpython3.9.dylib' (no such file), '/Applications/OBS.app/Contents/Frameworks/libpython3.9.dylib' (no such file), '/Applications/OBS.app/Contents/Frameworks/libpython3.9.dylib' (no such file), '/Applications/OBS.app/Contents/Frameworks/libpython3.9.dylib' (no such file), '/usr/lib/libpython3.9.dylib' (no such file, not in dyld cache), 'libpython3.9.dylib' (no such file), '/usr/lib/libpython3.9.dylib' (no such file, not in dyld cache)
09:40:12.350: 
09:40:12.350: [Python] Could not load library: libpython3.9.dylib
09:40:16.446: Failed to load 'en-GB' text for module: 'mac-capture.so'
09:40:16.448: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
09:40:16.448: No blackmagic support
09:40:16.453: Failed to load 'en-GB' text for module: 'mac-virtualcam.so'
09:40:16.455: Failed to load 'en-GB' text for module: 'mac-vth264.so'
09:40:16.520: [VideoToolbox encoder]: Adding VideoToolbox H264 encoders
09:40:16.527: [obs-browser]: Version 2.17.13
09:40:16.527: [obs-browser]: CEF Version 95.0.0-MediaHandler.2462+g95e19b8+chromium-95.0.4638.69
09:40:16.631: Failed to load 'en-GB' text for module: 'obs-vst.so'
09:40:16.633: Failed to load 'en-GB' text for module: 'obs-x264.so'
09:40:16.635: Failed to load 'en-GB' text for module: 'rtmp-services.so'
09:40:16.651: [vlc-video]: VLC 3.0.18 Vetinari found, VLC video source enabled
09:40:16.651: ---------------------------------
09:40:16.651:   Loaded Modules:
09:40:16.651:     vlc-video.so
09:40:16.651:     text-freetype2.so
09:40:16.651:     rtmp-services.so
09:40:16.651:     obs-x264.so
09:40:16.651:     obs-vst.so
09:40:16.651:     obs-transitions.so
09:40:16.651:     obs-outputs.so
09:40:16.651:     obs-filters.so
09:40:16.651:     obs-ffmpeg.so
09:40:16.651:     obs-browser.so
09:40:16.651:     mac-vth264.so
09:40:16.651:     mac-virtualcam.so
09:40:16.651:     mac-syphon.so
09:40:16.651:     mac-decklink.so
09:40:16.651:     mac-capture.so
09:40:16.651:     mac-avcapture.so
09:40:16.651:     image-source.so
09:40:16.651:     frontend-tools.so
09:40:16.651:     decklink-ouput-ui.so
09:40:16.651:     decklink-captions.so
09:40:16.651:     coreaudio-encoder.so
09:40:16.651: ---------------------------------
09:40:16.652: ==== Startup complete ===============================================
09:40:16.723: All scene data cleared
09:40:16.724: ------------------------------------------------
09:40:21.981: coreaudio: device 'iPhone 11 Microphone' initialized
09:40:21.982: [Loaded global audio device]: 'Mic/Aux'
09:40:22.011: adding 21 milliseconds of audio buffering, total audio buffering is now 21 milliseconds (source: Mic/Aux)
09:40:22.011: 
09:40:22.047: coreaudio: device 'Unknown USB Audio Device' initialized
09:40:22.047: [Loaded global audio device]: 'Mic/Aux 2'
09:40:22.078: adding 21 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Mic/Aux 2)
09:40:22.078: 
09:40:22.168: Logitech: Selected device 'USB Camera VID:1133 PID:2085'
09:40:22.170: Logitech: Preset 1920x1080 not available
09:40:22.170: Logitech: Using preset 1280x720
09:40:22.344: coreaudio: device 'SWB Audio Capture' initialized
09:40:22.346: iPhone: Selected device 'iPhone 11 Camera'
09:40:22.346: iPhone: Using preset 1280x720
09:40:22.394: coreaudio: failed to find device uid: BuiltInHeadphoneInputDevice, waiting for connection
09:40:22.430: Switched to scene 'Camera Only'
09:40:22.430: ------------------------------------------------
09:40:22.430: Loaded scenes:
09:40:22.430: - scene 'Dual Scene':
09:40:22.430:     - source: 'AudioCapture' (coreaudio_input_capture)
09:40:22.430:     - source: 'Samsung Screen Right' (group)
09:40:22.430:         - source: 'Display Capture 2' (display_capture)
09:40:22.430:         - source: 'iPhone' (av_capture_input)
09:40:22.430:         - source: 'OBS Overlay.001.png' (image_source)
09:40:22.430:     - source: 'HP Screen Left' (group)
09:40:22.430:         - source: 'Background' (image_source)
09:40:22.430:             - filter: 'Crop/Pad' (crop_filter)
09:40:22.430:             - filter: 'Image Mask/Blend' (mask_filter)
09:40:22.430:         - source: 'Display Capture' (display_capture)
09:40:22.430:         - source: 'iPhone' (av_capture_input)
09:40:22.430:         - source: 'Logitech' (av_capture_input)
09:40:22.430:         - source: 'OBS Overlay.001.png' (image_source)
09:40:22.430:     - source: 'Audio Input Capture' (coreaudio_input_capture)
09:40:22.430: - scene 'Camera Only':
09:40:22.430:     - source: 'iPhone' (av_capture_input)
09:40:22.430:     - source: 'Logitech' (av_capture_input)
09:40:22.430: ------------------------------------------------
09:44:27.949: iPhone: Device with unique ID '41434133-0000-0000-0000-000000000001' disconnected
09:44:28.251: coreaudio: device 'iPhone 11 Microphone' disconnected or changed.  attempting to reconnect

**Comment by umireon** [comment]
You need to install the x86_64 variant of this plugin when you use Intel OBS.
If you want to use the Apple Silicon variant of this plugin, please reinstall OBS itself and ensure you use Apple Silicon OBS.

**Comment by umireon** [comment]
Your OBS installation is the Intel OBS.

**Comment by ShanghaiTimes** [comment]
Thanks, that got it. I had obs left over from my old iMac Intel and just restored it all on the M2.Thanks-----Robert ***@***.***_A_ChalmersOn 18 Mar 2023, at 10:06 am, Kaito Udagawa ***@***.***> wrote:﻿
You need to install the x86_64 variant of this plugin when you use Intel OBS.
If you want to use the Apple Silicon variant of this plugin, please reinstall OBS itself and ensure you use Apple Silicon OBS.
