### ISSUE TITLE
obs: symbol lookup error: /usr//lib/x86_64-linux-gnu/obs-plugins/obs-backgroundremoval.so: undefined symbol: cpuinfo_initialize

### ISSUE THREAD

**Issue by piphoser** [royshil/obs-backgroundremoval#195]
OBS 29.0.2 from OBS ppa:obsproject/obs-studio repository crashes when adding the backgroundremoval filter with the above error message:  obs: symbol lookup error: /usr//lib/x86_64-linux-gnu/obs-plugins/obs-backgroundremoval.so: undefined symbol: cpuinfo_initialize

Is there a dependency I'm missing?

**Comment by royshil** [comment]
yes apparently something is wrong
we're looking into it
thanks for the issue

this is a duplicate of #194

**Comment by royshil** [comment]
@piphoser  can you try https://github.com/royshil/obs-backgroundremoval/suites/11693307176/artifacts/608110162 ?

**Comment by royshil** [comment]
this seems to be resolved
