### ISSUE TITLE
New BG segmentation models

### ISSUE THREAD

**Issue by ankitbko** [royshil/obs-backgroundremoval#2]
Checkout this and see if this gives better result https://elder.dev/posts/open-source-virtual-background/

I am not C++ developer so unfortunately cannot contribute directly over here. Hopefully this will help.

**Comment by royshil** [comment]
that solution is using a general purpose net (MobileNetV1) which is fine. I can try to include several models to switch between to get the best result

**Comment by simonbunge** [comment]
Great work, @royshil!! While your at adding selectable models, [MODNet ](https://github.com/ZHKKKe/MODNet) would be a cool one to try. A pre-made [ONNX version](https://drive.google.com/file/d/1cgycTQlYXpTh26gB9FTnthE7AvruV8hd/view?usp=sharing) is available, so should be straightforward enough. Not that I have looked into any detail, but a few tweaks to input/ output scaling and normalisation should do it. Let me know if you want any help.

**Comment by simonbunge** [comment]
Thank you, @royshil. Can't believe how quickly you got that to work (as I just established it actually does). Massive kudos!!
