### ISSUE TITLE
makepkg install is wrong

### ISSUE THREAD

**Issue by r3k2** [royshil/obs-backgroundremoval#21]
on Arch GNU/Linux the plugin needs to be installed under the home config or if you want to do it for all users as the package is setup to do in this case, to /usr/lib/obs-plugins

**Comment by royshil** [comment]
please try the latest updates to PKGBUILD or use the latest pre-built package https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.2.5-beta

**Comment by r3k2** [comment]
this is working I deleted everything and my git clone and re-pulled from master did the arch package and installed and everything works now with out any linking. thanks
