### ISSUE TITLE
0.5.15 cannot work with the color formats which has more than one plane

### ISSUE THREAD

**Issue by Sparronator9999** [royshil/obs-backgroundremoval#212]
**Describe the bug**
When applying the `Background Removal` filter from this plugin to any source, the source will disappear until the filter is removed or hidden. This will cause a green video until the source is hidden and shown.

Additionally, the `Background Color` property seems to be missing from the latest release.

**To Reproduce**
1. Add a `Background Removal` filter to any source
2. Make sure it's enabled
3. Source output will disappear

**Expected behavior**

**Screenshots**

https://user-images.githubusercontent.com/86388887/227756226-000aed23-d9d2-4b64-bd11-5783350ce4b5.mp4

**Desktop (please complete the following information):**
- OS: Windows 10 (22H2)
- Browser: N/A
- Plugin Version: v0.5.15
- OBS Version: v29.0.2
- GPU: NVIDIA GeForce GTX 1650 (Max-Q)

**Additional context**
I have reproduced this bug with both a `Media Source` and `Video Capture Device`, with any `Segmentation Model`, `Inference device`, `Blur Background Factor` or `Calculate Mask every X frame` setting.

**Comment by umireon** [comment]
@Sparronator9999 Can you post here the OBS log?

**Comment by umireon** [comment]
> Additionally, the Background Color property seems to be missing from the latest release.

The Background Color property was removed from the latest release.

**Comment by umireon** [comment]
I confirmed that 0.5.15 doesn't work with Media Source

**Comment by Sparronator9999** [comment]
> @Sparronator9999 Can you post here the OBS log?

Where can I find the OBS log?

> I confirmed that 0.5.15 doesn't work with Media Source

This also doesn't work with `Video Capture Device`.

**Comment by umireon** [comment]
You can find it at Help menu!

**Comment by umireon** [comment]
I think the very first frame was shown.

**Comment by Technetium1** [comment]
Here's some logs of it not working. It changes the color of the source used until deactivated 🤔 

[2023-03-26 01-50-05.txt](https://github.com/royshil/obs-backgroundremoval/files/11070884/2023-03-26.01-50-05.txt)
[2023-03-26 01-47-29.txt](https://github.com/royshil/obs-backgroundremoval/files/11070885/2023-03-26.01-47-29.txt)

**Comment by Sparronator9999** [comment]
@umireon, here is an OBS log of the issue:

[2023-03-26 16-57-55.txt](https://github.com/royshil/obs-backgroundremoval/files/11070891/2023-03-26.16-57-55.txt)

**Comment by umireon** [comment]
@Sparronator9999
@Technetium1 
I made #213, which is the possible fix to this problem. The Windows binary will be available on #213 soon and I want you to try it.

**Comment by umireon** [comment]
I think if there are more than one data plane, the image would be broken.

**Comment by umireon** [comment]
@Sparronator9999 

I confirmed the root cause of this bug and changed the title corresponding to the root cause.

**Comment by umireon** [comment]
I believe that 0.5.15 works with the YUY2 color format but does not work with the I420 color format

**Comment by umireon** [comment]
Just 10 minutes for #213 build

**Comment by umireon** [comment]
We have to wait for all jobs finished until the artifacts available

**Comment by umireon** [comment]
I forgot to label the PR

**Comment by umireon** [comment]
Just restarted the GHA and the artifacts will be available in 15 minutes.

**Comment by umireon** [comment]
I had misconfigured the CI and Windows artifacts were not available last time sorry.
This time would be fine.

**Comment by umireon** [comment]
@Sparronator9999 Please try this!
https://github.com/royshil/obs-backgroundremoval/suites/11813359950/artifacts/616823315

**Comment by umireon** [comment]
I noticed that HW decoding on Media Source prevents this plugin from working.
I will create another issue to track this problem.

**Comment by umireon** [comment]
#214

**Comment by umireon** [comment]
@Sparronator9999 Can you try to restart OBS please?

**Comment by umireon** [comment]
I don't think the YUY2 format is broken. Maybe due to #214

**Comment by Technetium1** [comment]
Willing to help test, just let me know which artifact to use, looks like https://github.com/royshil/obs-backgroundremoval/actions/runs/4524237852 is the most recent?

**Comment by umireon** [comment]
@Sparronator9999
The range is fixed to the partial range in the current implementation so thus this behavior is as expected.
https://github.com/royshil/obs-backgroundremoval/blob/main/src/background-filter.cpp#L335

Can you open another separate issue to track this problem?

**Comment by umireon** [comment]
@Technetium1 The latest one is available here!
https://github.com/royshil/obs-backgroundremoval/actions/runs/4524237852#:~:text=macos%2Dx86_64%2D128e98514-,obs%2Dbackgroundremoval%2Dwindows%2Dx64%2D128e98514,-35.9%20MB

**Comment by Technetium1** [comment]
@umireon Working great so far, no weird issues, no random color change when it stops, and most importantly no crash. Seems great!

**Comment by umireon** [comment]
https://github.com/royshil/obs-backgroundremoval/pull/220 will fix this
