### ISSUE TITLE
Background Removal effect only works with Limited colour space

### ISSUE THREAD

**Issue by Sparronator9999** [royshil/obs-backgroundremoval#218]
**Describe the bug**
When using the plugin with any source, the plugin will change the colours of the output. See the screenshots for an example.

**To Reproduce**
1. Add a `Video Capture Device` source to any scene in OBS
2. Go to `Effects`, and add a `Background Removal` filter to the camera.
3. Drag the `Threshold` slider to `1.00` to see the result clearer
4. Compare the video with the effect enabled and disabled

**Expected behavior**
Background removal effect doesn't affect colours of visible portion

**Screenshots**
Background Removal Enabled | Background Removal Disabled
--------|---------
![Background Removal Enabled](https://user-images.githubusercontent.com/86388887/227832822-c78d48a7-f7a2-4b83-b94f-81e7d83820c1.png) | ![Background Removal Disabled](https://user-images.githubusercontent.com/86388887/227832824-f3a7ad28-a284-46c1-9cdb-afc73d04684c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (22H2)
 - Browser: N/A
 - Plugin Version: latest commit of #213
 - OBS Version: 29.0.2

**Additional context**
Created at @umireon's request.

**Comment by umireon** [comment]
I don't think #217 is for this issue

**Comment by umireon** [comment]
We have to investigate about the color space on OBS Graphics subsystem. Everything is set as default now.

**Comment by umireon** [comment]
Please try this!

https://github.com/royshil/obs-backgroundremoval/suites/11907360441/artifacts/623490881
