### ISSUE TITLE
Race condition against cv::Mat causes OBS to crash

### ISSUE THREAD

**Issue by Sparronator9999** [royshil/obs-backgroundremoval#223]
**Describe the bug**
When changing certain settings, such as deactivating and re-activating a source, OBS Studio will crash.

**To Reproduce**
This bug seems to occur at random while changing settings, but this is how I reproduced it:
1. Add a Video Capture Device to any scene
2. Add a Background Removal filter
3. Deactivate and reactivate the video capture device
4. Crash

**Expected behavior**
OBS does not crash when using this plugin

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 (22H2)
 - Browser: N/A
 - Plugin Version: f96d5da, as provided by GitHub Actions
 - OBS Version 29.0.2

**Additional context**
Crash reports:
[Crash 2023-03-29 15-40-19.txt](https://github.com/royshil/obs-backgroundremoval/files/11096637/Crash.2023-03-29.15-40-19.txt)

[Crash 2023-03-29 15-51-41.txt](https://github.com/royshil/obs-backgroundremoval/files/11096694/Crash.2023-03-29.15-51-41.txt)

Logs:
[2023-03-29 15-41-50.txt](https://github.com/royshil/obs-backgroundremoval/files/11096640/2023-03-29.15-41-50.txt)

[2023-03-29 15-46-58.txt](https://github.com/royshil/obs-backgroundremoval/files/11096693/2023-03-29.15-46-58.txt)

**Comment by umireon** [comment]
@Sparronator9999 Thank you for reporting! Try #223 I hope this fixes the problem

**Comment by umireon** [comment]
Yes

**Comment by umireon** [comment]
The testing binary available here now: https://github.com/royshil/obs-backgroundremoval/suites/11880971780/artifacts/621589166

**Comment by umireon** [comment]
Please try #225

**Comment by umireon** [comment]
@Sparronator9999 What do you mean by enable and disable? Adding and removing this plugin from the effect filter list?

**Comment by umireon** [comment]
I think I could have reproduced this bug
