### ISSUE TITLE
The Mac OS Arm64 install package doesn't work properly

### ISSUE THREAD

**Issue by virtualflo** [royshil/obs-backgroundremoval#226]
**Describe the bug**
When I try to install the pkg package for mac Os arm64 nothing happens

**To Reproduce**
1 - Download https://github.com/royshil/obs-backgroundremoval/releases/download/v0.5.15/obs-backgroundremoval-0.5.15-macos-arm64.pkg
2 - Install the package
3 - Restart OBS, the filter isn't available
4 - Check the plugin folder of OBS backgroundremoval isn't there

**Expected behavior**
Install the plugin for OBS on a Mac M1

**Screenshots**
Not relevant

**Desktop (please complete the following information):**
 - OS: Ventura 13.1 
 - Browser Chrome
 - Plugin Version 0.5.15
- OBS Version 29.0.2

**Additional context**

**Comment by umireon** [comment]
@virtualflo Can you post the OBS log here? I want to ensure if you have Intel OBS or Apple Silicon OBS.
You can get log files from Help menu.

**Comment by royshil** [comment]
there are two possible install places for the plugin as well: `/Library/Application Support` and `~/Library/Application Support`
Did you look in both places?

**Comment by umireon** [comment]
I found an installer bug. #227 maybe related.

**Comment by virtualflo** [comment]
@umireon no apparently it's not related. I remove every space.

@royshil I checked both place and didn't find anything.

My log files: https://obsproject.com/logs/TZMW8hEGPZfWkNdt

**Comment by umireon** [comment]
@virtualflo You are using Intel OBS so you need to install the x86_64 version.
The ARM64 version won't work on your OBS unless you reinstall Apple Silicon OBS.
