### ISSUE TITLE
High Computepower Usage - low FPS

### ISSUE THREAD

**Issue by metzger100** [royshil/obs-backgroundremoval#23]
I love this Plugin but it demands min. 30% of my CPU-Usage when I use the GPU-Render on my Windows System. Without Recording or Streaming. The performance drop to 18 FPS.
I am not sure if it is possible to reduce that. If not please close the Issue.

**Comment by tatunts** [comment]
Hello @metzger100, do you happen to have an AMD CPU? With my 3900x CPU usage is simply too high, even with GPU on. Thanks.

**Comment by metzger100** [comment]
Hella @tatunts I am using a Intel Quadcore CPU. So its not CPU related.

**Comment by JiaChen-Zeng** [comment]
Same issue. I'm using GTX 1650 but CPU usage is constantly over 80%.

**Comment by darkarp** [comment]
Same, with an i7-9700K and an RTX 2080 Super

**Comment by metzger100** [comment]
Small Update: I switched to Ryzen 5 1600X and the Issue is still the case. 
My CPU Usage is aboput 40% but the FPS drop to 12-22 FPS. I don't why. It wouldn't be an Issue if the Plugin uses more CPU, but it doesn't and begins to reduce the FPS. It looks like it is kind of inefficient after the Segmentation of Zoom, Google Meet and co use way less compute power. Or it is a Problem with Windows 10.

**Comment by uniqueum** [comment]
AMD Ryzen 7 2700X here with an RX 580 8GB -- so I genereally let the CPU handle all the rendering.
Either way, whether I choose CPU or GPU, my FPS drops way below 15 (with Robust Video Matting even below 10), even though the CPU shoots to a rocket 40%+.

Would love to use the plugin for streaming and/or recording, but as of now it's quite frankly unusable. :/

**Comment by royshil** [comment]
we offer directml acceleration on windows now.
