### ISSUE TITLE
OBS Background Removal consumes excessive resources when effect is not visible

### ISSUE THREAD

**Issue by Sparronator9999** [royshil/obs-backgroundremoval#236]
**Describe the bug**
When the background removal effect is not visible (hidden using the "eye" icon, or the source is deactivated), the background removal plugin uses approximately the same amount of CPU as when it is enabled and visible.

**To Reproduce**
1. Open Task Manager to the Performance tab to see the difference in resource usage
2. Open OBS, add a Background Removal filter to any source
3. Toggle the visibility of the effect (or deactivate/reactivate the source)
4. Notice that the CPU (and GPU, if using GPU inference) resources do not change until the effect is removed

**Expected behavior**
CPU/GPU resources drop when the plugin effect is disabled (but still in the list of effects for a source)

**Screenshots**
Annotated screenshot of the resource usage issue:
![Capture2](https://user-images.githubusercontent.com/86388887/229025534-be059953-1fb1-4bd0-96a1-3bf5ab6aa24d.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 (22H2)
 - Browser: N/A
 - Plugin Version: Latest commit (f4f616c) from GitHub Actions
 - OBS Version: 29.0.2

**Additional context**
Log file: [2023-03-31 15-42-10.txt](https://github.com/royshil/obs-backgroundremoval/files/11118252/2023-03-31.15-42-10.txt)

**Comment by umireon** [comment]
I've made a fix on https://github.com/royshil/obs-backgroundremoval/pull/237

**Comment by umireon** [comment]
Can you try this?
https://github.com/royshil/obs-backgroundremoval/suites/11937178201/artifacts/625605884

**Comment by umireon** [comment]
I fixed the problem 
https://github.com/royshil/obs-backgroundremoval/suites/11959477069/artifacts/627295852

**Comment by umireon** [comment]
@Sparronator9999 Can you post here the screenshot of the Deactivate button?
I couldn't find the button on my OBS.

**Comment by umireon** [comment]
@Sparronator9999 
This Deactivate button is Windows-specific and implemented on the win-dshow plugin not on OBS core itself.
So I don't want to add support for this Deactivate button because it's very hard for us to handle.
