### ISSUE TITLE
Does background removal trigger WHEA-logger 18 error on 5900x?

### ISSUE THREAD

**Issue by fcordella** [royshil/obs-backgroundremoval#239]
**Describe the bug**
After upgrading to versione 0.5.16, using background removal triggers a WHEA-logger 18 on a Ryzen 9 5900x, causing the reboot of the system (there is no BSOD). After the reboot, Logitech StreamCam is frozen and is not recognized by Windows 11: you have to unplug from PC and reconnect, so it works again.

**To Reproduce**
1. Go to right click on the source to which apply the background removal 
2. Click on filter
3. Add background removal to effects 
4. Wait for the reboot.

**Expected behavior**
It shouldn't reboot.

**Screenshots**
NO screenshot, as the system reboot itself.

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Plugin Version 0.5.16
- OBS Version 29.0.2

**Additional context**
Without background removal, it looks like the system works fine.
[2023-03-31 02-11-50.txt](https://github.com/royshil/obs-backgroundremoval/files/11120728/2023-03-31.02-11-50.txt)
The file attached is the OBS log right before the last reboot with WHEA-logger 18 error

**Comment by umireon** [comment]
When you set the number of 'Caculate mask every X frame' to be 10, does this problem persist?

I doubt that the high CPU usage of this plugin causes this problem and the root cause of this problem is not on this plugin.

**Comment by fcordella** [comment]
Yes, it does if I set  'Caculate mask every X frame' to 10.

**Comment by umireon** [comment]
Could you please post the detail of the WHEA-logger 18 error here?
I suppose it would be on Windows Event Log.
