### ISSUE TITLE
background color channels seem to be in wrong order

### ISSUE THREAD

**Issue by stahlratte** [royshil/obs-backgroundremoval#24]
When i set #0000ff as the background color the picker shows it as blue, but the output color is actually red. Other way around also works (#ff0000 -> blue).
So probably somewhere the channel order needs to be reversed.

**Comment by olhado** [comment]
I've seen this too. Perhaps in this area of the code? https://github.com/royshil/obs-backgroundremoval/blob/main/src/background-filter.cpp#L251-L254

I might try and open a PR, but until the CPU usage drops, I can't really use the plugin.

**Comment by royshil** [comment]
i'll fix this very soon. along with the new background segmentation model

**Comment by royshil** [comment]
This was resolved in the latest release,
