### ISSUE TITLE
OBS Filter Crop/Pad is not working properly when Background Removal is on

### ISSUE THREAD

**Issue by breadncup** [royshil/obs-backgroundremoval#243]
**Describe the bug**

OBS Filter Crop/Pad is not working properly when Background Removal is on

**To Reproduce**

1. Add Video Capture with a camera
2. Select the Filter from the Video Capture Source
3. Select Background Removal
4. Select the Blur Background factor as 1
5. Close
6. Select the Filter again from the Video Capture Source
7. Select Crop/Pad
8. Adjust Top as 300 and Bottom as 700
9. Compare when Background Removal is Off and On
10. The Top value in Crop/Pad does not work. (It crops from the bottom always)

**Expected behavior**

The Top Value in Crop/Pad should work as expected no matter what.

**Screenshots**

* When Background Removal is OFF
![Background Removal Off](https://user-images.githubusercontent.com/685504/229680644-b2c45fb2-9bd8-4949-a6a9-9d7f9a499cf8.png)

* When Background Removal is ON
![Background Removal On](https://user-images.githubusercontent.com/685504/229680652-3d24d1c8-4f39-4258-bbdc-fef370f65fbf.png)

**Log and Crash Report**

[2023-04-03 20-22-30.txt](https://github.com/royshil/obs-backgroundremoval/files/11144415/2023-04-03.20-22-30.txt)

**Desktop (please complete the following information):**

 - OS: macOS Ventura
 - Browser: Safari
 - Plugin Version: 0.5.16
 - OBS Version: 29.0.2

**Comment by umireon** [comment]
I doubt this line should be `obs_source_video_render(tf->source)` but not been tested.
https://github.com/royshil/obs-backgroundremoval/blob/main/src/background-filter.cpp#L555

**Comment by umireon** [comment]
@breadncup
I've fixed this bug on #244. Can you try the following binary?
https://github.com/royshil/obs-backgroundremoval/suites/12063343066/artifacts/634667122
