### ISSUE TITLE
Performance Idea - option to reprocess mask every X frames

### ISSUE THREAD

**Issue by iBenMoore** [royshil/obs-backgroundremoval#25]
I've had to opportunity to use this plugin now on several occasions to feed the virtual camera output into webex meetings, and it's been working well, but like many others I find that cpu usage is a bottleneck that effects performance.  Tweaking and/or trying out different models could improve that.  But another thing I was thinking of, and I'm not sure how feasible it is, but maybe an option could be created to reprocess the mask every X frames?

I'm guessing the work of the models reprocessing what the mask should be is the big hitter on cpu.  Right now I can run about 15fps max against my cpu's (with some frame droppage), which isn't the smoothest experience as far as watching lips move on a web meeting, etc,  But even rendering at 5fps the mask seems to hold up well.  So I was thinking, what if for example there was an option to only reprocess the mask every X frames.  Then, if you wanted the existing experience, you could set it to1, but it might be possible in my case to set it to 5 and be able to render 30fps video while in the background the models are only actually having to process 6fps.  Again, I haven't reviewed the code to get an idea of how feasible it would be to implement, just throwing another idea out there on a way to maybe improve performance.

**Comment by royshil** [comment]
thanks for the suggestion @iBenMoore 

my intuition tells me that if we had a good segmentation model with very small input e.g. 32x32 or 48x48 - we can still reach a good visual experience (with contour smoothing) with very high frame rates. This is where i'll be spending my efforts in the short term.

**Comment by fangfufu** [comment]
Google's new Mediapipe library can achieve very high performance without GPU. 
https://google.github.io/mediapipe/solutions/selfie_segmentation

I have replaced the backend of my webcam background replacement tool with it:
https://github.com/fangfufu/Linux-Fake-Background-Webcam

**Comment by royshil** [comment]
@fangfufu 
Unfortunately 
```
2021-06-08 21:00:00,604 - ERROR - Tensorflow op [segment: TFL_Convolution2DTransposeBias] is not supported
2021-06-08 21:00:00,604 - ERROR - Unsupported ops: Counter({'TFL_HARD_SWISH': 11, 'TFL_Convolution2DTransposeBias': 1})
```

**Comment by fangfufu** [comment]
@royshil , where do these error messages come from?

**Comment by royshil** [comment]
When i try to convert the `.tflite` model to `.onnx` with the official converter https://github.com/onnx/tensorflow-onnx

**Comment by fangfufu** [comment]
Ah ok.

**Comment by iBenMoore** [comment]
Looks like there might be a Mediapipe meet onnx model here to try:  https://reposhub.com/dotnet/machine-learning-and-data-science/keijiro-MeetBarracuda.html

**Comment by royshil** [comment]
Please see the latest release for the Meet model and another lightweight model.
The difference in performance is not very big, but the new models are faster.
