### ISSUE TITLE
add the ability to have yolov8 create the bounding box for the background removal

### ISSUE THREAD

**Issue by Pickymarker** [royshil/obs-backgroundremoval#251]
add the ability to have yolov8 create the bounding box for the background removal https://github.com/akanametov/yolov8-face https://github.com/ultralytics/ultralytics

**Comment by umireon** [comment]
We cannot include the library you suggested because our plugin is GPL-2.0 and their library is GPL-3.0

**Comment by Pickymarker** [comment]
but there yolov8 models are opensource and they allow anyone to use it for free

**Comment by Pickymarker** [comment]
![image](https://user-images.githubusercontent.com/74084396/231408214-de55057c-beb9-473d-b6ad-b76c5ef2df61.png)

https://www.gnu.org/licenses/license-list.html#:~:text=Please%20note%20that%20GPLv3%20is,to%20make%20the%20desired%20combination.

**Comment by Pickymarker** [comment]
yolov8face has these models 
![image](https://user-images.githubusercontent.com/74084396/231535722-fcdc44dc-00c8-41b5-9e4f-e7f194cb3a57.png)
and [ultralytics](https://github.com/ultralytics/ultralytics)? has these models 
![image](https://user-images.githubusercontent.com/74084396/231536679-2d668236-e6c4-4c2d-bf5a-6409977f4e8e.png)
![image](https://user-images.githubusercontent.com/74084396/231536692-588ac43e-4baf-4317-9bfb-6b3aeb6e8e49.png)
![image](https://user-images.githubusercontent.com/74084396/231536704-c183363c-9c18-4da9-8e6e-755b84a48a75.png)
![image](https://user-images.githubusercontent.com/74084396/231536714-5224b19b-0ab7-4082-8abd-d0119dd51ae5.png)
 and all them are for different purposes i gave you links to all yolov8 models so you can pick which one is the best for the purpose.

**Comment by royshil** [comment]
i can't see a yolov8 model for portrait segmentation though
and the general purpose models are far too big and slow - since they are geared towards imagenet (1000 classes) and not just portrait segmentation

an option is to train our own model using the yolov8 nano architecture
but that's an involved process.
