### ISSUE TITLE
Filter not found

### ISSUE THREAD

**Issue by thematrixiam** [royshil/obs-backgroundremoval#261]
**Describe the bug**

Can not find filter in the pulldown list when I add new filter.

**To Reproduce**

1. Go to 'Sources'
2. Right Click on 'video capture device'
3. Scroll down to 'Filters'
4. Select "+" sign to add new filter
5. Notice that the filter is not shown

**Expected behavior**

I expect to see the filter in the pulldown list

**Screenshots**

Pretty self explanitory, not needed.

**Log and Crash Report**

no crash.

**Desktop (please complete the following information):**

 - OS: win10
 - Browser: chrome
 - Plugin Version: 0.5.16
 - OBS Version: 29.0.2

**Additional context**

Tried both .exe method and zip method

**Comment by umireon** [comment]
Can you post the screenshot here?

**Comment by thematrixiam** [comment]
[2023-04-14 10-55-01.txt](https://github.com/royshil/obs-backgroundremoval/files/11235322/2023-04-14.10-55-01.txt)

![not found filter](https://user-images.githubusercontent.com/8868512/232109263-766f7b3a-2303-4e2e-8ceb-3a0cc72084d5.jpg)

**Comment by umireon** [comment]
This filter would be available under Effect filters.
You are looking the Audio/Video filters and this filter is not listed there.

**Comment by thematrixiam** [comment]
yep... that was the problem... thanks
