### ISSUE TITLE
Unable to build on Arch

### ISSUE THREAD

**Issue by ngoonee** [royshil/obs-backgroundremoval#262]
**Describe the bug**
Building from git master on Arch throws an error after OpenCV_Build
[ 72%] Built target OpenCV_Build
make[2]: *** No rule to make target 'OpenCV_Build-prefix/lib/libopencv_imgproc.a', 
needed by 'obs-backgroundremoval.so'.  Stop.
make[2]: *** Waiting for unfinished jobs....

Using the following PKGBUILD (slightly modified from AUR one, just removing unnecessary patches) - the build() function is the 'meat' of it
[PKGBUILD.txt](https://github.com/royshil/obs-backgroundremoval/files/11227747/PKGBUILD.txt)

Attaching the complete build log:-

[errors.txt](https://github.com/royshil/obs-backgroundremoval/files/11227745/errors.txt)

**Comment by ohadeytan** [comment]
Similar error on Fedora 37

**Comment by royshil** [comment]
is it possible create a CI pipeline for Arch builds?

**Comment by umireon** [comment]
Yes we can do Arch build on containers of GitHub Actions
https://docs.github.com/ja/actions/using-jobs/running-jobs-in-a-container

**Comment by ngoonee** [comment]
Thanks for completing this and #266 - have updated the AUR PKGBUILD for git, and just adopted and pushed the PKGBUILD for non-git as well.
