### ISSUE TITLE
Blur background factor for v0.5.17 for OBS 29.0.2 [mac] cannot exceed a maximum of 20.

### ISSUE THREAD

**Issue by perryrivera1** [royshil/obs-backgroundremoval#269]
**Describe the bug**

Blur background factor for v0.5.17 for OBS 29.0.2 [mac] cannot exceed a maximum of 20.

**To Reproduce**

1. Install OBS 29.0.2 (max)
2. Install the https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.5.17 pkg file
3. Add the effect filter for Background Removal
4. Can't exceed a max of 20 (see screenshot)

**Expected behavior**

I've seen videos on the internet max this out to 100.

**Screenshots**
![Image 4-21-23 at 1 29 PM](https://user-images.githubusercontent.com/93743187/233729481-36b975e8-d3db-4f4a-931b-7179d7f5ea40.jpeg)

**Log and Crash Report**

NA

**Comment by umireon** [comment]
The maximum value of this setting was recently changed.
It is not a bug but an expected change.
https://github.com/royshil/obs-backgroundremoval/pull/255/files#diff-4e873e25a59f1bf23600cc652a834a24cb84ecf53e865840736f921b5f7a0160L146
