### ISSUE TITLE
Background Remover crashes OBS

### ISSUE THREAD

**Issue by OBS1227** [royshil/obs-backgroundremoval#27]
Hi.
I was told by the developer that he hasn't updated it for OBS 27 yet and to bring my issue here.  I was able to install it and open it in OBS 27, but every time I activate a camera either externally or internally it crashes. My main computer is a Mac OS High Sierra and this is what the OBS log report was. Thanks: 
 https://obsproject.com/logs/1B8vp1Uag7iHbEsg

**Comment by anoril1979** [comment]
Hi!

I got the same issue with OBS 26.1.1 on Win10: the plugin starts and is visible as a Video plugin, but when activated, the camera feedback goes black and OBS hangs. 
Best regards,
Paul

(No crash log as I have to kill OBS as it hangs forever...)

**Comment by royshil** [comment]
I now upgraded the plugin for v27
Please try to install it now and see if it works, @OBS1227 @anoril1979

**Comment by packysauce** [comment]
Howdy! It's 4am so i'll be brief:
https://github.com/royshil/obs-backgroundremoval/blob/main/src/background-filter.cpp#L282
if i remove the std::string(newModel) call and just use newModel, it stops crashing and everything works.
popOS 21.04, built obs and plugin into ~/.local and have been debugging as best i can with vscode.
sleepy times, lemme know if i can get you more convincing details (its a recent change too, so could be - im out of my depth on my c++ quirks)

**Comment by anoril1979** [comment]
I updated OBS to 27 and get the last build (after comment from Royshil) and it works fine!
Thanks

**Comment by royshil** [comment]
@OBS1227 @packysauce  are you able to run the plugin with v27?

**Comment by packysauce** [comment]
(i'm compiling it myself, not using the release)
I got it running with v27, had to remove that std::string() i mentioned, but that got me sorted out.
fun fact, running with CUDA was basically removing _DML and using _CUDA! neat!

**Comment by royshil** [comment]
@packysauce can you confirm the CUDA version actually uses the NVidia GPU instead of the CPU? i couldn't get it to work on my PC that has an Nvidia GPU

**Comment by packysauce** [comment]
went ahead and put up what I've been using. nvidia-smi, cpu util, and fan noise all seem to suggest it's running on the GPU

**Comment by vxf** [comment]
I also had to remove that std::string() constructor and hopefully let the compiler handle the copy, now all works perfect. I'm using gcc 7.5.0 and I also had to add the missing NULL fields in background_removal_filter_info declaration, so I guess @royshil  uses different compilers on Linux.

**Comment by wwsh** [comment]
hi! on my integrated NVIDIA GTX960m there's no way I can make it work with OBS. Which GPu have u tested with your btw great plugin ? Cheers

**Comment by max-allan-surevine** [comment]
v27 fails for me. I see about a second of background removal (from my video camera source). And then it crashes OBS completely. No delays etc.

**Comment by LukeFree91** [comment]
> v0.3.0beta fails for me. I see about a second of background removal (from my video camera source). And then it crashes OBS completely. No delays etc.

Yep I have the same issue!

**Comment by royshil** [comment]
Please try https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.4.0
@LukeFree91 @max-allan-surevine @wwsh @vxf @packysauce

**Comment by ftraxxler** [comment]
If have tried to install it on arch linux with makepkg -s and then pacman -U but my obs also crashes when I am trying to set the filter ? I have the version 0.3.0beta and not the 0.4.0 because makepkg creates 0.3.0 and 0.4.0

**Comment by royshil** [comment]
@ftraxxler  i'll work on the 0.4.0 for arch linux... should be up soon

**Comment by ftraxxler** [comment]
> @ftraxxler i'll work on the 0.4.0 for arch linux... should be up soon

Installed it a few seconds ago. Works perfect! Thanks

**Comment by OBS1227** [comment]
Packysauce, so sorry I didn't mean to ignore you it's just that I don't know how to reply to comments on this board. I just reread them to see if I can learn something and I saw that you had asked me a question back when I first posted. It's been a while so I have OBS 27.1.3. and the current version of Background removal for Mac. It shows up with all the parameters that can be adjusted, but it's a black screen. I am not seen with my camera.  Royshil said that I didn't install some components, but I don't know how to install them and am awaiting further instruction. Thanks!

**Comment by jkeys1989** [comment]
I have 27.1.3 and it crashes every time I try to remove background. Can someone help?

**Comment by donfmorrison** [comment]
Crashing here also as soon as I add the Background Removal filter.
* OBS 27.1.3
* Background Removal tool 0.4.0
* Mac OS Monterey 12.1

**Comment by royshil** [comment]
Can you please post the OBS logs here? (Or the relevant section of them)
You can view the logs even after the program crashed by looking in the help menu and selecting to find the location of the log files.
They are just .txt files. Look at the latest one
Thanks

**Comment by donfmorrison** [comment]
Latest log from crash - doesn't seem very helpful though?
```
15:51:32.709: CPU Name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
15:51:32.709: CPU Speed: 2800MHz
15:51:32.709: Physical Cores: 4, Logical Cores: 8
15:51:32.709: Physical Memory: 16384MB Total
15:51:32.709: OS Name: Mac OS X
15:51:32.709: OS Version: Version 12.1 (Build 21C52)
15:51:32.710: Kernel Version: 21.2.0
15:51:32.732: hotkeys-cocoa: Using layout 'com.apple.keylayout.US'
15:51:32.733: Current Date/Time: 2022-01-17, 15:51:32
15:51:32.733: Browser Hardware Acceleration: true
15:51:32.733: Portable mode: false
15:51:32.877: OBS 27.1.3 (mac)
15:51:32.877: ---------------------------------
15:51:32.878: ---------------------------------
15:51:32.878: audio settings reset:
15:51:32.878: 	samples per sec: 48000
15:51:32.878: 	speakers:        2
15:51:32.884: ---------------------------------
15:51:32.884: Initializing OpenGL...
15:51:32.958: Loading up OpenGL on adapter ATI Technologies Inc. AMD Radeon Pro 555 OpenGL Engine
15:51:32.958: OpenGL loaded successfully, version 4.1 ATI-4.7.101, shading language 4.10
15:51:33.111: ---------------------------------
15:51:33.111: video settings reset:
15:51:33.111: 	base resolution:   1920x1080
15:51:33.111: 	output resolution: 1920x1080
15:51:33.111: 	downscale filter:  Bicubic
15:51:33.111: 	fps:               30/1
15:51:33.111: 	format:            NV12
15:51:33.111: 	YUV mode:          709/Partial
15:51:33.111: NV12 texture support not available
15:51:33.111: Audio monitoring device:
15:51:33.111: 	name: Default
15:51:33.111: 	id: default
15:51:33.111: ---------------------------------
15:51:33.116: Failed to load 'en-US' text for module: 'decklink-captions.so'
15:51:33.120: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
15:51:33.139: os_dlopen(libpython3.9.dylib->libpython3.9.dylib): dlopen(libpython3.9.dylib, 0x0101): tried: '/Applications/OBS.app/Contents/MacOS/../Frameworks/libpython3.9.dylib' (no such file), '/Applications/OBS.app/Contents/MacOS/../Frameworks/libpython3.9.dylib' (no such file), '/Applications/OBS.app/Contents/MacOS/../Frameworks/libpython3.9.dylib' (no such file), '/Applications/OBS.app/Contents/MacOS/../Frameworks/libpython3.9.dylib' (no such file), 'libpython3.9.dylib' (no such file), '/usr/lib/libpython3.9.dylib' (no such file), '//libpython3.9.dylib' (no such file), '/usr/lib/libpython3.9.dylib' (no such file)
15:51:33.139: 
15:51:33.140: [Python] Could not load library: libpython3.9.dylib
15:51:33.373: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
15:51:33.374: No blackmagic support
15:51:33.379: [mac-virtualcam] version=1.3.0
15:51:33.465: [VideoToolbox encoder]: Adding VideoToolbox H264 encoders
15:51:33.496: Failed to load 'en-US' text for module: 'obs-backgroundremoval.so'
15:51:33.496: [obs-backgroundremoval] plugin loaded successfully (version 0.3.0)
15:51:33.504: [obs-browser]: Version 2.16.3
15:51:33.504: [obs-browser]: CEF Version 85.0.0-HEAD.2273+g93b66a0+chromium-85.0.4183.121
15:51:33.693: VLC found, VLC video source enabled
15:51:33.693: ---------------------------------
15:51:33.693:   Loaded Modules:
15:51:33.693:     vlc-video.so
15:51:33.693:     text-freetype2.so
15:51:33.693:     rtmp-services.so
15:51:33.693:     obs-x264.so
15:51:33.693:     obs-vst.so
15:51:33.693:     obs-transitions.so
15:51:33.693:     obs-outputs.so
15:51:33.693:     obs-filters.so
15:51:33.693:     obs-ffmpeg.so
15:51:33.693:     obs-browser.so
15:51:33.693:     obs-backgroundremoval.so
15:51:33.693:     mac-vth264.so
15:51:33.693:     mac-virtualcam.so
15:51:33.693:     mac-syphon.so
15:51:33.693:     mac-decklink.so
15:51:33.693:     mac-capture.so
15:51:33.693:     mac-avcapture.so
15:51:33.693:     image-source.so
15:51:33.693:     frontend-tools.so
15:51:33.693:     decklink-ouput-ui.so
15:51:33.693:     decklink-captions.so
15:51:33.693:     coreaudio-encoder.so
15:51:33.693: ---------------------------------
15:51:33.693: ==== Startup complete ===============================================
15:51:33.714: All scene data cleared
15:51:33.714: ------------------------------------------------
15:51:33.780: coreaudio: failed to find device uid: default, waiting for connection
15:51:33.780: coreaudio: no device found
15:51:33.780: [Loaded global audio device]: 'Desktop Audio'
15:51:33.841: coreaudio: device 'Yeti X' initialized
15:51:33.841: [Loaded global audio device]: 'Mic/Aux'
15:51:33.863: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Mic/Aux)
15:51:33.863: 
15:51:34.378: EOS T2i: Selected device 'EOS Webcam Utility'
15:51:34.381: EOS T2i: Using preset 1280x720
15:51:34.460: Ext Webcam: Selected device 'HD Web Camera'
15:51:34.460: Ext Webcam: Using preset 1280x720
15:51:34.698: HD Facetime Camera: Selected device 'FaceTime HD Camera (Built-in)'
15:51:34.698: HD Facetime Camera: Using preset 1280x720
15:51:34.783: Switched to scene 'External Webcam'
15:51:34.784: ------------------------------------------------
15:51:34.784: Loaded scenes:
15:51:34.784: - scene 'External Webcam':
15:51:34.784:     - source: 'Ext Webcam' (av_capture_input)
15:51:34.784: - scene 'External Webcam Cropped':
15:51:34.784:     - source: 'Ext Webcam' (av_capture_input)
15:51:34.784: - scene 'DSLR':
15:51:34.784:     - source: 'EOS T2i' (av_capture_input)
15:51:34.784: - scene 'Laptop Camera':
15:51:34.784:     - source: 'HD Facetime Camera' (av_capture_input)
15:51:34.784: - scene 'Laptop Camera Cropped':
15:51:34.784:     - source: 'HD Facetime Camera' (av_capture_input)
15:51:34.784: - scene 'Image/Video':
15:51:34.784:     - source: 'Browser' (browser_source)
15:51:34.784: ------------------------------------------------
15:51:43.436: [obs-backgroundremoval] Destroy scalers.
15:51:43.515: [obs-backgroundremoval] Model mediapipe.onnx input 0: name input_1:0 shape (4 dim) 1 x 96 x 160 x 3
15:51:43.516: [obs-backgroundremoval] Model mediapipe.onnx output 0: name segment:0 shape (4 dim) 1 x 96 x 160 x 2
15:51:43.517: [obs-backgroundremoval] Allocated 46080 sized float-array for input 0
15:51:43.518: [obs-backgroundremoval] Allocated 30720 sized float-array for output 0
15:51:43.518: User added filter 'Background Removal' (background_removal) to source 'Ext Webcam'
15:51:43.580: [obs-backgroundremoval] Destroy scalers.
15:51:43.580: [obs-backgroundremoval] Initialize scalers. Size 1280 x 720
```

**Comment by royshil** [comment]
Hmm. There not an explicit error there
But I suspect the "ext camera" which sounds like an external camera?
Can you try first with your internal camera? E.g. the embedded camera in your laptop
Or just in general a different camera
Because it might be an issue of the frame not coming in properly or in a way I know how to parse...

**Comment by OBS1227** [comment]
In terms of my situation I uninstalled BR because I need to use the built in "Virtual Camera" so that Zoom can recognize OBS for my lessons. Unfortunately my logs don't go farther than the day I uninstalled it. I'm not a programmer so reinstalling it takes some time in order to recreate the issue. Virtual Camera shows up, but doesn't activate when clicked on unfortunately. Until I can get some time to install it again this is all the info I could give you. Sorry! Thanks for trying to fix the issue.

**Comment by donfmorrison** [comment]
Tried my internal "HD Facetime Camera" and got the same kind of non-error. Pretty useless logs.

Is it possible I'm missing some pre-requisites or something?

**Comment by royshil** [comment]
It's not unlikely that it's because of the MacOS version you're running. Possibly the shared libraries have a mismatch. The only way to get around that will be to build the plug-in again from scratch on 12.1.
Otherwise - did you verify the files from the plug-in were installed in the right folders?
(Although if the files weren't found it would go up in the logs)
So my current bet is on the OS version.

**Comment by OBS1227** [comment]
in response to your last question as to if it's installed properly. I am not sure. I right clicked on OBS and i dragged the app to that folder that was in your instructions. I opened it up and guessed as to where each belonged as I am not a programmer. It took me many times and I finally saw everything that I should be seeing in your plugin. I could get it to work for sometimes a few minutes and sometimes until I wanted to close OBS. Many times I would make several attempts. It would automatically close and sometimes it stayed there. The Robust Video Matting always shut it down and then it starting working. I would have benefitted if their was an installer that did it all, because as you say I might have done something to make it crash!  Would it be possible for you or someone else to list the steps as to where certain elements need to be installed or dragged in? Perhaps an inaccurate installation is causing it to crash? Well if you do it for Mac OS 12. 1 I won't be able to install it for a while. I will need to get an external drive to update my OS. I use some expensive music software that requires a hefty price to upgrade to the latest OS with their software. A few years back I was doing some professional work and needed their software, but now I don't. I am afraid I will need it and can't use it due to the upgraded OS unless I get paid enough. I really should upgrade to a more current OS, but if you're getting success on 11 then why not keep it there as long as you can? Thanks so much for your willingness to help! Looking forward to updates and fixes!

**Comment by donfmorrison** [comment]
@royshil I have built from source and still getting the same behavior and error on OS 12.1 - At this point, I'll just have to be patient and wait for you to upgrade to 12.1. Thanks for putting this together and for continuing to support it.

**Comment by OBS1227** [comment]
I know that we can create multiple OBS's, but I am unclear as to if the build or foundation is the same for all. I  mean if I am on ne OBS will it contain the same plugins as the others? If I can install a separate OBS I will do that to experiment, but right now it's too risky timewise to be able to have a unreliable OBS to get it back to the reliable for my lessons. Otherwise I would. Thanks for listening and all your hard work Mr. Shilkrot!

**Comment by StoneBlazin** [comment]
@royshil just want to say thank you for your efforts on this amazing plugin.

@donfmorrison hey man i was using 0.4.0 and it was crashing pretty much instantly on startup or whenever i messed with the settings too long and so i deleted all traces of the plugin from OBS contents folder and unzipped 0.3.0 into the app instead and it has crashed a few times but nothing like before i can actually use the plugin and it seems to be streaming fine as well , im on a 2011 imac with high sierra so it should work for your newer model, sure hope so anyway best of luck.

@OBS1227 Yes you can install multiple versions of OBS and multiple versions of plugins, 0.4.0 was making my OBS(27.1.3) so i installed 26.1.2 and installed plugin version 2.4 or whatever and it was stable but it was only getting like 8 frames per second and making my stream choppy i didnt try 0.3.0 though and im curious to see how that would work but i did downgrade the plugins in my 27.1.3 to 0.3.0 and it seems to be holding up and working properly , give that a try and let me know how it goes

**Comment by royshil** [comment]
@jkeys1989  the background removal plugin is never being loaded... can't see it in the logs
Can you verify the `.so` files are in the right location in the plugins folder of OBS?

**Comment by OBS1227** [comment]
@donfmorrison, Thanks! I meant the same version of OBS. I got this idea when I tried to reinstall OBS. It would ask me if I wanted to replace or keep both. I kept both, so then they start automatically numbering and  I get the impression that it does, but not exactly. BR shows up in effects as opposed to the audio visual filter that it should be when properly installed. The error I would get is that it has no properties and was unusable.

**Comment by OBS1227** [comment]
If this is a repeat of this message I apologize. I started to compose it and I went looking for error logs and couldn't find the window again. It seems that Robust Video Matting makes it crash, but not always. If I start it several times it will start up and last for good periods of times,  Mac OS High Sierra  OBS 27.1.3.  Thanks!
[2022-01-19 16-43-57.txt](https://github.com/royshil/obs
[2022-01-19 16-43-57.txt](https://github.com/royshil/obs-backgroundremoval/files/7900926/2022-01-19.16-43-57.txt)
-backgroundremoval/files/7900906/2022-01-19.16-43-57.txt)
work for a good amount of time, but if I close OBS with it enabled it typically will crash.

**Comment by OBS1227** [comment]
One more thing that might be helpful. I installed it on OBS 27.2 Beta and first thing it crashed, so I uninstalled it the way I know how (figured out on my own.)  and BR shows up in effects with no properties. Not sure if the aforementioned info helps. My installation process. Don't know if it is correct or not. I followed this: I copied the .so file into the OBS plugin folder and the  BR plugin folder into the resources-data-OBS - plugins folder. When I uninstalled BR I just deleted both, but it still keeps that remnant of Br in the effects folder. Did I install it correctly and did I uninstall it correctly. It does work in copies of OBS, but I uninstalled it from the beta, because I need a stable OBS for what I want to do. Thanks!

**Comment by StoneBlazin** [comment]
for anyone that cannot get the plugin to work there is one workaround i know: download snap cam which lets use a green screen filter then select that as the source for any camera you add to OBS

**Comment by vxf** [comment]
@royshil I've been using this plugin in all my meetings ever since and almost forgot this thread, 0.4.0 works great! I have yet to try enabling GPU also

**Comment by OBS1227** [comment]
Well, I'm happy to report that i am enjoying this plugin. I am so glad that I stuck with it. I installed it on Mac OS Catalina on an external  drive on OBS 27.1.3. with what I have been using it for so far it works with no crashes. I am not a gamer and haven't done this with any live situations yet, but have had OBS open for long periods of time. The RVM still needs either some instruction by way of color adjustments or a software update, but it is only a little noticeable if you don't move.  However, I did install it on the latest 27.2.1. for Mac and the screen is black. I will change the color to green like it wants me to, but it doesn't show me. I do have both OBS's and am loving the one it works on. I wonder if installing StreamFX helped it in anyway, because that is when it became stable. Unless it was a coinkydink? Or, maybe a clean HD helped? Thank You Roy!

**Comment by Technetium1** [comment]
Working great for me via https://aur.archlinux.org/packages/obs-backgroundremoval

**Comment by codysechelski** [comment]
I'm Also having Stability Issues on my Mac. I will run, and I can preview the results, but after a few minutes the video will freeze and OBS crashes.

``` 
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro16,1
  Processor Name:	6-Core Intel Core i7
  Processor Speed:	2.6 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	12 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  System Firmware Version:	1731.100.130.0.0 (iBridge: 19.16.14243.0.0,0)
  OS Loader Version:	540.100.7~23
  Serial Number (system):	C02G68EYMD6R
  Hardware UUID:	61F1A9C7-FC73-51DE-ADD9-A6D8296B8661
  Provisioning UDID:	61F1A9C7-FC73-51DE-ADD9-A6D8296B8661
  Activation Lock Status:	Disabled
```

Log:
```
16:26:33.892: CPU Name: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
16:26:33.892: CPU Speed: 2600MHz
16:26:33.892: Physical Cores: 6, Logical Cores: 12
16:26:33.892: Physical Memory: 16384MB Total
16:26:33.892: OS Name: Mac OS X
16:26:33.892: OS Version: Version 12.3.1 (Build 21E258)
16:26:33.892: Kernel Version: 21.4.0
16:26:33.904: hotkeys-cocoa: Using layout 'com.apple.keylayout.US'
16:26:33.904: Current Date/Time: 2022-05-19, 16:26:33
16:26:33.904: Browser Hardware Acceleration: true
16:26:33.904: Portable mode: false
16:26:33.990: OBS 27.1.0 (mac)
16:26:33.990: ---------------------------------
16:26:33.990: ---------------------------------
16:26:33.990: audio settings reset:
16:26:33.990: 	samples per sec: 48000
16:26:33.990: 	speakers:        2
16:26:33.991: ---------------------------------
16:26:33.991: Initializing OpenGL...
16:26:34.043: Loading up OpenGL on adapter Intel Inc. Intel(R) UHD Graphics 630
16:26:34.043: OpenGL loaded successfully, version 4.1 INTEL-18.5.8, shading language 4.10
16:26:34.150: ---------------------------------
16:26:34.150: video settings reset:
16:26:34.150: 	base resolution:   1792x1120
16:26:34.150: 	output resolution: 1792x1120
16:26:34.150: 	downscale filter:  Bicubic
16:26:34.150: 	fps:               30/1
16:26:34.150: 	format:            NV12
16:26:34.150: 	YUV mode:          709/Partial
16:26:34.150: NV12 texture support not available
16:26:34.151: Audio monitoring device:
16:26:34.151: 	name: Default
16:26:34.151: 	id: default
16:26:34.151: ---------------------------------
16:26:34.153: Failed to load 'en-US' text for module: 'decklink-captions.so'
16:26:34.154: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
16:26:34.161: os_dlopen(libpython3.9.dylib->libpython3.9.dylib): dlopen(libpython3.9.dylib, 0x0101): tried: '/Applications/OBS.app/Contents/MacOS/../Frameworks/libpython3.9.dylib' (no such file), '/Applications/OBS.app/Contents/MacOS/../Frameworks/libpython3.9.dylib' (no such file), '/Applications/OBS.app/Contents/MacOS/../Frameworks/libpython3.9.dylib' (no such file), '/Applications/OBS.app/Contents/MacOS/../Frameworks/libpython3.9.dylib' (no such file), 'libpython3.9.dylib' (no such file), '/usr/lib/libpython3.9.dylib' (no such file), '//libpython3.9.dylib' (no such file)
16:26:34.161: 
16:26:34.161: [Python] Could not load library: libpython3.9.dylib
16:26:34.675: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
16:26:34.675: No blackmagic support
16:26:34.677: [mac-virtualcam] version=1.3.0
16:26:34.741: [VideoToolbox encoder]: Adding VideoToolbox H264 encoders
16:26:34.747: Failed to load 'en-US' text for module: 'obs-backgroundremoval.so'
16:26:34.747: [obs-backgroundremoval] plugin loaded successfully (version 0.3.0)
16:26:34.751: [obs-browser]: Version 2.16.2
16:26:34.751: [obs-browser]: CEF Version 85.0.0-HEAD.2273+g93b66a0+chromium-85.0.4183.121
16:26:34.785: os_dlopen(/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib->/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib): dlopen(/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib, 0x0101): tried: '/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib' (no such file)
16:26:34.785: 
16:26:34.785: Couldn't find VLC installation, VLC video source disabled
16:26:34.787: Failed to load 'en-US' text for module: 'StreamDeckPlugin.so'
16:26:34.788: ---------------------------------
16:26:34.788:   Loaded Modules:
16:26:34.788:     StreamDeckPlugin.so
16:26:34.788:     vlc-video.so
16:26:34.788:     text-freetype2.so
16:26:34.788:     rtmp-services.so
16:26:34.788:     obs-x264.so
16:26:34.788:     obs-vst.so
16:26:34.788:     obs-transitions.so
16:26:34.788:     obs-outputs.so
16:26:34.788:     obs-filters.so
16:26:34.788:     obs-ffmpeg.so
16:26:34.788:     obs-browser.so
16:26:34.788:     obs-backgroundremoval.so
16:26:34.788:     mac-vth264.so
16:26:34.788:     mac-virtualcam.so
16:26:34.788:     mac-syphon.so
16:26:34.788:     mac-decklink.so
16:26:34.788:     mac-capture.so
16:26:34.788:     mac-avcapture.so
16:26:34.788:     image-source.so
16:26:34.788:     frontend-tools.so
16:26:34.788:     decklink-ouput-ui.so
16:26:34.788:     decklink-captions.so
16:26:34.788:     coreaudio-encoder.so
16:26:34.788: ---------------------------------
16:26:34.788: ==== Startup complete ===============================================
16:26:34.805: All scene data cleared
16:26:34.805: ------------------------------------------------
16:26:34.892: coreaudio: device 'Elgato Wave:3' initialized
16:26:34.892: [Loaded global audio device]: 'Mic/Aux'
16:26:34.907: [Media Source 'hello_world']: settings:
16:26:34.907: 	input:                   /Users/codysechelski/Movies/Videos/Circuit - 27725.mp4
16:26:34.907: 	input_format:            (null)
16:26:34.907: 	speed:                   100
16:26:34.907: 	is_looping:              yes
16:26:34.907: 	is_linear_alpha:         no
16:26:34.907: 	is_hw_decoding:          no
16:26:34.907: 	is_clear_on_media_end:   yes
16:26:34.907: 	restart_on_activate:     yes
16:26:34.907: 	close_when_inactive:     no
16:26:34.963: elgoto-face-cam: Selected device 'Elgato Facecam'
16:26:34.964: elgoto-face-cam: Using preset 1280x720
16:26:35.022: [obs-backgroundremoval] Destroy scalers.
16:26:35.059: [obs-backgroundremoval] Model mediapipe.onnx input 0: name input_1:0 shape (4 dim) 1 x 96 x 160 x 3
16:26:35.059: [obs-backgroundremoval] Model mediapipe.onnx output 0: name segment:0 shape (4 dim) 1 x 96 x 160 x 2
16:26:35.060: [obs-backgroundremoval] Allocated 46080 sized float-array for input 0
16:26:35.060: [obs-backgroundremoval] Allocated 30720 sized float-array for output 0
16:26:35.065: [Media Source 'Media Source']: settings:
16:26:35.065: 	input:                   /Users/codysechelski/Videos/virtual-backgrounds/Codes - 23355.mp4
16:26:35.065: 	input_format:            (null)
16:26:35.065: 	speed:                   100
16:26:35.065: 	is_looping:              yes
16:26:35.065: 	is_linear_alpha:         no
16:26:35.065: 	is_hw_decoding:          yes
16:26:35.065: 	is_clear_on_media_end:   yes
16:26:35.065: 	restart_on_activate:     yes
16:26:35.065: 	close_when_inactive:     no
16:26:35.065: Switched to scene 'Main Cam Raw'
16:26:35.065: ------------------------------------------------
16:26:35.065: Loaded scenes:
16:26:35.065: - scene 'Main Cam Raw':
16:26:35.065:     - source: 'Media Source' (ffmpeg_source)
16:26:35.065:     - source: 'elgoto-face-cam' (av_capture_input)
16:26:35.065:         - filter: 'Background Removal' (background_removal)
16:26:35.065:         - filter: 'Chroma Key' (chroma_key_filter_v2)
16:26:35.065: - scene 'Main Cam Zoomed':
16:26:35.065:     - source: 'Main Cam Raw' (scene)
16:26:35.065: - scene 'Off Camera':
16:26:35.065:     - source: 'hello_world' (ffmpeg_source)
16:26:35.065:     - source: 'Image' (image_source)
16:26:35.065: - scene 'on-mute':
16:26:35.065:     - source: 'Main Cam Raw' (scene)
16:26:35.065:     - source: 'on-mute-image' (image_source)
16:26:35.065: ------------------------------------------------
16:26:35.522: [obs-backgroundremoval] Destroy scalers.
16:26:35.522: [obs-backgroundremoval] Initialize scalers. Size 1280 x 720
16:27:30.188: adding 106 milliseconds of audio buffering, total audio buffering is now 106 milliseconds (source: Media Source)
16:27:30.188: 
16:27:35.140: [Media Source 'Media Source']: settings:
16:27:35.140: 	input:                   /Users/codysechelski/Videos/virtual-backgrounds/Codes - 23355.mp4
16:27:35.140: 	input_format:            (null)
16:27:35.140: 	speed:                   100
16:27:35.140: 	is_looping:              yes
16:27:35.140: 	is_linear_alpha:         no
16:27:35.140: 	is_hw_decoding:          yes
16:27:35.140: 	is_clear_on_media_end:   yes
16:27:35.140: 	restart_on_activate:     yes
16:27:35.140: 	close_when_inactive:     no
16:27:36.662: ==== Virtual Camera Start ==========================================
16:27:41.950: Output 'virtualcam_output': stopping
16:27:41.950: Output 'virtualcam_output': Total frames output: 156
16:27:41.950: Output 'virtualcam_output': Total drawn frames: 152 (158 attempted)
16:27:41.950: Output 'virtualcam_output': Number of lagged frames due to rendering lag/stalls: 6 (3.8%)
16:27:41.951: ==== Virtual Camera Stop ===========================================
16:27:47.707: ==== Virtual Camera Start ==========================================
16:28:08.204: [Media Source 'Media Source']: settings:
16:28:08.204: 	input:                   /Users/codysechelski/Videos/virtual-backgrounds/Star - 55550.mp4
16:28:08.204: 	input_format:            (null)
16:28:08.204: 	speed:                   100
16:28:08.204: 	is_looping:              yes
16:28:08.204: 	is_linear_alpha:         no
16:28:08.204: 	is_hw_decoding:          yes
16:28:08.204: 	is_clear_on_media_end:   yes
16:28:08.204: 	restart_on_activate:     yes
16:28:08.204: 	close_when_inactive:     no
16:28:19.398: User switched to scene 'on-mute'
16:28:20.882: User switched to scene 'Main Cam Raw'
```

**Comment by royshil** [comment]
this was fixed in latest versions
