### ISSUE TITLE
Blur Background setting causing significant GPU usage above certain settings

### ISSUE THREAD

**Issue by Sparronator9999** [royshil/obs-backgroundremoval#271]
**Describe the bug**

When setting the `Blur background factor` setting high enough, the background blur effect will use a very significant amount of GPU resources (this is more apparent on integrated graphics).

**To Reproduce**

1. Open Task Manager and OBS Studio
2. Add a `Background Removal` filter to any source (if you haven't already).
3. Set `Blur Background Factor` to a high setting (settings as low as 6 max out my integrated graphics, while my discrete graphics can handle up to around 12 before lagging significantly)
4. Observe (in Task Manager) the High GPU usage

**Expected behavior**

The background blur does not use this much GPU time.

**Screenshots**

Before (tested using 39adf39) | After (latest release)
------------------------------|------------------------
![before](https://user-images.githubusercontent.com/86388887/233868781-14d180ff-7273-4b9c-8bff-d3edd2875589.png) | ![after](https://user-images.githubusercontent.com/86388887/233868956-521c438b-1f9b-423a-8cf2-495be5a3e9e0.png)

Background blur factor was set to 50 (before) and 12 (after). These settings give about the same amount of blur when switching versions, from my testing.

**Log and Crash Report**

[2023-04-24 07-53-54.txt](https://github.com/royshil/obs-backgroundremoval/files/11305075/2023-04-24.07-53-54.txt)

[2023-04-24 07-55-51.txt](https://github.com/royshil/obs-backgroundremoval/files/11305074/2023-04-24.07-55-51.txt)

**Desktop (please complete the following information):**

 - OS: Windows 10 (22H2)
 - Browser: N/A
 - Plugin Version: Latest (v0.5.17)
 - OBS Version: Latest (v29.0.2)

**Additional context**

Commit 39adf39 and earlier do not seem to exhibit this behaviour, which suggests that the newly-introduced GPU blending in the latest release is actually performing worse than before

**Comment by umireon** [comment]
Originally the background blur was performed on CPU but now it is performed on GPU so increasing the GPU load is expected.
Blurring is a very heavy computation, though.

**Comment by umireon** [comment]
The current blur implementation is a naïve one, and we should implement more efficient algorithm such as ones on the following article:

https://www.intel.com/content/www/us/en/developer/articles/technical/an-investigation-of-fast-real-time-gpu-based-image-blur-algorithms.html

**Comment by royshil** [comment]
we could add an option to choose GPU or CPU blur... to fit everyone's needs
for some (many) - saving the CPU cycles is more important, for others its the GPU

**Comment by royshil** [comment]
> The current blur implementation is a naïve one, and we should implement more efficient algorithm such as ones on the following article:
> 
> https://www.intel.com/content/www/us/en/developer/articles/technical/an-investigation-of-fast-real-time-gpu-based-image-blur-algorithms.html

i've read this article in the past researching efficient blur

it all comes down to kernel separability. with a "two pass" (instead of current "one pass") we can do box or even gaussian blur pretty fast...
i can implement it, but i think the 2 rendering passes may be slower than what we have now

**Comment by gretel** [comment]
> it all comes down to kernel separability. with a "two pass" (instead of current "one pass") we can do box or even gaussian blur pretty fast... i can implement it, but i think the 2 rendering passes may be slower than what we have now

thanks, curious to try.

**Comment by umireon** [comment]
@royshil I have implemented GPU Kawase blur on #276. That is blazingly fast when the size of the blur is very large.

**Comment by umireon** [comment]
@Sparronator9999 Here you are!
https://github.com/royshil/obs-backgroundremoval/suites/12449981629/artifacts/663440548
