### ISSUE TITLE
Flatpak version

### ISSUE THREAD

**Issue by nisel11** [royshil/obs-backgroundremoval#292]
As I understand flatpak version already exists, but where to download it or how to install it? if it does not already exist I will close the ticket

**Comment by umireon** [comment]
It is available on the FlatHub pull request: https://github.com/flathub/flathub/pull/4016#issuecomment-1501132720

It will be officially released soon.

**Comment by nisel11** [comment]
> It is available on the FlatHub pull request: [flathub/flathub#4016 (comment)](https://github.com/flathub/flathub/pull/4016#issuecomment-1501132720)
> 
> It will be officially released soon.

in another issue I saw a command for manually installing a flatpak version and it is also in a commented form in some file, it also does not work, is this normal or it should work? command: flatpak-builder --user --install --force-clean build-dir com.obsproject.Studio.Plugin.backgroundremoval.yaml

**Comment by umireon** [comment]
@nisel11 Can you wait for the official FlatPak release?

**Comment by umireon** [comment]
You can install this plugin via this command:

```
flatpak install com.obsproject.Studio.Plugin.BackgroundRemoval
```

**Comment by hardpenguin** [comment]
I am waiting for this as well ☺️
