### ISSUE TITLE
Installation instructions use incorrect filename for macos

### ISSUE THREAD

**Issue by aesuan** [royshil/obs-backgroundremoval#294]
**Describe the bug**

In the [Building > Mac OS](https://github.com/royshil/obs-backgroundremoval#mac-osx) section of the `readme`, the two included commands reference the build and package files `./.github/scripts/build-macosx.zsh` and `./.github/scripts/package-macosx.zsh` respectively. The actual names of the files in the repo are `./.github/scripts/build-macos.zsh` and `./.github/scripts/package-macos.zsh` (`macos` rather than `macosx`), so using the included command results in error `no such file or directory`.

**To Reproduce**

1. Clone the repo
2. `cd` into the repo in Terminal
2. Go to [Building > Mac OS](https://github.com/royshil/obs-backgroundremoval#mac-osx)
2. Copy the example command `$ ./.github/scripts/build-macosx.zsh -c Release -t macos-x86_64`
3. Paste command into Terminal

**Expected behavior**

The filenames in the repo should match the file names in the `readme` and the included command should successfully start the build process. 

**Desktop (please complete the following information):**

 - OS: Mac OSX
 - Browser: Chrome
 - Plugin Version: v0.5.18
 - OBS Version: n/a

**Comment by royshil** [comment]
fixes! many thanks
