### ISSUE TITLE
Add an "enhancement" to portrait video feature

### ISSUE THREAD

**Issue by royshil** [royshil/obs-backgroundremoval#295]
**Is your feature request related to a problem? Please describe.**

We should add a feature too enhance the video of the user in case of bad lighting etc

**Describe the solution you'd like**

A toggle user can tick to enable the enhance mode and the video will become more crisp and nicer.

**Describe alternatives you've considered**

Maybe there are other plugin that do this...

**Additional context**

In similar video chats there is such mode and I'm sure we can find free models to use...

**Comment by royshil** [comment]
@umireon What do you think?

**Comment by royshil** [comment]
AOD net (ICCV 2017) is insanely small: https://github.com/MayankSingal/PyTorch-Image-Dehazing
Like 0.002M parameters

**Comment by umireon** [comment]
Let's go but we may want to put this feature in a separate source filter.

**Comment by royshil** [comment]
I've started to work on this
Training the neural network now
So I'll put a PR soon with the initial results

**Comment by royshil** [comment]
released in latest version 0.5.19
