### ISSUE TITLE
No option to set background color

### ISSUE THREAD

**Issue by zxcv32** [royshil/obs-backgroundremoval#296]
The v0.5.18 (also tried v0.5.17 and v0.5.16) does not have the option to change the background color. 
The background color sets to #191b26.

![image](https://user-images.githubusercontent.com/18421306/235371443-cf2b314b-5331-4965-85f1-01009c080229.png)

OBS Studio - 29.0.2.1-1+b1 (linux)

**Comment by royshil** [comment]
Hi @zxcv32 

We've removed the background color options in favor of transparency

If you want a solid background just create an element with solid color and the video with transparent background on top of it

We should update all the GIFs though to reflect this

**Comment by umireon** [comment]
Can we close this issue as completed? @royshi]

**Comment by royshil** [comment]
yes i think its safe to close

**Comment by AyoCodess** [comment]
i cant get smooth edges no matter what i do without the background option.
