### ISSUE TITLE
Incomplete build description and missing dependencies

### ISSUE THREAD

**Issue by MatiMax** [royshil/obs-backgroundremoval#3]
Hi Roy,

first of all, thank you so much for delving into the merits of developing a so much anticipated and much needed plugin for the awesome OBS.

However, with regards to the build instructions I would like to be so bold as to mention several issues which I experienced during my struggle to get an error free build leaving me with frustration and finally giving up on the endeavour.

First of all, I had an issue in which Homebrew would not install correctly on the version of macOS Catalina which I’m running. However, I made it to the point that I could install the mentioned prerequisites.

Secondly, and this is actually missing in you description, `cmake` is not part of the Xcode development environment which I’m using, but has to be brewed separately. Using the Homebrew package of cmake results in a SIGILL error which I didn’t try to track down. Instead I used the CMake Mac application which I downloaded from cmake.org.

Last, but not least, using the CMake application to generate the make files I encountered another error which pinpointed me to the necessity to have the OBS source code available to build the `libobs` module. However, trying to build this module again left me with errors which I didn’t spend time to investigate further upon.

All in all the prerequisites for building your background removal module seems to require refinement and also seems to be more complex for green field build environments.

Therefore I’d like to ask you if it would be possible for you to make available a binary build of the module together with the model data in a compressed file which users could download and install more easily. I’d be happy to support you in your efforts by making a donation via your preferred platform.

Kind regards, all the best, stay safe and healthy, and greetings from Switzerland

Mati

**Comment by mctrafik** [comment]
+1 to the above.

For ease of discovery, this is the libobs error:

```
  By not providing "FindLibObs.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LibObs", but
  CMake did not find one.

  Could not find a package configuration file provided by "LibObs" with any
  of the following names:

    LibObsConfig.cmake
    libobs-config.cmake

  Add the installation prefix of "LibObs" to CMAKE_PREFIX_PATH or set
  "LibObs_DIR" to a directory containing one of the above files.  If "LibObs"
  provides a separate development package or SDK, be sure it has been
  installed.
```

I tried downloading and installing the source for obs-studio, but it doesn't like the `libobs` that's in there. :/ I'm a programmer but not a C programmer, and this is a stopping point for me, too. Too bad. Really wanted to try this out.

**Comment by royshil** [comment]
yea finding libobs was  a huge pain.

If you install OBS app you already have the binaries for libobs (e.g. `/Applications/OBS.app/Contents/Frameworks/libobs.0.dylib`)
but you don't have the headers. so you need to clone the main obs repo e.g. `git clone git@github.com:obsproject/obs-studio.git`

then you'd need to point `FindLibObs.cmake` to find the lib and headers:
```
find_path(LIBOBS_INCLUDE_DIR
	NAMES obs.h
	HINTS
		ENV obsPath${_lib_suffix}
		ENV obsPath
		${obsPath}
	PATHS
		/Users/roy_shilkrot/Downloads/obs-studio/libobs/
		/usr/include /usr/local/include /opt/local/include /sw/include
	PATH_SUFFIXES
		libobs
	)
```
and
```
	find_library(${base_name_u}_LIB
		NAMES ${_${base_name_u}_LIBRARIES} ${lib_name} lib${lib_name} ${lib_name}.0
		HINTS
			ENV obsPath${_lib_suffix}
			ENV obsPath
			${obsPath}
			${_${base_name_u}_LIBRARY_DIRS}
		PATHS
			/Applications/OBS.app/Contents/Frameworks
			/usr/lib /usr/local/lib /opt/local/lib /sw/lib
# ...
```

I'm working to streamline this...

**Comment by royshil** [comment]
I've created a release so you could download the pre-built binaries: https://github.com/royshil/obs-backgroundremoval/releases/tag/0.1-alpha

Follow the instructions on the release page.

Also added the above instructions to the `README.md`.

**Comment by mctrafik** [comment]
Thank you for the reply, Roy.

I tired the pre-built binaries. Copied them into the plugin folders. Doesn't seem to work. I get:

```
error: os_dlopen(/Applications/OBS.app/Contents/PlugIns/obs-backgroundremoval.so->/Applications/OBS.app/Contents/PlugIns/obs-backgroundremoval.so): dlopen(/Applications/OBS.app/Contents/PlugIns/obs-backgroundremoval.so, 257): Library not loaded: /usr/local/opt/onnxruntime/lib/libonnxruntime.1.7.2.dylib
  Referenced from: /Applications/OBS.app/Contents/PlugIns/obs-backgroundremoval.so
  Reason: image not found

warning: Module '/Applications/OBS.app/Contents/PlugIns/obs-backgroundremoval.so' not loaded
```

My brew installs a different version:

```
% ls /usr/local/opt/onnxruntime/lib       
libonnxruntime.1.5.3.dylib	libonnxruntime.dylib
```

So I'm guessing the pre-built version doesn't work.

**Comment by royshil** [comment]
OK. one solution is to bundle libonnxruntimeNNN.dylib with the plugin, and copy it to the same directory for it find it
another solution is to get the plugin to link against the symlinked version so it just finds any libonnxruntime.dylib and tries to use it (instead of forcing the exact one).

i'll take a look into option 2. but for now i'll just add the dylib to the release files

**Comment by troypesola** [comment]
I'm unable to build too.

I did build a local copy of OBS Studio.  I set the header and libs to point to the git repo folders.  'cmake ..' works

But then 'cmake --build ..' fails with "Could not load cache".

I removed the CMakeCache.txt file, reran 'cmake ..' and I get the same error.

**Comment by troypesola** [comment]
Looks like simply changing the build command to use current folder instead worked.

- 'cmake --build .'
- And then add a step to create the obs-backgroundremoval folder

Looks like it is working!

**Comment by royshil** [comment]
I'm going to close this issue since i re-did the build and install parts.
open another issue if you're running into problems.

thanks for the help!
