### ISSUE TITLE
# CPU threads: setting 1 behaves funny

### ISSUE THREAD

**Issue by Zahrun** [royshil/obs-backgroundremoval#301]
Between 0.5.18 and 0.5.19, I observe the `# CPU threads` option appeared
Here are my observations of CPU usage with MediaPipe depending on # CPU threads setting (inference device: CPU)
0: 51-53
1: 18-31
2: 17-18
3: 25-27
4: 34-35
5: 43-44
6: 51-53
7: 60-62
8: 68-70

I guess 0 uses as many threads as CPU cores, which in my case is 6, so that looks correct.
I don’t notice any difference in the output image, whatever the number of thread I set, which makes me think that I would want to use setting 2.
The setting of 1 CPU thread behaves funny though, it seems that there might actually be more than 1 thread, and it is the only setting in which the usage goes up and down so much.

**Comment by Zahrun** [comment]
Here are the observations of CPU usage with MediaPipe depending on # CPU threads setting (inference device: GPU - TensorRT)
0: 18-28
1: 14-29
2: 17-29
8: 17-29

So I guess in GPU mode, the `# CPU threads` option makes no difference
For my hardware, it seems that GPU mode actually does not add anything over CPU mode, there is more delay between the camera input and the filter output, and CPU usage is higher.

BTW, thank you for the active development, and for having reduced the CPU usage even more, now 17-18% in my scenario

**Comment by royshil** [comment]
@Zahrun thanks for the feedback
can you distill please the problems you'd like fixed?
just so we have a direction to work

**Comment by Zahrun** [comment]
Sure, my question is this: when inference device is CPU, why is it that `# CPU threads = 1` leads to higher CPU usage than `# CPU threads = 2`?

**Comment by royshil** [comment]
@Zahrun i actually can't say for sure.. i believe it's due to overhead in shuffling the data or cueing up the worker threads for work
with 2 threads it may be more efficient in executing parts of the graph in parallel..

**Comment by Zahrun** [comment]
Ok then, if that is the case we might want to have 2 threads as the default value.
I thought maybe it was an error in the code, and it was not really using only 1 thread.
I was hoping for even less CPU usage, but really it is totally usable now.

**Comment by umireon** [comment]
Can we close this issue as completed? @royshil

**Comment by royshil** [comment]
Sure yes. I think this is resolved
