### ISSUE TITLE
Background removal is not showing up under filters

### ISSUE THREAD

**Issue by TreeArtist** [royshil/obs-backgroundremoval#303]
I have tried multiple installation methods but I cannot get obs to see the plugin even though it is in the plugins folder in the obs app folder.

I am running KDE Neon, OBS 27.2.3 

![image](https://github.com/royshil/obs-backgroundremoval/assets/131339957/2a02fee3-5b4a-4177-86ef-c75e63a35476)
![image](https://github.com/royshil/obs-backgroundremoval/assets/131339957/8c9d244f-5338-4101-be4b-4ba48460bb61)

**Comment by umireon** [comment]
OBS 27 is not supported. Please use the latest OBS (28+)
