### ISSUE TITLE
Plugin not showing in filters

### ISSUE THREAD

**Issue by BreburdaKrystof** [royshil/obs-backgroundremoval#312]
Hello, I have downloaded the plugin but cannot find it in the filters menu. I also tried the installer, but no luck there either.
Log files said it was loaded successfully so I don't know where the problem is.

![Untitled](https://github.com/royshil/obs-backgroundremoval/assets/83399853/26ba8a86-fc87-4236-8f9d-feda69f260d9)

**Log Report**

[2023-05-26 23-09-21.txt](https://github.com/royshil/obs-backgroundremoval/files/11580009/2023-05-26.23-09-21.txt)

**Desktop**

 - OS: \[windows 10]

 - Plugin Version: \[0.5.19]
 - OBS Version: \[29.1.1]

**Comment by umireon** [comment]
You have to look in the Effect filter
