### ISSUE TITLE
Better matting capabilities of e.g. Hair and Glasses

### ISSUE THREAD

**Issue by royshil** [royshil/obs-backgroundremoval#315]
**Is your feature request related to a problem? Please describe.**

I would like to get a more accurate matting (separation between FG and BG), not just a "binary blob" of FG.
I've seen Google Meet be very good with matting e.g. hair and glasses.

**Describe the solution you'd like**

A better matting of partial foregrounds, e.g hair

**Describe alternatives you've considered**

Currently we have a "blob", which we can apply feathering to.

**Additional context**

N/A

**Comment by umireon** [comment]
Sounds great!

**Comment by royshil** [comment]
this was largely implemented by #320
