### ISSUE TITLE
We need new instruction videos

### ISSUE THREAD

**Issue by umireon** [royshil/obs-backgroundremoval#317]
**Is your feature request related to a problem? Please describe.**

Many users watch some videos describing this plugin but they are outdated and users ask questions on issues.

**Describe the solution you'd like**

We need a new video describing how to use this plugin to navigate new users.

**Describe alternatives you've considered**

Written documents are also OK but I suppose users prefer videos.

**Additional context**

My oral English is not good so I cannot create an English video but I can still create a Japanese video.

**Comment by royshil** [comment]
This is an excellent idea!

I will create a video, hopefully tonight, and then cut out some GIFs from it to use in our docs

**Comment by umireon** [comment]
Nice work!
