### ISSUE TITLE
OBS 27.0.1-2 (64 bit) frozes and chrashes when aktivating plugin in Linux Manjaro 

### ISSUE THREAD

**Issue by stepfister** [royshil/obs-backgroundremoval#32]
Specs.: 

OS: Manjaro Linux x86_64 
Kernel: 5.10.52-1-MANJARO 
CPU: Intel i5-4460 (4) @ 3.400GHz 
GPU: NVIDIA GeForce GTX 960 

Issue:

If I want to use the backgroundremoval-plugin with my logitech 930e obs frozes first and then it crashes. I never see the config dialog of this plugin. 
I installed with `Archlinux: install the package e.g. pacman -U obs-backgroundremoval*.tar.zst`

Any ideas or fixes?

**Comment by JoshuaMoe** [comment]
I think if you clone the repo and then follow the steps for Arch listed in the readme it should work

the steps are:

```
$ cd scripts
$ makepkg -s
```

**Comment by stepfister** [comment]
Thanks, it works. I can aktivate it. The results are not really good. The background is flickering and my head is always disapearing.

**Comment by JoshuaMoe** [comment]
Alright,

you need to ensure proper lighting and you could play with the settings a bit and maybe choose a different segmentation model

**Comment by stepfister** [comment]
I have two led-lights on my desk in front of me. Maybe the plugin needs more controlled light? In my Back there a windows with daylight? I will try some adjusting.

**Comment by JoshuaMoe** [comment]
Oh, the windows could cause the problem maybe try hanging something in front

**Comment by stepfister** [comment]
Yes, the windows are a problem. I closed all, made the room dark, its getting better. I have my head back. But every white or somehow reflecting surface is a problem. Even the pinguin tux with his yellow feets disturbs the body shape. It only works with SINet, MODNet does really nothing in my case. I can use a real greenscreen with my lightning. My lights shouldn't be the problem.
The plugin is very picky with the lights far from usable on a daily basis.

**Comment by Johnnyreyman** [comment]
Is there any way to enable gpu inference on linux?

**Comment by royshil** [comment]
we have new linux versions out now
