### ISSUE TITLE
Fix SINET

### ISSUE THREAD

**Issue by royshil** [royshil/obs-backgroundremoval#321]
**Describe the bug**
SINET model doesn't work properly.

**To Reproduce**
Just use the SINET model.

**Expected behavior**

A reasonable segmentation.

**Screenshots**

I can't make a screenshot since I'm on my phone. But it wasn't working for me yesterday.

**Log and Crash Report**
It doesn't crash. Just the segmentation is off.

**Desktop (please complete the following information):**

 - OS: macos
 - Plugin Version: 1.0.0
 - OBS Version: 29.1

**Additional context**

**Comment by umireon** [comment]
I got the following error

```
error: [obs-backgroundremoval] OpenCV(4.7.0) /Users/runner/work/obs-backgroundremoval/obs-backgroundremoval/plugin/build_arm64/OpenCV_Build-prefix/src/OpenCV_Build/modules/imgproc/src/contours.cpp:197: error: (-210:Unsupported format or combination of formats) [Start]FindContours supports only CV_8UC1 images when mode != CV_RETR_FLOODFILL otherwise supports CV_32SC1 images only in function 'cvStartFindContours_Impl'
```
