### ISSUE TITLE
doesn't work on macOS

### ISSUE THREAD

**Issue by ipinky77** [royshil/obs-backgroundremoval#322]
**Describe the bug**

It breaks the application if we move files into the OBS.app

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log and Crash Report**

Upload your OBS log file here (`Help`>`Log Files`>`Show Log Files`) to help us find cause of the problem.

If OBS is crashing, upload the crash report here as well (`Help`>`Crash Reports`>`Show Crash Reports`).

**Desktop (please complete the following information):**

 - OS: \[e.g. iOS\]
 - Browser: \[e.g. chrome, safari\]
 - Plugin Version: \[e.g. 0.5.1\]
 - OBS Version: \[e.g. 28.02\]

**Additional context**

**Comment by unclenoah** [comment]
I had the same issue - Mac Mini M2 Pro, Mac OS 13.4, OBS Studio 29.1.2, dl'd arm64 mac installer, install ran just fine, .plugin file is in /Users/<me>/Library/Application Support/obs-studio/plugins but did not show in filters for Video Capture Device, and did not show loading in OBS log. However, restarted OBS a few times, and magically it loaded, and showed up in the Audio/Video Filters for my Video Capture Device. Not sure if multiple restarts of the app will help @ipinky77 but it worked for me.

**Comment by ipinky77** [comment]
found the installer... thanks a lot... works like a charm!!!! greatly appreciated
