### ISSUE TITLE
Compatibility issue with the obs-studio ppa

### ISSUE THREAD

**Issue by IRoninCoder** [royshil/obs-backgroundremoval#33]
The default instructions did not work for me on ubuntu 20.04 with obs studio ppa because obs did not detect the plugin installation. Upon investigation it turns out that the obs ppa is utilizing the `/lib/obs-plugins` which is not in the `CMakeLists.txt`. So I wrote a patch for it:
```
--- CMakeLists.txt      2021-09-07 14:43:11.033428381 +0200
+++ CMakeLists-patched.txt      2021-09-07 14:44:30.217512505 +0200
@@ -239,13 +239,13 @@
        file(GLOB onnxmodels data/*.onnx)
 
        install(TARGETS ${CMAKE_PROJECT_NAME}
-               LIBRARY DESTINATION "${CMAKE_INSTALL_FULL_LIBDIR}/obs-plugins")
+               LIBRARY DESTINATION "/lib/obs-plugins")
 
        install(FILES ${locale_files}
-               DESTINATION "${CMAKE_INSTALL_FULL_DATAROOTDIR}/obs/obs-plugins/${CMAKE_PROJECT_NAME}/locale")
+               DESTINATION "/lib/obs-plugins/${CMAKE_PROJECT_NAME}/locale")
 
        install(FILES ${onnxmodels}
-               DESTINATION "${CMAKE_INSTALL_FULL_DATAROOTDIR}/obs/obs-plugins/${CMAKE_PROJECT_NAME}/")
+               DESTINATION "/lib/obs-plugins/${CMAKE_PROJECT_NAME}/")
 endif()
 # --- End of section ---

```
And now obs studio successfully display the filter, however trying to add the filter it breaks with a segfault and this is what I see in the core dump:
```
StacktraceAddressSignature: /usr/bin/obs:11:/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28+ad6b0:/usr/lib/obs-plugins/obs->
StacktraceTop:
 __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:314
 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<ch>
 filter_update(void*, obs_data*) () from /usr//lib/obs-plugins/obs-backgroundremoval.so
 filter_create(obs_data*, obs_source*) () from /usr//lib/obs-plugins/obs-backgroundremoval.so
 ?? () from /lib/libobs.so.0
```
Versions are exact match (27.0.1 atm). The core dump has a path in it which is `/usr//lib/obs-plugins` and that does not look right to me. Ideas are welcomed.

PS: The default debian sources libobs0 and obs-studio did not work either because the filter is not detected at all so I'm sure it's using some other plugins directory like the ppa does. Either case I need the 26+ (deb one is 25) of obs due to its virtual camera (that plugin is a pain to maintain manually and breaks frequently).

**Comment by tomchiverton** [comment]
The magic is `cmake .. -DLIBOBS_INCLUDE_DIR=/usr/include/obs`

**Comment by IRoninCoder** [comment]
@tomchiverton Unfortunately that did not fix it for me. It crashes after I add the filter from the list of filters on the video source. I installed it without using the above patch by just updating the flag and running the `mv`. Filter does show up in cli and in the list of filters on camera source inside obs UI.

Thinking graphic card which I do not have and rely on integrated graphics, but I thought ONNX runs on CPU anyways. Not sure what the segmentation fault is about. Did you get to actually add the filter and use it successfully?
