### ISSUE TITLE
Plugin not showing in filter list

### ISSUE THREAD

**Issue by Xario123** [royshil/obs-backgroundremoval#331]
Similar issue to SwampPig's #327

 - OS: Windows 10 64bits 21H2 build 19044.3086
 - Browser: Firefox
 - Plugin Version: 1.0.1
 - OBS Version: 29.1.2
 
 I tried with obs-backgroundremoval version 1.0.0 and OBS version 28.1.2. Does not work.
 
 
log: [2023-06-16 12-17-37.txt](https://github.com/royshil/obs-backgroundremoval/files/11769088/2023-06-16.12-17-37.txt)

**Comment by umireon** [comment]
@Xario123 Can you attach here logs?


Upload your OBS log file here (`Help`>`Log Files`>`Show Log Files`) to help us find cause of the problem.

**Comment by Xario123** [comment]
I found the solution. I saw in the log that the "obs-backgroundremoval.dll" module was loaded.

I'm using OBS in French, so I assumed the entry in the UI must be missing for that language.

I switched the application to English and "Background Removal" is now accessible.

**Comment by Xario123** [comment]
I did not understand. It works now.
