### ISSUE TITLE
How to Uninstall?

### ISSUE THREAD

**Issue by albas99** [royshil/obs-backgroundremoval#332]
The ReadME doesn't seem to have an uninstall instruction. Is there a way to uninstall the plugin? How can I do that?

**Comment by umireon** [comment]
@albas99 I appreciate your involvement in this project very much!

Can you write documentation to uninstall our plugin on your platform and open a pull request for this repository?
You can uninstall this plugin simply by removing the files you have installed.

Thanks in advance 👍

**Comment by albas99** [comment]
@umireon Sure, I'll give it a try

**Comment by royshil** [comment]
@albas99 please look for it under `/Users/<you>/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin`
In your image it looks like you're looking in the "global" OBS directory

**Comment by abbas133** [comment]
@royshil I removed from the mentioned directory still can see Background Removal filter in the application. Thoughts? 

> @albas99 please look for it under `/Users/<you>/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin` In your image it looks like you're looking in the "global" OBS directory

**Comment by umireon** [comment]
@abbas133 Do you use Intel Mac or Apple Silicon Mac?

**Comment by abbas133** [comment]
> @abbas133 Do you use Intel Mac or Apple Silicon Mac? If you are using Intel Mac, you also have to remove `/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin`.

I have Apple Silicon (M2) 2023

**Comment by umireon** [comment]
@royshil I've created a PR to add uninstalling instructions.
