### ISSUE TITLE
Ubuntu 22 Plugin not in effect list

### ISSUE THREAD

**Issue by alexander-zierhut** [royshil/obs-backgroundremoval#333]
**Describe the bug**
I simply can't find the effect in the list although the plugin seems to have been loaded. I installed using the latest release and used the .deb file.

**Expected behavior**
I expected the plugin to show up in the effect list of the video source (Webcam)

**Screenshots**
[Screencast from 18.06.2023 01:18:33.webm](https://github.com/royshil/obs-backgroundremoval/assets/26348781/4150a517-3161-4fb1-9e70-44bb263a1afd)

**Log and Crash Report**
https://obsproject.com/logs/OYY0f8lmBOhZY8ZI

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Not relevant
 - Plugin Version: obs-backgroundremoval v1.0.1
 - OBS Version: 27.2.3+dfsg1-1 (64 bit)

**Comment by royshil** [comment]
We only support OBS v28+ for this plugin
Please try to upgrade OBS and see if the plugin comes up for you

**Comment by alexander-zierhut** [comment]
Thank you! I guess the repos are a bit old on Ubuntu then.

**Comment by umireon** [comment]
#337 is related PR
