### ISSUE TITLE
Obs Background Removal for Ubuntu

### ISSUE THREAD

**Issue by ghost** [royshil/obs-backgroundremoval#34]
i like they added background removal for linux (FOR ARCHLINUX)!
i am using ubuntu plz add support for ubuntu
make it .deb file 
plz
Thanks

**Comment by unk1nd** [comment]
would like this as well

**Comment by Zahrun** [comment]
I added the package to pacstall https://github.com/pacstall/pacstall
It will work only with the obs-studio version from Ubuntu repos (no ppa, no flatpak, no snap)

**Comment by Zahrun** [comment]
My pacscript does not work with the ppa version of OBS.
Run this:
`sudo apt remove obs-studio -autoremove` to remove the ppa version
Then remove the ppa:
`sudo add-apt-repository ppa:obsproject/obs-studio -r`
Then install the obs-studio from Ubuntu repo:
`sudo apt update && sudo apt install obs-studio`

That is one step. Now the file not found issue is weird, it’s like the file download failed. Try again after the steps I mentionned?
Also I would advise to actually install the -git version: `pacstall -I obs-backgroundremoval-git` because it is more up to date and has more features. That might also actually not have the hash issue

**Comment by mperezy** [comment]
Yes, using `obs-backgroundremoval-git` on your **pacscript** seems it worked:
![image](https://user-images.githubusercontent.com/29245884/137208738-06f38e2e-5356-4c3a-8ba8-f2de871b5403.png)

But now I'm not able to open OBS following the steps you shared first in your last comment LOL. I'm only see the loading animation in the mouse cursor and nothing happens:

![OBS-issue](https://user-images.githubusercontent.com/29245884/137209672-b8432c78-068f-428a-9edc-1e3b1cdc506e.gif)

What a mess hahaha.
What do you recommend to do now ? I think burn my PC could the problem hahahaha :v

**Comment by mperezy** [comment]
@Zahrun 

I tired to run `obs-studio` from terminal and I'm getting this:

![image](https://user-images.githubusercontent.com/29245884/137210373-ee09d132-0fb1-48f8-8581-ab1f1b3dc18b.png)

**Comment by Zahrun** [comment]
Yup it seems StreamFX requires obs-studio version 27 as a minimum since version StreamFX 0.10.1
So you can use StreamFX version 0.10.0 with your current setup.
Or actually, Ubuntu 21.10 will be out tomorrow and deliver obs-studio version 27 so upgrading to ubuntu 21.10 might have obs work with StreamFX 0.10.1
Or I could try to make the pacscript work with the ppa version but I think it’s complicated

**Comment by mperezy** [comment]
For the blurred black border it's only an image with that black border and applied the blur effect from `StreamFX` with Dual Filtering type, Area subtype and size 4.

**Comment by Zahrun** [comment]
Ah you are lucky you can add two sources from the same camera. It does not work with my cheap webcam. I could use a Source Mirror from StreamFX but I can’t apply the background removal on it. Some people had the same issue https://github.com/royshil/obs-backgroundremoval/issues/26 I’ll see if that can be fixed somehow.

**Comment by mperezy** [comment]
Jeez !. For some reason the [repo](https://github.com/jschmid1/gopro_as_webcam_on_linux) that I'm using to be able to stream my Gopro in Ubuntu makes visible for many programs that use webcams, so I think that's why I can create more than one source of my gopro in OBS. Maybe you need to use **v4l2loopback** to stream your webcam, but it is probably you'll get some latency in your webcam source. Maybe if you check that repo can find a possible solution. I don't a have a webcam to make some tests, but I think **v4l2loopback** could solve your problem 🤔

**Comment by mperezy** [comment]
Looks really good !

I'm glad you could solve your webcam issue with `v4l2loopback` on `webcamoid`.

**Comment by celorodovalho** [comment]
I followed all step, but I have this error when trying to compile:

![image](https://user-images.githubusercontent.com/475722/147217427-76e35e79-f910-4cbb-8796-02773cf6cb3d.png)

**Comment by Zahrun** [comment]
In the pacscript, I use the following:
`cmake -j$(nproc) -DobsIncludePath=/usr/include/obs .. && cmake --build . -j$(nproc)
sudo cmake --install .`
Maybe try this

Otherwise, just use `pacstall -I obs-backgroundremoval-git`

**Comment by celorodovalho** [comment]
@Zahrun 
![image](https://user-images.githubusercontent.com/475722/147748583-07bb34ec-d26b-4e52-acc6-aae436d32d12.png)

**Comment by Zahrun** [comment]
What linux distribution and version of it are you using?

Can you try the pacstall installation method ? `pacstall -I obs-backgroundremoval-git`

**Comment by ZlowrogiTuru** [comment]
> What linux distribution and version of it are you using?
> 
> Can you try the pacstall installation method ? `pacstall -I obs-backgroundremoval-git`

Using pacstall to install obs-backgroundremoval removes obs-studio in a processes. Tried this mutliple times and at the end I can't launch obs anymore.

**Comment by Zahrun** [comment]
> > What linux distribution and version of it are you using?
> > Can you try the pacstall installation method ? `pacstall -I obs-backgroundremoval-git`
> 
> Using pacstall to install obs-backgroundremoval removes obs-studio in a processes. Tried this mutliple times and at the end I can't launch obs anymore.

Please refer to my previous answer https://github.com/royshil/obs-backgroundremoval/issues/34#issuecomment-942689271

**Comment by MadMartian** [comment]
You could build your own deb, but I found this was easy enough to build from source.
Even the CUDA GPU version was fairly straightforward (had to use ONNX v1.7.0, other than that pretty straightforward)

**Comment by frdsofficial** [comment]
> My pacscript does not work with the ppa version of OBS. Run this: `sudo apt remove obs-studio --auto-remove` to remove the ppa version Then remove the ppa: `sudo add-apt-repository ppa:obsproject/obs-studio -r` Then install the obs-studio from Ubuntu repo: `sudo apt update && sudo apt install obs-studio`
> 
> That is one step. Now the file not found issue is weird, it’s like the file download failed. Try again after the steps I mentionned? Also I would advise to actually install the -git version: `pacstall -I obs-backgroundremoval-git` because it is more up to date and has more features. That might also actually not have the hash issue

When I try to install `pacstall -I obs-backgroundremoval-git` I got this message: [!] ERROR: You seem to be offline . What can I do? I'm using Lubuntu 18.04.

**Comment by deymisluis** [comment]
> > My pacscript does not work with the ppa version of OBS. Run this: `sudo apt remove obs-studio --auto-remove` to remove the ppa version Then remove the ppa: `sudo add-apt-repository ppa:obsproject/obs-studio -r` Then install the obs-studio from Ubuntu repo: `sudo apt update && sudo apt install obs-studio`
> > That is one step. Now the file not found issue is weird, it’s like the file download failed. Try again after the steps I mentionned? Also I would advise to actually install the -git version: `pacstall -I obs-backgroundremoval-git` because it is more up to date and has more features. That might also actually not have the hash issue
> 
> When I try to install `pacstall -I obs-backgroundremoval-git` I got this message: `[!] ERROR: You seem to be offline`. What can I do? I'm using Lubuntu 18.04.

The same occurs in Xubuntu 20.04.

**Comment by Zahrun** [comment]
I installed Xubuntu 20.04 in a VM and installed obs-studio, pacstall, and obs-backgroundremoval-git.
It works fine.
Are you connected to the internet when you install the pacscript?
Try:
```
pacstall -U
pacstall -I obs-backgroundremoval-git
```

**Comment by Zahrun** [comment]
Actually it seems to be a pacstall bug https://github.com/pacstall/pacstall/issues/516 and https://github.com/pacstall/pacstall/issues/502
So first try the above
```
pacstall -U
pacstall -I obs-backgroundremoval-git
```
If that does not work you can do this:
```
pacstall -U pacstall develop
pacstall -I obs-backgroundremoval-git
```

**Comment by Zahrun** [comment]
> > My pacscript does not work with the ppa version of OBS. Run this: `sudo apt remove obs-studio --auto-remove` to remove the ppa version Then remove the ppa: `sudo add-apt-repository ppa:obsproject/obs-studio -r` Then install the obs-studio from Ubuntu repo: `sudo apt update && sudo apt install obs-studio`
> > That is one step. Now the file not found issue is weird, it’s like the file download failed. Try again after the steps I mentionned? Also I would advise to actually install the -git version: `pacstall -I obs-backgroundremoval-git` because it is more up to date and has more features. That might also actually not have the hash issue
> 
> When I try to install `pacstall -I obs-backgroundremoval-git` I got this message: `[!] ERROR: You seem to be offline`. What can I do? I'm using Lubuntu 18.04.

I installed Lubuntu 18.04 in a VM. For the error you mention, please see my above answer. But then you will get a OpenCV version compatibility issue 
```
Could not find a configuration file for package "OpenCV" that is compatible
  with requested version "4.2".

  The following configuration files were considered but not accepted:

    /usr/share/OpenCV/OpenCVConfig.cmake, version: 3.2.0
```
Either move to Lubuntu 20.04 or find an updated version of OpenCV somewhere. There might be other issues after this but I would recommend update to Lubuntu 20.04 anyway. Or 22.04 soon.

**Comment by carlosevi94** [comment]
I everyone, I'm on Ubuntu 20.04, im trying to install using `pacstall -I obs-backgroundremoval-git` but I get stucked here

![Fail on instalation](https://user-images.githubusercontent.com/16592166/168287208-89137994-36eb-4f77-9f58-fe98ed780847.png)

Maybe is a way to change something in pacstall script and get it run???

**Comment by misskecupbung** [comment]
@carlosevi94 Before installing the plugin, I execute these on my Ubuntu 20.04:
```
sudo apt remove obs-studio --auto-remove
sudo add-apt-repository ppa:obsproject/obs-studio -r
sudo apt update && sudo apt install obs-studio
sudo apt install -y libobs-dev libopencv-dev language-pack-en wget git build-essential cmake
```

> > > My pacscript does not work with the ppa version of OBS. Run this: `sudo apt remove obs-studio --auto-remove` to remove the ppa version Then remove the ppa: `sudo add-apt-repository ppa:obsproject/obs-studio -r` Then install the obs-studio from Ubuntu repo: `sudo apt update && sudo apt install obs-studio`
> > > That is one step. Now the file not found issue is weird, it’s like the file download failed. Try again after the steps I mentionned? Also I would advise to actually install the -git version: `pacstall -I obs-backgroundremoval-git` because it is more up to date and has more features. That might also actually not have the hash issue
> > 
> > 
> > When I try to install `pacstall -I obs-backgroundremoval-git` I got this message: `[!] ERROR: You seem to be offline`. What can I do? I'm using Lubuntu 18.04.
> 
> Same thing happens in Xubuntu 20.04.

Same with me, I installed it through the deb file and it works.

**Comment by misskecupbung** [comment]
> > My pacscript does not work with the ppa version of OBS. Run this: `sudo apt remove obs-studio --auto-remove` to remove the ppa version Then remove the ppa: `sudo add-apt-repository ppa:obsproject/obs-studio -r` Then install the obs-studio from Ubuntu repo: `sudo apt update && sudo apt install obs-studio`
> > That is one step. Now the file not found issue is weird, it’s like the file download failed. Try again after the steps I mentionned? Also I would advise to actually install the -git version: `pacstall -I obs-backgroundremoval-git` because it is more up to date and has more features. That might also actually not have the hash issue
> 
> When I try to install `pacstall -I obs-backgroundremoval-git` I got this message: `[!] ERROR: You seem to be offline`. What can I do? I'm using Lubuntu 18.04.

Same with me, I installed it through the deb file and it works.

**Comment by misskecupbung** [comment]
> I everyone, I'm on Ubuntu 20.04, im trying to install using `pacstall -I obs-backgroundremoval-git` but I get stucked here
> 
> ![Fail on instalation](https://user-images.githubusercontent.com/16592166/168287208-89137994-36eb-4f77-9f58-fe98ed780847.png)
> 
> Maybe is a way to change something in pacstall script and get it run???

I installed the dependencies first and it works on my Ubuntu 20.04
```
sudo apt remove obs-studio --auto-remove
sudo add-apt-repository ppa:obsproject/obs-studio -r
sudo apt update && sudo apt install obs-studio
sudo apt install -y libobs-dev libopencv-dev language-pack-en wget git build-essential cmake
```

**Comment by carlosevi94** [comment]
> I installed the dependencies first and it works on my Ubuntu 20.04
> 
> ```
> sudo apt remove obs-studio --auto-remove
> sudo add-apt-repository ppa:obsproject/obs-studio -r
> sudo apt update && sudo apt install obs-studio
> sudo apt install -y libobs-dev libopencv-dev language-pack-en wget git build-essential cmake
> ```

Now its works!!! Thanks! :D

**Comment by DJYeh** [comment]
I was following the instructions when I got problem with onnxruntime. I'm not familiar with pacstall. Any idea how to fix this? 

WARNING! stowing onnxruntime-1-7-0-bin would cause conflicts:
  * existing target is neither a link nor a directory: usr/local/include/cpu_provider_factory.h
  * existing target is neither a link nor a directory: usr/local/include/cuda_provider_factory.h
  * existing target is neither a link nor a directory: usr/local/include/onnxruntime_c_api.h
  * existing target is neither a link nor a directory: usr/local/include/onnxruntime_cxx_api.h
  * existing target is neither a link nor a directory: usr/local/include/onnxruntime_cxx_inline.h
  * existing target is neither a link nor a directory: usr/local/include/onnxruntime_session_options_config_keys.h
  * existing target is neither a link nor a directory: usr/local/lib/libonnxruntime.so.1.7.0
  * existing target is not owned by stow: usr/local/lib/libonnxruntime.so
All operations aborted.
[!] ERROR: Package contains links to files that exist on the system
[+] INFO: Cleaning up
[!] ERROR: Failed to install onnxruntime-1-7-0-bin

**Comment by herteljt** [comment]
> I was following the instructions when I got problem with onnxruntime. I'm not familiar with pacstall. Any idea how to fix this?
> 
> WARNING! stowing onnxruntime-1-7-0-bin would cause conflicts:
> 
> * existing target is neither a link nor a directory: usr/local/include/cpu_provider_factory.h
> * existing target is neither a link nor a directory: usr/local/include/cuda_provider_factory.h
> * existing target is neither a link nor a directory: usr/local/include/onnxruntime_c_api.h
> * existing target is neither a link nor a directory: usr/local/include/onnxruntime_cxx_api.h
> * existing target is neither a link nor a directory: usr/local/include/onnxruntime_cxx_inline.h
> * existing target is neither a link nor a directory: usr/local/include/onnxruntime_session_options_config_keys.h
> * existing target is neither a link nor a directory: usr/local/lib/libonnxruntime.so.1.7.0
> * existing target is not owned by stow: usr/local/lib/libonnxruntime.so
>   All operations aborted.
>   [!] ERROR: Package contains links to files that exist on the system
>   [+] INFO: Cleaning up
>   [!] ERROR: Failed to install onnxruntime-1-7-0-bin

I followed Zahrun's advice above and did:
`pacstall -U pacstall develop
pacstall -I obs-backgroundremoval-git`

**Comment by billksun** [comment]
> @Zahrun Another option is the NDI plugin. You can add an NDI output filter to your cam source and create several NDI sources from it that you can use to apply the blur effect and the background removal filters.

@mhcerri @Zahrun How did you get this working? I am trying to get 2 sources from the same webcam (phone cam via DroidCam OBS) that I can apply different filters to (one obs-backgroundremoval, and the other blur). I didn't get very far:

1. I added a DroidCam OBS Source, with a Dedicated NDI Output filter.
2. I then added the NDI Source, but I am unable to see my NDI output created in the previous step in the "Source name" list.

Did something go wrong?

**Comment by deymisluis** [comment]
> i like they added background removal for linux (FOR ARCHLINUX)! i am using ubuntu plz add support for ubuntu make it .deb file plz Thanks

I tried all the steps here and I was not successful, but I found a snap version with several plugins installed including OBS Background Removal, some may not even like snaps but this one ended up solving my problem and saved me time.

[https://github.com/snapcrafters/obs-studio](https://github.com/snapcrafters/obs-studio)

**Comment by MisterDerpie** [comment]
Heya folks,

tried to install the plugin via pacstall but got the error that `../LICENSE` isn't found.
There's an easy way around that, simply editing the pacstall script and change the install step 

```bash
# OLD
install() {
  sudo cmake --install . > /dev/null
  sudo install -Dm644 "../LICENSE" -t "${STOWDIR}/${name}/usr/share/licenses/${name}"
}
```

to

```bash
# NEW
install() {
  cd build/
  sudo cmake --install . > /dev/null
  sudo install -Dm644 "../LICENSE" -t "${STOWDIR}/${name}/usr/share/licenses/${name}"
}
```

**Comment by royshil** [comment]
we need to get your help in Archlinux installers again as they are broken

can you please pick up the latest `main` HEAD and see if you can come up with a fix? 🙏

**Comment by Zahrun** [comment]
> we need to get your help in Archlinux installers again as they are broken
> 
> can you please pick up the latest `main` HEAD and see if you can come up with a fix? pray

Ubuntu lunar, the upcoming release, currently packages cmake 3.25.1. I will wait for them to package 3.25.2 and then fix the pacscript.

You wrote archlinux, did you mean to post this in a different thread or did you mean ubuntu?
