### ISSUE TITLE
Unclear OpenSUSE Instructions

### ISSUE THREAD

**Issue by bonobo-d** [royshil/obs-backgroundremoval#346]
**Describe the bug**

I have built the plugin on OpenSUSE Tumbleweed following [these instructions](https://github.com/royshil/obs-backgroundremoval/blob/main/docs/BUILDING-OPENSUSE.md), yet the Background Removal filter isn't appearing in the list of possible filters.

**To Reproduce**

1. Have OBS already installed with `zypper install obs-studio`
2. Build the plugin with the OpenSUSE instructions linked above.
3. Reboot
4. Start OBS
5. Open the Filters settings
6. See that the plugin isn't there

**Expected behavior**

The plugin should be available after building it.

**Desktop (please complete the following information):**

 - OS: OpenSUSE Tumbleweed 20230621 KDE
 - Browser: Firefox
 - Plugin Version: 1.0.1
 - OBS Version: 29.1.3 (64bit)

**Additional context**

It's likely that I'm doing something wrong, as I'm not expert at this. It does look like the "plugin building" instructions are also building OBS Studio itself, so maybe that's conflicting with the pre-existing OBS installation. I don't know how to debug that. But if that's the case, it should be clarified in the instructions page.

**Comment by umireon** [comment]
@bonobo-d Can you post here the screenshot that indicates your OBS installation could not find our plugin?
And can you post here the log?

**Comment by bonobo-d** [comment]
@umireon 
Here is the screenshot:
![OBS_screenshot](https://github.com/royshil/obs-backgroundremoval/assets/66203865/585595e5-c7ee-4d7c-b26f-a603c84016b0)

And here is the latest log:
[2023-06-24 13-08-11.txt](https://github.com/royshil/obs-backgroundremoval/files/11854445/2023-06-24.13-08-11.txt)

**Comment by umireon** [comment]
#348 will fix your problem. Try the instructions again for master or you can wait for v1.0.3 is released.

**Comment by bonobo-d** [comment]
@umireon It is indeed fixed with the latest commit. Thank you!
