### ISSUE TITLE
1.0.2: Complains about missing libonnxruntime.so.1.15.1 (1.0.1 works fine) - Xubuntu 22.04 LTS

### ISSUE THREAD

**Issue by flipbit03** [royshil/obs-backgroundremoval#347]
**Describe the bug**

Plugin is not listed as available, shows failure in OBS' logs.

I am in a fresh XUbuntu 22.04 install, installed OBS via PPA, and then grabbed this library from the latest `.deb` release and installed it

**Log and Crash Report**
```
19:46:32.068: os_dlopen(/usr//lib/x86_64-linux-gnu/obs-plugins/obs-backgroundremoval.so->/usr//lib/x86_64-linux-gnu/obs-plugins/obs-backgroundremoval.so): libonnxruntime.so.1.15.1: cannot open shared object file: No such file or directory
19:46:32.068: 
19:46:32.069: os_dlopen(/usr//lib/x86_64-linux-gnu/obs-plugins/obs-backgroundremoval.so->/usr//lib/x86_64-linux-gnu/obs-plugins/obs-backgroundremoval.so): libonnxruntime.so.1.15.1: cannot open shared object file: No such file or directory
19:46:32.069: 
19:46:32.069: Module '/usr//lib/x86_64-linux-gnu/obs-plugins/obs-backgroundremoval.so' not loaded
```

**Desktop (please complete the following information):**

 - OS: XUbuntu 22.04 (Fresh Install)
 - Browser: Google Chrome 
 - Plugin Version: v1.0.2
 - OBS Version: 29.1.3

**EDIT - IMPORTANT**: Removing 1.0.2 and installing 1.0.1 worked for me! (I can use 1.0.1 just fine). 

Thanks again for this awesome plugin :heart:

**Comment by umireon** [comment]
I've confirmed this bug.

**Comment by umireon** [comment]
#348 will fix this problem
