### ISSUE TITLE
Add a real-time monocular depth estimation model

### ISSUE THREAD

**Issue by royshil** [royshil/obs-backgroundremoval#354]
Depth estimation can be used to create a background "focus" effect, instead of a binary mask like we have right now
Depth map can also create all kinds of cool 3D effects. 
Maybe we can provide a secondary video output frame of the depth map as "alpha map".

people have asked for it in the past https://ideas.obsproject.com/posts/1822/depth-map-filter
https://ideas.obsproject.com/posts/2058/advanced-filter-options

**Comment by royshil** [comment]
possible options for models:
* https://github.com/PINTO0309/PINTO_model_zoo/tree/main/158_HR-Depth
* https://github.com/PINTO0309/PINTO_model_zoo/tree/main/210_SC_Depth_pl
* https://github.com/PINTO0309/PINTO_model_zoo/tree/main/294_FSRE-Depth

i tested and they work at or close to realtime on CPU

**Comment by royshil** [comment]
ding ding din! we have a winner
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/384_TCMonoDepth

inference is 4ms on my CPU and the results are perfect!
model is ~450k file also...

**Comment by umireon** [comment]
What is license?

**Comment by umireon** [comment]
MIT License sounds suitable for us

**Comment by royshil** [comment]
i started working on this on `roy.add_depth_estimation_model`

**Comment by royshil** [comment]
now on PR #366
