### ISSUE TITLE
CMake Error:   Xcode 1.5 not supported.

### ISSUE THREAD

**Issue by mcr0cx** [royshil/obs-backgroundremoval#356]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log and Crash Report**

Upload your OBS log file here (`Help`>`Log Files`>`Show Log Files`) to help us find cause of the problem.

If OBS is crashing, upload the crash report here as well (`Help`>`Crash Reports`>`Show Crash Reports`).

**Desktop (please complete the following information):**

 - OS: \[e.g. iOS\]
 - Browser: \[e.g. chrome, safari\]
 - Plugin Version: \[e.g. 0.5.1\]
 - OBS Version: \[e.g. 28.02\]

**Additional context**

**Comment by umireon** [comment]
We're sorry but we cannot do anything without description.

**Comment by ilias-t** [comment]
I experienced this running on a beta version of Xcode on a beta OS installation. In the applications directory, renaming the application from `Xcode-beta` to just `Xcode` fixed this issue for me.

**Comment by ilias-t** [comment]
For some reason I also needed to set `USE_SYSTEM_CURL` to `true` as a cache variable in the `macos` config of `CMakePresets.json`

**Comment by 100terres** [comment]
Thank you @ilias-t for the tip.

I was getting the following error when running `./.github/scripts/build-macos -c Release`:

```
-- Install OBS sources (universal) - done
CMake Error at cmake/BuildMyCurl.cmake:15 (add_subdirectory):
  The source directory

    /REDACTED/obs-backgroundremoval/vendor/curl

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:80 (include)


CMake Error at cmake/BuildMyCurl.cmake:17 (target_compile_options):
  Cannot specify compile options for target "libcurl" which is not built by
  this project.
Call Stack (most recent call first):
  CMakeLists.txt:80 (include)
```

I was able to fix it by adding `USE_SYSTEM_CURL: true` here: https://github.com/royshil/obs-backgroundremoval/blob/f38e2fd980545bc27fbeb97578d25268fcb28bf2/CMakePresets.json#L21-L28

**Comment by umireon** [comment]
It seems that you didn't run `git submodule update --init`. This is not related to Xcode-beta.
