### ISSUE TITLE
Audio issue while filter is active

### ISSUE THREAD

**Issue by thesleepingjay** [royshil/obs-backgroundremoval#358]
I get audio issues when both the removal and enhancement filters are visible.
I get audio hitching on my main audio output when listening to my razer nommo usb speakers, but not when i listen through my fiio btr3k. It doesnt seem to show up on the recording, but its really distracting. it is noticeable because i listen to youtube while i stream. i have a 5800x3d, 4080, windows 10 22h3 19045.3086, nvidia driver 536.40.

**Comment by royshil** [comment]
Thanks for the issue @thesleepingjay 
can you maybe provide a short audio (or video with audio) recording so we know what you hear?
are you able to capture it somehow?

**Comment by thesleepingjay** [comment]
Yeah, give me a few hours and I'll send you a video

**Comment by thesleepingjay** [comment]
Hi Roy,

Here's a video showing whats going on. Thanks for responding and working on
this for free.

Thanks,
Caleb

**Comment by royshil** [comment]
@thesleepingjay we didn't get the video. do you want to upload it to google drive etc.?

**Comment by thesleepingjay** [comment]
Try this
 20230630_152534.mp4
<https://drive.google.com/file/d/1B2WQjcM0QKdLR9gNVnyqwjZ9OCcRwdSE/view?usp=drive_web>

**Comment by royshil** [comment]
Thanks! for the video
I appreciate the detailed information 

Hmm. This is very strange
Our b/g removal plugin doesn't affect audio at all, we don't process it in the plugin.  Any audio should pass through, we never change or touch it.
We also don't affect any video source on which the plugin is not enabled, and it looks like the filter is only on the camera video. 

So my thinking around potential problems is:
- your computer is working hard on the b/g removal processing and consuming CPU. Can you check the FPS and the CPU utilization in OBS? (bottom right corner) when the plugin is ON and the OFF to see the difference
- it's very very strange you're only getting this audio problem on the spekaers and not headphones. so maybe this is a GPU problem? or some kind of processing the speakers are doing on your computer (driver) that clash with the plugin's process. maybe you can check the drivers for your speakers? like if they need an update or something.
- you mentioned this happens with BOTH b/g removal and Enhance are enabled - did you   do a "A/B" test with enabling one and disabling the other, and then both enabled to see which configuration is doing the audio problem?

**Comment by umireon** [comment]
@royshil Can I close this issue because we haven't heard from the author for a long time?

**Comment by thesleepingjay** [comment]
Yeah, sorry about that. I forgot to reply, but I found a workaround. Thanks
for responding.

**Comment by umireon** [comment]
@thesleepingjay Can you share the workaround with us in case another hit a similar problem?

**Comment by thesleepingjay** [comment]
I say workaround, but ive just been using my DAC and Headphones, which
don't have the same issue as my usb speakers. I tried updating all the
things i could think of, but it didnt make a difference, tho I havent been
able to try it out again for a while.

**Comment by umireon** [comment]
@thesleepingjay Thank you for sharing the information!
