### ISSUE TITLE
macOS signing is broken with the new build system

### ISSUE THREAD

**Issue by umireon** [royshil/obs-backgroundremoval#361]
It seems some variables are missing.
https://github.com/royshil/obs-backgroundremoval/actions/runs/5423915612/jobs/9862535981

**Comment by umireon** [comment]
@royshil Can you reconfigure the signing secrets according to [Developer ID Application: Kaito Udagawa (4HMJS6J4MZ)](https://github.com/obsproject/obs-plugintemplate#github-actions-set-up)?

**Comment by royshil** [comment]
this is strange because i have it set up properly... i'll have to re-do this probably
i can get to it later this evening

**Comment by umireon** [comment]
Mac signing works properly under my setup
https://github.com/umireon/obs-backgroundremoval/actions/runs/5427900959/jobs/9871582712#step:6:887

**Comment by umireon** [comment]
I doubt that MACOS_SIGNING_CERT does not contain the correct certs and keys.
My MACOS_SIGNING_APPLICATION_IDENTITY is `Developer ID Application: Kaito Udagawa (VDC7PGE9X3)`
My MACOS_SIGNING_INSTALLER_IDENTITY is `Developer ID Installer: Kaito Udagawa (4HMJS6J4MZ)`
My MACOS_SIGNING_CERT includes two certs and two keys.
<img width="354" alt="スクリーンショット 2023-07-03 22 17 54" src="https://github.com/royshil/obs-backgroundremoval/assets/1067855/904a2c91-fc98-4550-b369-35f6047f46ef">

**Comment by royshil** [comment]
OK i re did it and now the signing is working again. thanks for the help!
