### ISSUE TITLE
Installed But Not Showing

### ISSUE THREAD

**Issue by DrewskiesAU** [royshil/obs-backgroundremoval#37]
Hi Team,
I have followed instruction to install plugin but when open OBS it is not listed in the filter
![Capture](https://user-images.githubusercontent.com/91114124/134122411-0a98e8fe-c581-4a9e-81de-2d8c4632b616.PNG)
s

**Comment by bfack95** [comment]
Having the same issue. Hoping someone can address this.

**Comment by geneangela** [comment]
I am also having the same issue.

**Comment by DrewskiesAU** [comment]
Is there any updates on this by any chance?

**Comment by rygvko** [comment]
Yes i have the same issue....pls fix this...

**Comment by ryanpeiris** [comment]
Hi, Guys,

Make sure you are checking the filter under audio/video not in effect filters. I made that mistake.

![tempsnip](https://user-images.githubusercontent.com/22732023/135336731-d8187a40-d03f-42f8-8846-3290c93456b1.png)

**Comment by xelantro** [comment]
Well for me it's just not there :/ and as seen in the screenshot it seems like he's also in the Audio-/Videofilters list.
On Windows, extracted the arcive, copied it all over (everything seems to be there - like `obs-backgroundremoval.dll in \obs-plugins\64bit\` and so on)

**Comment by DrewskiesAU** [comment]
Hi Ryan,
As per my screenshot on original message, I can confirm I am looking under Audio/video filters

**Comment by rygvko** [comment]
Is Roy the developer is not say something about this???? helow Roy.....

**Comment by hvisage** [comment]
If you are on macOS and having this problem, you are probably on a Case Sensitive filesystem and the .so file got put in `Plugins` instead of `PlugIns` and you'll notice the 2x directories in a `ls -l` output like this:
```
⇒  ls -alrt
total 8
drwxr-xr-x@  3 hvisage  staff    96 Sep 28 12:05 ..
drwxr-xr-x@  6 hvisage  admin   192 Sep 28 12:05 Resources
-rw-r--r--@  1 hvisage  staff  1226 Sep 28 12:05 Info.plist
drwxr-xr-x@  3 hvisage  staff    96 Sep 28 12:06 _CodeSignature
drwxr-xr-x@  8 hvisage  staff   256 Sep 28 12:06 MacOS
drwxr-xr-x@ 38 hvisage  staff  1216 Oct  1 08:09 Frameworks
drwxr-xr-x@  9 hvisage  staff   288 Oct  2 16:37 .
drwxr-xr-x   3 hvisage  admin    96 Oct  2 16:58 Plugins
drwxr-xr-x@ 30 hvisage  admin   960 Oct  2 16:58 PlugIns
```

Solution, mv/copy the `obs-backgroundremoval.so` to the `PlugIns` directory and it will pop up :)

(At least me it did after a build it when I was trying to find a solution)

```
PlugIns:
bearer                   iconengines              mac-decklink.so          obs-browser.so           obs-vst.so               styles
coreaudio-encoder.so     image-source.so          mac-syphon.so            obs-ffmpeg.so            obs-x264.so              text-freetype2.so
decklink-captions.so     imageformats             mac-virtualcam.so        obs-filters.so           platforms                vlc-video.so
decklink-ouput-ui.so     mac-avcapture.so         mac-vth264.so            obs-outputs.so           printsupport
frontend-tools.so        mac-capture.so           obs-backgroundremoval.so obs-transitions.so       rtmp-services.so

Plugins:
obs-backgroundremoval.so
```

**Comment by rygvko** [comment]
> 
> 
> If you are on macOS and having this problem, you are probably on a Case Sensitive filesystem and the .so file got put in `Plugins` instead of `PlugIns` directory and you'll notice the 2x directories in a `ls -l` output like this:
> 
> ```
> /Applications/OBS.app/Contents|
> ⇒  ls -alrt
> total 8
> drwxr-xr-x@  3 hvisage  staff    96 Sep 28 12:05 ..
> drwxr-xr-x@  6 hvisage  admin   192 Sep 28 12:05 Resources
> -rw-r--r--@  1 hvisage  staff  1226 Sep 28 12:05 Info.plist
> drwxr-xr-x@  3 hvisage  staff    96 Sep 28 12:06 _CodeSignature
> drwxr-xr-x@  8 hvisage  staff   256 Sep 28 12:06 MacOS
> drwxr-xr-x@ 38 hvisage  staff  1216 Oct  1 08:09 Frameworks
> drwxr-xr-x@  9 hvisage  staff   288 Oct  2 16:37 .
> drwxr-xr-x   3 hvisage  admin    96 Oct  2 16:58 Plugins
> drwxr-xr-x@ 30 hvisage  admin   960 Oct  2 16:58 PlugIns
> ```
> 
> Solution, mv/copy the `obs-backgroundremoval.so` to the `PlugIns` directory and it will pop up :)
> 
> (At least me it did after a build it when I was trying to find a solution)
> 
> ```
> PlugIns:
> bearer                   iconengines              mac-decklink.so          obs-browser.so           obs-vst.so               styles
> coreaudio-encoder.so     image-source.so          mac-syphon.so            obs-ffmpeg.so            obs-x264.so              text-freetype2.so
> decklink-captions.so     imageformats             mac-virtualcam.so        obs-filters.so           platforms                vlc-video.so
> decklink-ouput-ui.so     mac-avcapture.so         mac-vth264.so            obs-outputs.so           printsupport
> frontend-tools.so        mac-capture.so           obs-backgroundremoval.so obs-transitions.so       rtmp-services.so
> 
> Plugins:
> obs-backgroundremoval.so
> ```

If Windows???

**Comment by DrewskiesAU** [comment]
I am on windows

**Comment by rygvko** [comment]
what kind of windows do you have? @DrewskiesAU

**Comment by hvisage** [comment]
> If Windows???

I'd say follow the same logic to check... it'll definitely be a similar problem on Linux.

I don't do M$-Windows - too much issues for me professionally, so can't comment on Windows

**Comment by DrewskiesAU** [comment]
Hi @rygvko i am running windows 10

**Comment by Localzen** [comment]
FOUND THE SOLUTION!!! I was having the same issue, installed but couldnt see it. I updated my OBS and the background removal tool showed up where it was supposed to. To update OBS, navigate (within OBS) to "help" -> "check for updates". 
@MatiMax @rygvko

**Comment by rygvko** [comment]
@Localzen Nope it doesnt works......my obs is 27.1.1 64bit still not showing up....

**Comment by Localzen** [comment]
@rygvko for real?? damnn... did you extract the zip directly into your OBS folder?

**Comment by rygvko** [comment]
@Localzen Yes I did....C:\Program Files\obs-studio\data\obs-plugins\obs-backgroundremoval And C:\Program Files\obs-studio\obs-plugins\64bit

**Comment by DrewskiesAU** [comment]
Confirming my OBS is the current version and extract directly to the location

**Comment by rygvko** [comment]
I think its a bug in the plugin causing that....the developer must fix it....

**Comment by kontroll** [comment]
I can see the filter, on Linux, under the list of Audio/Video filters. My problem is that I use my phone as a cam, and it uses a browser source. For that reason I can't apply the filter anyway.

**Comment by rygvko** [comment]
@kontroll Yes you can add Audio/Video Filters. Open you Phone cam using media not browser source. Then you can Uncheck the Local file, then in the input enter the link for accessing your phone camera...

**Comment by DrewskiesAU** [comment]
Still not working, has there been any updates to fix as of yet?

**Comment by rygvko** [comment]
i guess it never gonna fix....cause the developer dont care about it.....its just few computer that not able to used it....just uninstall 
and find another way....forget this suck plugin....

**Comment by royshil** [comment]
> i guess it never gonna fix....cause the developer dont care about it.....its just few computer that not able to used it....just uninstall and find another way....forget this suck plugin....

Hi @rygvko . Thank you for your comment! I'm working in 3 jobs and I've very very little time, but I do my best (!) to give you all a completely free plugin and open source. I work at night and on the weekends, because I think it's a good thing for the OBS users to have for free.
If you're not satisfied with the plugin - help us improve it! check out the code and fix some problems..
Thanks again

**Comment by rygvko** [comment]
> 
> 
> > i guess it never gonna fix....cause the developer dont care about it.....its just few computer that not able to used it....just uninstall and find another way....forget this suck plugin....
> 
> Hi @rygvko . Thank you for your comment! I'm working in 3 jobs and I've very very little time, but I do my best (!) to give you all a completely free plugin and open source. I work at night and on the weekends, because I think it's a good thing for the OBS users to have for free. If you're not satisfied with the plugin - help us improve it! check out the code and fix some problems.. Thanks again

yes at last you give concern about this really appreciate....

**Comment by royshil** [comment]
Please try https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.4.0
@rygvko @DrewskiesAU @chukwumaokere @kontroll @Localzen @hvisage

**Comment by DrewskiesAU** [comment]
Thank you for the time and effort you put into this @royshil 

I have just tried the new file and it still doesnt show up for me

**Comment by rygvko** [comment]
> 
> 
> Please try https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.4.0 @rygvko @DrewskiesAU @chukwumaokere @kontroll @Localzen @hvisage

Still not showing up...same as @DrewskiesAU....running on 27.1.3 (64bit)

**Comment by Inventatorul1** [comment]
Same problem

**Comment by KeysiJones** [comment]
I found a solution... 

Step 1: Uninstall OBS by running sudo apt remove obs-studio
Step 2: Add OBS official repository by running  sudo add-apt-repository ppa:obsproject/obs-studio
Step 3: Update packages running sudo apt update
Step 4: Install OBS studio by running sudo apt install obs-studio
Step 5: Clone the repository in the folder you want it to be cloned and then run bellow commands

git clone https://github.com/royshil/obs-backgroundremoval.git
cd obs-backgroundremoval
mkdir build && cd build
cmake .. && cmake --build . && cmake --install .

Setp 6: move plugin files to obs plugins folder running the commands below...

sudo mv /usr/local/lib/obs-plugins/obs-backgroundremoval.so /usr/lib/obs-plugins/
sudo mv /usr/local/share/obs/obs-plugins/obs-backgroundremoval /usr/share/obs/obs-plugins/

It worked for me... hope it helps you guys too.

Let's help each other !!

**Comment by Inventatorul1** [comment]
I found a fix for windows: after you extract de zip manually place the files in obs directories.
obs-backgroundremoval-0.4.0-win64\data\obs-plugins ----> C:\Program Files\obs-studio\data\obs-plugins
obs-backgroundremoval-0.4.0-win64\obs-plugins\64bit ----> C:\Program Files\obs-studio\obs-plugins\64bit

**Comment by rygvko** [comment]
> 
> 
> I found a fix for windows: after you extract de zip manually place the files in obs directories. obs-backgroundremoval-0.4.0-win64\data\obs-plugins ----> C:\Program Files\obs-studio\data\obs-plugins obs-backgroundremoval-0.4.0-win64\obs-plugins\64bit ----> C:\Program Files\obs-studio\obs-plugins\64bit

Thats not a solution....its the same as standart procedure for installing pluggin for OBS....and defenetely NOT WORKING....

**Comment by adminjw** [comment]
> > I found a fix for windows: after you extract de zip manually place the files in obs directories. obs-backgroundremoval-0.4.0-win64\data\obs-plugins ----> C:\Program Files\obs-studio\data\obs-plugins obs-backgroundremoval-0.4.0-win64\obs-plugins\64bit ----> C:\Program Files\obs-studio\obs-plugins\64bit
> 
> Thats not a solution....its the same as standart procedure for installing pluggin for OBS....and defenetely NOT WORKING....

Well, actually - it was the solution for me. For what ever reason when I copy-paste the files directly from the zip to the obs-studio folder, the UI makes me believe that the files have been copied (admin prompt, progress bar, etc..). Afterwards I run into the mentioned issue.

Thanks to @Inventatorul1 I checked for the individual files in the sub-folders and to my surprise, there was nothing to be found. So as recommended, I first extracted the files and only than copied them over. This time the files are in the right location and voilà - the plugin works now.

**Comment by DrewskiesAU** [comment]
I still cant get this to work. I have decided to not worry about this one now.

Thank you everyone for trying :)

**Comment by Wolfyxon** [comment]
I tried everything, still filter isn't showing

**Comment by Artyrm** [comment]
I looked into the log file, and it says:
`23:13:41.510: Skipping module '../../obs-plugins/64bit/DirectML.dll', not an OBS plugin
23:13:41.512: LoadLibrary failed for '../../obs-plugins/64bit/DirectML.dll': The specified module could not be found.
23:13:41.512:  (126)
23:13:41.512: Module '../../obs-plugins/64bit/**DirectML.dll**' not loaded
23:13:41.584: [AMF] Unable to load 'amfrt64.dll', error code 126.
23:13:41.607: [AMF] AMF Test failed due to one or more errors.
23:13:41.607: Failed to initialize module 'enc-amf.dll'
23:13:41.615: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin
23:13:41.626: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin
23:13:41.627: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin
23:13:41.636: LoadLibrary failed for '../../obs-plugins/64bit/**obs-backgroundremoval.dll**': The specified module could not be found.
23:13:41.636:  (126)
23:13:41.636: Module '../../obs-plugins/64bit/obs-backgroundremoval.dll' not loaded
23:13:41.637: [obs-browser]: Version 2.16.3
23:13:41.637: [obs-browser]: CEF Version 75.1.16+g16a67c4+chromium-75.0.3770.100
23:13:41.646: [noise suppress]: NVIDIA RTX denoiser disabled, redistributable not found
23:13:41.728: Skipping module '../../obs-plugins/64bit/**onnxruntime.dll**', not an OBS plugin
23:13:41.730: LoadLibrary failed for '../../obs-plugins/64bit/onnxruntime.dll': The specified module could not be found.
23:13:41.730:  (126)
23:13:41.730: Module '../../obs-plugins/64bit/onnxruntime.dll' not loaded`

I highlighted the files that are used by this plugin. Somehow OBS doesn't count them for plugin...

**Comment by Artyrm** [comment]
Dependecy Walker shows several missing libraries:
![image](https://user-images.githubusercontent.com/21180686/148659545-2160aaa6-2433-4c99-afa1-0e007158ef72.png)

Most notably, d2d12.dll - that means no chance for me to get it running on my laptop, since it is Win7.

obs-backround remover requires some more dlls:
![image](https://user-images.githubusercontent.com/21180686/148659658-8ba169da-f700-49fa-892e-146118683006.png)

**Comment by lluio** [comment]
@KeysiJones jones solution worked for me on Ubuntu 21.04 :)

**Comment by KeysiJones** [comment]
> 

I'm very happy that it worked for you @lluio  !!! have a nice day !!

**Comment by royshil** [comment]
this shuold be resolved now

**Comment by ngreyes** [comment]
The issue may be your screen resolution, I had the same problem.  Shrink down the OBS window for the Audio/Video filters and then move the window upwards, you will notice a second set of adding filters button. The top set is for Audio/Video and the second bottom set is for effects, that's where you will find the Background remover.

**Comment by amitjoc** [comment]
### **NOTE: Let me know any further information needed**  

**Windows 10 Fully updated**  

<img width="459" height="289" alt="Image" src="https://github.com/user-attachments/assets/dd3342c7-5aa9-4ca9-ba51-aab583ac88b6" />

**OBS 28 and 31 and 32 check with all version**  

**In OBS 32 following popup is showing**   
<img width="353" height="233" alt="Image" src="https://github.com/user-attachments/assets/f460e79b-bf20-4ed4-aad8-fbd9ed31d4d0" />

**and for All version same error shown in Logs**  

<img width="810" height="560" alt="Image" src="https://github.com/user-attachments/assets/fa8d3ce7-dadb-4497-81b0-68e5dd7e8886" />
