### ISSUE TITLE
Update AUR packages

### ISSUE THREAD

**Issue by umireon** [royshil/obs-backgroundremoval#376]
We released v1 so we need to update AUR definition.

The current maintainer of AUR is @ngoonee so we have to contact them.

https://aur.archlinux.org/packages/obs-backgroundremoval
https://aur.archlinux.org/packages/obs-backgroundremoval-git

**Comment by ngoonee** [comment]
I'm on it.

**Comment by umireon** [comment]
What is 12.2? And please please post the log here to let me onvestigate the problem

**Comment by ngoonee** [comment]
> What is 12.2? And please please post the log here to let me investigate the problem

Sorry, did not mention, its the Cuda version

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find CUDA: Found unsuitable version "12.2", but required is exact
  version "12.1" (found /opt/cuda)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:598 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindCUDA.cmake:1268 (find_package_handle_standard_args)
  /usr/lib/cmake/opencv4/OpenCVConfig.cmake:86 (find_package)
  /usr/lib/cmake/opencv4/OpenCVConfig.cmake:108 (find_host_package)
  CMakeLists.txt:60 (find_package)

**Comment by umireon** [comment]
It seems that building of ONNX Runtime failed.
Can you make PKGBUILD depend on AUR ONNX Runtime?
You can use -DUSE_SYSTEM_ONNXRUNTIME=ON to load the system ONNX Runtime.

**Comment by umireon** [comment]
I tried to reproduce this problem and hit another problem. This problem is related to libcurl and would be fixed in #377.

**Comment by umireon** [comment]
@ngoonee Can you update obs-backgroundremoval-git as follows?

```
# Maintainer: Ng Oon-Ee <n g o o n e e dot t a l k @ gmail dot com>
# Based on obs-backgroundremoval PKGBUILD by PedroHLC <root@pedrohlc.com>
pkgname=obs-backgroundremoval-git
pkgver=1.1.0.r2.aeab837
pkgrel=1
pkgdesc="Background removal plugin for OBS studio"
arch=(x86_64)
url='https://github.com/royshil/obs-backgroundremoval'
license=('GPL2')
depends=('obs-studio' 'opencv' 'curl')
makedepends=('git' 'cmake')
conflicts=("obs-backgroundremoval")
source=('git+https://github.com/royshil/obs-backgroundremoval.git')
sha256sums=('SKIP')

pkgver() {
	cd "$srcdir/${pkgname%-git}"
	printf "%s" "$(git describe --tags --long | sed 's/\([^-]*-\)g/r\1/;s/-/./g')"
}

build() {
  cd "$srcdir/${pkgname%-git}"
  cmake -B build --preset linux-x86_64 -DLINUX_PORTABLE=OFF -DUSE_SYSTEM_OPENCV=ON -DUSE_SYSTEM_CURL=ON
  cmake --build build
}

package() {
  cd "$srcdir/${pkgname%-git}"
  cmake --install build --prefix "$pkgdir/usr"
}

```

**Comment by ngoonee** [comment]
Done. I still cannot build on my personal machine due to it being on [testing] with CUDA version 12.2, but everything looks fine. Will update obs-backgroundremoval as well.

**Comment by umireon** [comment]
I'm not sure but that CUDA error seems to be a packaging error on Arch Linux.

**Comment by umireon** [comment]
Can you wait for 1.1.1 before updating obs-backgroundremoval? 1.1.1 will include a change that is needed to buils on Arch Linux.

**Comment by ngoonee** [comment]
I have updated. Should be fine for non-[testing] users, and [testing] users will know to hold off anyway (or at least be able to find this convo).

**Comment by umireon** [comment]
Thanks!
