### ISSUE TITLE
Feed the game I'm playing into the screen

### ISSUE THREAD

**Issue by dbhol** [royshil/obs-backgroundremoval#378]
I've just set up this green screen on my OBS but i was wondering if it is possible to feed to game i am playing into the green screen like some people do. So it's a seamless link over the whole screen instead of a different background where i am
Thanks

**Comment by umireon** [comment]
Can you provide an example image?

**Comment by dbhol** [comment]
I have managed to resolve this now.
I found i was using an old version of the plugin as well which might not have helped, as i was linked to it from a different website. I just applied the filter to my camera and it worked without needing to do anything
