### ISSUE TITLE
The 1.1.0 deb does not install the library into /usr but /usr/local

### ISSUE THREAD

**Issue by Frozen-byte** [royshil/obs-backgroundremoval#379]
**Describe the bug**
The Plugin does not show up in the Filter.

**To Reproduce**

Start OBS and try to add the effect Filter to a V4L2 Source

**Expected behavior**
Background should show up 

**Log and Crash Report**
[2023-07-11 02-59-20.txt](https://github.com/royshil/obs-backgroundremoval/files/12009670/2023-07-11.02-59-20.txt)

**Desktop (please complete the following information):**
Kubuntu 23.04  
OBS Studio - 29.1.3 (from PPA ppa:obsproject/obs-studio)  
obs-backgroundremoval 1.1.0 (`releases/download/1.1.0/obs-backgroundremoval-1.1.0-x86_64-linux-gnu.deb`)  

**Additional context**
Worked on v1.0.3 and obs v29.0.1 but neither work, after updating OBS to 29.1.3

**Comment by umireon** [comment]
I confirmed that this is a bug of the build process.

**Comment by Frozen-byte** [comment]
According to your title change, I should be fine moving the files to a correct folder? Do you have a hint for the proper path? In the [docs](https://obsproject.com/kb/plugins-guide) I only find the `~/.config/obs-studio/plugins` path, which did not work for me.
 

<br class="Apple-interchange-newline">

**Comment by umireon** [comment]
This will fix the problem https://github.com/royshil/obs-backgroundremoval/pull/381

**Comment by umireon** [comment]
You can workaround this problem by the following commands:

```
sudo cp -r /usr/local/share/obs/obs-plugins/obs-backgroundremoval /usr/share/obs/obs-plugins/
sudo cp -r /usr/local/lib/obs-plugins/obs-backgroundremoval /usr/lib/x86_64-linux-gnu/obs-plugins/
```

**Comment by royshil** [comment]
@Frozen-byte can you test the latest installer to see the files go into the right place?

**Comment by umireon** [comment]
This is not yet fixed due to #384

**Comment by royshil** [comment]
can we verify and close now?

**Comment by Frozen-byte** [comment]
lgtm!
