### ISSUE TITLE
Is it possible to create a new release?

### ISSUE THREAD

**Issue by louie-github** [royshil/obs-backgroundremoval#38]
Hi! It looks like in between the latest [v0.3.0-beta](https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.3.0-beta) release and the latest commit, there have been a few features added, most importantly:

- Processing mask every X frames of video (8d64b35644344cda7e942aaa9e63ed54ba23b872)
- Using CUDA (0f101de11f16ccd9e6c70e6318e0210a0c796bdf)

I think these features, especially the first one, are rather useful, and so, is it possible to request a new release be made along with some build artifacts, since most people might find it difficult to manually compile?

In the future, maybe we could automate this with GitHub Actions.

Thank you!

**Comment by royshil** [comment]
i'm going to release again within a couple days
just going to upgrade to v27.1.3 and add the alpha channel

**Comment by royshil** [comment]
Please try https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.4.0
@louie-github

**Comment by louie-github** [comment]
Thank you!
