### ISSUE TITLE
Provide the zip for a portable OBS installation on Windows

### ISSUE THREAD

**Issue by iNgeon** [royshil/obs-backgroundremoval#389]
If i my ask why is there no version of the windows zip file.
Some of us use OBS portable and would like to still extract it into those versions.

https://obsproject.com/forum/resources/obs-and-obs-studio-portable-mode-on-windows.359/

https://portableapps.com/apps/music_video/obs-studio-portable

**Comment by umireon** [comment]
@iNgeon Here is the zip archive of 1.1.2.
https://github.com/royshil/obs-backgroundremoval/suites/14319111345/artifacts/805678926

I have just created #390 to include a zip archive on releases.
https://github.com/royshil/obs-backgroundremoval/pull/390
Starting from 1.1.3, a release will include a zip archive for portable installations of OBS on Windows.

**Comment by iNgeon** [comment]
Thank you
