### ISSUE TITLE
Windows X64 portable releases

### ISSUE THREAD

**Issue by Spafbi** [royshil/obs-backgroundremoval#391]
I maintain an OBS plugins updater for a small group of charity streamers. The nature of the updater requires that plugins be in a portable `zip` format. It would help us out considerably if your releases once again included the Win64 portable releases.

Thanks!

**Comment by umireon** [comment]
Is #390 what you want? And #390 is already merged and will be released for the next release.

**Comment by Spafbi** [comment]
D'oh! I had only looked at the open issues. Yup! That's it. Thank you.
