### ISSUE TITLE
not appearing in filters, obs 29.1.3

### ISSUE THREAD

**Issue by colevrya** [royshil/obs-backgroundremoval#392]
**Describe the bug**

when installed correctly (the plugin on the installer is placed in the obs folder on another drive) the filter still doesn't show

**To Reproduce**

install it with obs on steam  + on a different drive

**Expected behavior**

no filter in filters

**Screenshots**

![image](https://github.com/royshil/obs-backgroundremoval/assets/100182500/90193df7-b99f-4499-b4bf-a1fce952d9cd)

**Log and Crash Report**

[2023-07-18 03-33-52.txt](https://github.com/royshil/obs-backgroundremoval/files/12078200/2023-07-18.03-33-52.txt)

If OBS is crashing, upload the crash report here as well (`Help`>`Crash Reports`>`Show Crash Reports`).

**Desktop (please complete the following information):**

 - OS: windows 11
 - Browser: opera gx
 - Plugin Version: 1.1.2
 - OBS Version: 29.1.3

**Additional context**

i have tried a completely fresh install of obs

**Comment by umireon** [comment]
Where did you place the OBS itself and our plugin?

**Comment by royshil** [comment]
Looking at your logs it never tried to load the plugin
There's nothing there about it
So I conclude that the plugin wasn't installed to the right directory, most likely because OBS itself wasn't installed to the standard location.
Can you look in %appdata%/obs-studio/ ?
Did you install OBS in any custom way?

**Comment by colevrya** [comment]
I installed obs on my d drive ( using steam) so it should be "D:\SteamLibrary\steamapps\common\OBS Studio" which should be right since I did send the plugin to install there.. and no there is nothing in appdata, very werid

**Comment by royshil** [comment]
Non standard install locations are always a problem...

Can you try to manually install the plugin via the .zip package and copy the files to the right folder in your D drive?

**Comment by umireon** [comment]
The zip archive is not available on the release page now but is avaiable on the following URL:
https://github.com/royshil/obs-backgroundremoval/suites/14326488019/artifacts/806182746

**Comment by colevrya** [comment]
it works! THANKS! (also sorry for late response)
