### ISSUE TITLE
git tag prefix

### ISSUE THREAD

**Issue by drieks** [royshil/obs-backgroundremoval#404]
**Describe the bug**

Hi,

it seems that you removed the tag name prefix "v", versions up to v1.1.0 starts with "v", 1.1.1 and 1.1.2 don't have this prefix. Version 1.1.0 was released both with and without prefix.

This breaks at least flatpack and two arch linux aur scripts:

flatpak install com.obsproject.Studio.Plugin.BackgroundRemoval

https://aur.archlinux.org/packages/obs-backgroundremoval-git
https://aur.archlinux.org/packages/obs-backgroundremoval

All of them are still on the latest version with prefix "v", so it is currently not possible to install the latest version on arch linux based systems.

**To Reproduce**

Try to install the latest version from any of this sources:
flatpak install com.obsproject.Studio.Plugin.BackgroundRemoval

https://aur.archlinux.org/packages/obs-backgroundremoval-git
https://aur.archlinux.org/packages/obs-backgroundremoval

**Expected behavior**

The latest version should be installed.

**Screenshots**

-

**Log and Crash Report**

-

**Desktop (please complete the following information):**

 - OS: manjaro linux

**Additional context**

-

**Comment by royshil** [comment]
Shoot. This was a requirement from the latest OBS plugin template build scripts. We'll have to fix this on there

**Comment by umireon** [comment]
I want to ask obs-studio/obs-plugintemplate why they removed the v prefix.

**Comment by royshil** [comment]
@umireon i actually was the one who removed the `v` from the tag, but that was because the plugin template would not create the package correctly.

however, for now we can simple apply two tags `1.1.3` and `v1.1.3` for the same commit, and only create release based on the `1.1.3`
but the flatpack and AUR will still be able to download the source from github
what do you think?

**Comment by umireon** [comment]
I'm asking this on upstream now: https://github.com/obsproject/obs-plugintemplate/issues/86

**Comment by umireon** [comment]
I suppose the removal of the prefix "v" is intentional on the upstream and we have to fix Flatpak and AUR to conform to the new tag format.

**Comment by umireon** [comment]
I'm going to change all the build definitions to use the tag without v prefix.
