### ISSUE TITLE
Independent settings for different scenes

### ISSUE THREAD

**Issue by aspiers** [royshil/obs-backgroundremoval#407]
**Is your feature request related to a problem? Please describe.**

(Please forgive me if this is a general issue with OBS plugins rather than this particular plugin; I'm new to OBS so am not sure if it is, but I couldn't find any docs on the topic.)

I'd like to use this plugin in different scenes, but with different plugin settings in each.  For example, in one scene I want the plugin to blur my background, and in others I want it to remove the background.

However currently, whenever I change the "Blur background factor" plugin setting, it applies to all scenes, so I can't achieve this.  This happens even when I use the trick of having the video source (webcam) inside a different group per scene, and then applying the plugin as a filter on the group rather than directly on the video source.

**Describe the solution you'd like**

Plugin settings are saved and restored independently per filter, not globally.

**Comment by aspiers** [comment]
Thanks a lot!

**Comment by umireon** [comment]
As far as I know, you can create another source from the same device and you can configure different filters with different sources in this way.

**Comment by aspiers** [comment]
When I tried adding multiple sources from the same webcam, only the first one worked.  Maybe that's a Linux problem, or an issue with my setup.  Either way, I can't get it working that way - but still it's great to know that in theory it should be possible.  Thanks a lot for sharing!

**Comment by umireon** [comment]
I tried the group trick on my Ubuntu 22.04 and it works. Can you try this again?

https://github.com/royshil/obs-backgroundremoval/assets/1067855/06a298bf-5404-425f-9216-4d3633903102
