### ISSUE TITLE
Focus blur can be turned off

### ISSUE THREAD

**Issue by Dilzze** [royshil/obs-backgroundremoval#408]
The version 1.0.1 was good!!  at version 1,2 BRUL FOCUS POINT IS WORKING BAD imposible to set corectly! blur on my face.. please remove this

**Comment by Dilzze** [comment]
![Untitled](https://github.com/royshil/obs-backgroundremoval/assets/95056481/a4ff7897-a7fe-4ae3-a15e-643535898a36)

**Comment by umireon** [comment]
Can you describe your problem precisely and fill in the template?
Unfortunately, we cannot understand and resolve your problem because there is seldom information.
You have to provide us sufficient understanding of your situation.

Best,

**Comment by Dilzze** [comment]
Sorry my english is not very good. But i try to explain. Im talking about blur focus point. Its very hard to use. Becouse my head is not straight to the camera. and the blur is on my one side of the face. i try to adjust blur focus. the focus is bluring my left ar right side of the face. i think the focus blur point need to do biger radial to adjust. or let us tu turn it off.  becouse focus blur point is very narow (small) and all blur goes to the left or to the right side of the face. Thank you. Im suing rigt now 1.0.1 version is better.

**Comment by royshil** [comment]
I can add an option to disable the focus blur and revert to the original blur version.

We can release this in v1.1.3 or v1.1.4 since it's not a big change.

**Comment by Dilzze** [comment]
yes it will be nice. Just leave this option and you can make to turn this off funcion. And if you can make blur point r(adial) i dont know in english how to say blur point biger ar smaller to adjust. i think you understandand. Becouse blur point is to smalll right now. it will be better if we can change smaller ar biger <3 tnks for your hard work !!!!!

**Comment by royshil** [comment]
Implemented in #410

**Comment by royshil** [comment]
@Dilzze please check out the latest`main` version to see if it resolves your problem
