### ISSUE TITLE
Doesn't work with me (I'm brown and my background is kinda brown too)

### ISSUE THREAD

**Issue by ArudoPE** [royshil/obs-backgroundremoval#41]
I think I'm hard to identify to this plugin, because it can't identify me and "remove" the background. If I use the default settings, it shows a black screen, and if I play a little with the settings it shows this:
![image](https://user-images.githubusercontent.com/74159611/137575786-33b112e9-132d-4524-b377-3c64629c7b16.png)

**Comment by royshil** [comment]
try the MediaPipe model - it's faaar better then SINET

i don't think your skin complexion or background are particularly hard .... it should work OK

**Comment by royshil** [comment]
new models are implemented in latest versions
