### ISSUE TITLE
Background blur halo effect

### ISSUE THREAD

**Issue by dekatr0n** [royshil/obs-backgroundremoval#414]
**Is your feature request related to a problem? Please describe.**

I use the plugin to blur my background, but I've noticed that the blurred background often has a halo effect around the detected mask, where the colors of the subject bleed into the blurred background. This is especially noticeable if you stand against a dark background while wearing light colors.

**Describe the solution you'd like**

While blurring the background, the filter should only use the pixels outside the detected mask to create the blur effect. 

**Describe alternatives you've considered**

I've noticed that the background blur implementations in Google Meet and Zoom do this correctly, and there is no halo effect.

**Additional context**

I'm not exactly sure how this can be approached from an implementation POV, but maybe the "[Repeat edge pixels](https://www.youtube.com/watch?v=2ORequJEx1w)" feature of After Effects can be some inspiration?

**Comment by royshil** [comment]
Thanks for the feedback @dekatr0n 
can you post a screenshot here of the halo effect?

**Comment by dekatr0n** [comment]
Sure, here's a side-by-side with Google Meet and Zoom. If you look at the edges of my shoulders, you can see that obs-backgroundremoval has the halo effect while Meet and Zoom have sharp edges.

![halo-effect](https://github.com/royshil/obs-backgroundremoval/assets/88532740/f6efd438-97a3-4f53-9b53-f0db8949510c)

**Comment by royshil** [comment]
Alright yeah
Thanks for sharing this!
I know how to solve it. Our blur algorithm needs to take into account the mask, which it doesn't right now. That's not a huge lift I can take of it very soon.

**Comment by royshil** [comment]
![montage](https://github.com/royshil/obs-backgroundremoval/assets/441170/3f30e3d0-c0ee-4d6c-8f44-2507e11fe9fb)
I was able to solve it. A PR will be up soon, please help test 🙏

**Comment by royshil** [comment]
Fixed by #415

**Comment by dekatr0n** [comment]
I'm amazed at your speed and dedication to this project ❤️ 

I would like to help test it out, but I'm not exactly sure how. I tried downloading and installing the Windows build artifact from [here](https://github.com/royshil/obs-backgroundremoval/actions/runs/5735435086), but I cannot see the fix in action. Do I have to build it myself?

**Comment by royshil** [comment]
Yes.. that's supposed to be a build that includes the fix.

However the fix is in the .effect files and not the .dll file (assuming Windows).

Can you see that you copy in the effects as well from the build?

**Comment by dekatr0n** [comment]
Thanks, I can confirm that the fix works, but only when focal blur is disabled. When focal blur is enabled, the image still has a noticeable halo. Why is that? Here's is a comparison screenshot for reference:

![halo-fix-comparison](https://github.com/royshil/obs-backgroundremoval/assets/88532740/1885def0-8639-4ea9-897e-bab10d8256bd)

**Comment by royshil** [comment]
@dekatr0n thanks for the thorough testing, i appreciate your help!

the focal blur is different in nature. it doesn't use a mask per-se, so we can't block the non-masked pixels

while i think it might be possible to get the focal blur to be sharper around the edges, it will add (in my current analysis) some significant computation overhead in the pixel shader

it think we should merge the halo fix for now, and come back to focal blur later

**Comment by dekatr0n** [comment]
That makes sense. Thanks for the prompt fix!
