### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by Milliw** [royshil/obs-backgroundremoval#417]
**Describe the bug**

Can't install after compiling. Getting error:
```
[obs-backgroundremoval]$ sudo cmake --install build_x86_64 --prefix /usr
CMake Error: Error processing file: /home/ccc/obs-backgroundremoval/build_x86_64/cmake_install.cmake
[obs-backgroundremoval]$ echo $?
1
```

**To Reproduce**

Follow Fedora installation instructions

**Expected behavior**

Obvious

**Desktop (please complete the following information):**

 - OS: Nobara 38
 - Browser: \[e.g. chrome, safari\]
 - Plugin Version: 1.1.3
 - OBS Version: 29.1

**Comment by umireon** [comment]
Your description includes no information so we cannot debug your situation.

Can you get more information from cmake command such as debug or verbose option?
It would be great to attach the output of building command.

Best

**Comment by royshil** [comment]
@Milliw can you please run this with verbose option https://cmake.org/cmake/help/latest/manual/cmake.1.html#cmdoption-cmake-install-v ?
i wonder what went wrong

**Comment by Milliw** [comment]
`sudo cmake --install build_x86_64 --verbose --prefix /usr` returns the exact same output. Hm....
`git submodule update --init --verbose` just runs without any output at all.

**Comment by umireon** [comment]
@Milliw  Did you run the following command?
`.github/scripts/build-linux --skip-deps
`

**Comment by Milliw** [comment]
> 

I did.
I also deleted and redid everything twice now.

**Comment by umireon** [comment]
Could you post here all the outputs of every command as I requested?

**Comment by Milliw** [comment]
> Could you post here all the outputs of every command as I requested?

[obsbckgrndrmvl-log.txt](https://github.com/royshil/obs-backgroundremoval/files/12294619/obsbckgrndrmvl-log.txt)

I don't know what I might have done different this time except sending the output of the commands to a file but this time it all went through without errors... :-/

But yeah. Update successfully passed! =D
Thx for the support!! =)

**Comment by umireon** [comment]
I am glad to hear you sucessfully installed our plugin!
