### ISSUE TITLE
Linux - TensorRT - FAIL input has no shape specificied. Please run shape inference on the onnx model first

### ISSUE THREAD

**Issue by llitz** [royshil/obs-backgroundremoval#418]
**Describe the bug**

Changing from CPU to GPU - TensorRT isn't working.
OBS is throwing a few errors behind the scenes:

```
2023-08-03 16:59:50.188090109 [E:onnxruntime:background-removal-inference, tensorrt_execution_provider.h:73 log] [2023-08-03 22:59:50   ERROR] [graphShapeAnalyzer.cpp::checkCalculationStatusSanity::1504] Error Code 2: Internal Error (Assertion !isPartialWork(p.second.symbolicRep) failed. )
2023-08-03 16:59:50.309889173 [E:onnxruntime:, inference_session.cc:1644 operator()] Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc:1387 SubGraphCollection_t onnxruntime::TensorrtExecutionProvider::GetSupportedList(SubGraphCollection_t, int, int, const onnxruntime::GraphViewer&, bool*) const [ONNXRuntimeError] : 1 : FAIL : TensorRT input: 389 has no shape specified. Please run shape inference on the onnx model first. Details can be found in https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html#shape-inference-for-tensorrt-subgraphs

error: Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc:1387 SubGraphCollection_t onnxruntime::TensorrtExecutionProvider::GetSupportedList(SubGraphCollection_t, int, int, const onnxruntime::GraphViewer&, bool*) const [ONNXRuntimeError] : 1 : FAIL : TensorRT input: 389 has no shape specified. Please run shape inference on the onnx model first. Details can be found in https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html#shape-inference-for-tensorrt-subgraphs
```

**To Reproduce**

On my systems, trying to use any of the GPU modes triggers the error.
Modifying the segmentation model or trying to enable the GPU - TensorRT as the device will cause obs to stop for several seconds. It appears to fallback automatically to CPU, as it still works but CPU there are no changes to CPU utilization.

**Additional context**

Running on Gentoo Linux
OpenCV 4.7.0
TensorRT 8.6.16 (cuda 11.8)

I am unsure if this has been seen before or if there's something wrong with my setup, but all the libraries appear to be loaded correctly.

**Comment by umireon** [comment]
OpenCV 4.7.0 is not supported on out plugin. Can you update OpenCV to 4.8.0 and try again?

**Comment by llitz** [comment]
I see, I will give it a try when i have access to this machine again and
update you. Thank you

**Comment by umireon** [comment]
@royshil Can we close this issue as stalled?

**Comment by llitz** [comment]
I haven't been able to update opencv, please close I will update
accordingly if I get the newer version running and can test against it.

**Comment by royshil** [comment]
closing pending more information.

**Comment by MadMartian** [comment]
I just built and installed OpenCV 4.8.0, having the same issue here too with the freezing, although I don't think it's crashing anymore.  OBS freezes for several seconds before start-up (probably due to camera being last active with the background removal plugin turned on).  

- It also freezes for several seconds and/or crashes after changing from _GPU - TensorRT_ ➝ _CPU_ ➝ _GPU - TensorRT_.
- Similar behaviour changing the segmentation model from _SINet_ ➝ _MediaPipe_.

I see this in the logs after a change:
```
info: Model models/mediapipe.onnx input 0: name input_1:0 shape (4 dim) 1 x 144 x 256 x 3
info: Model models/mediapipe.onnx output 0: name segment:0 shape (4 dim) 1 x 144 x 256 x 2
info: Allocated 110592 sized float-array for input 0
info: Allocated 73728 sized float-array for output 0
```

It's not clear to me whether it's falling back to CPU or not.

**Comment by umireon** [comment]
Please do not post to the closed issue. Can you open a new issue?
