### ISSUE TITLE
Cannot Install on Mac Studio

### ISSUE THREAD

**Issue by donnievawter** [royshil/obs-backgroundremoval#428]
**Describe the bug**

**To Reproduce**

Download the mac os pkg 
open to install
follow install directions
**Expected behavior**

The plug-in to be installed

**Screenshots**

<img width="626" alt="image" src="https://github.com/royshil/obs-backgroundremoval/assets/89166921/f541115a-f983-426f-af3c-945b009c6d05">

The installation fails with no information
**Log and Crash Report**

Upload your OBS log file here (`Help`>`Log Files`>`Show Log Files`) to help us find cause of the problem.

If OBS is crashing, upload the crash report here as well (`Help`>`Crash Reports`>`Show Crash Reports`).

**Desktop (please complete the following information):**

 - OS: 13.4.1 (c) (22F770820d)  M1Max 64 bit
 - Browser: Edge
 - Plugin Version: latest
 - OBS Version: 29.1.3

**Additional context**

**Comment by umireon** [comment]
Please post here the log of the installer.
It can be shown by Command+L during the installation.

**Comment by donnievawter** [comment]
Aug 23 21:28:50 raven Installer[6941]: Failed to load specified background image
Aug 23 21:28:50 raven Installer[6941]: Could not load resource readme: (null)
Aug 23 21:28:50 raven Installer[6941]: Could not load resource license: (null)
Aug 23 21:29:13 raven installd[6191]: PackageKit: ----- Begin install -----
Aug 23 21:29:23 raven shove[6981]: Error relinking file (primary): /var/folders/kn/r5k_25m548jdqn91yltc9df00000gn/C/PKInstallSandboxManager/ED8C0D8A-926B-49EE-A309-CF9AD81577DB.activeSandbox/Root/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin to /Users/donaldvawter/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin, error = 13
	srcPath = /var/folders/kn/r5k_25m548jdqn91yltc9df00000gn/C/PKInstallSandboxManager/ED8C0D8A-926B-49EE-A309-CF9AD81577DB.activeSandbox/Root/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin NSFileOwnerAccountID=501 NSFileSystemFileNumber=95857321 NSFileExtensionHidden=0 NSFileSystemNumber=16777233 NSFileSize=96 NSFileGroupOwnerAccountID=20 NSFileOwnerAccountName=donaldvawter NSFileCreationDate=2023-08-14 08:41:30 +0000 NSFilePosixPermissions=493 NSFileType=NSFileTypeDirectory NSFileGroupOwnerAccountName=staff NSFileReferenceCount=3 NSFileModificationDate=2023-08-14 08:41:30 +0000
	dstParentPath = /Users/donaldvawter/Library/Application Support/obs-studio/plugins NSFileOwnerAccountID=0 NSFileSystemFileNumber=65633344 NSFileExtensionHidden=0 NSFileSystemNumber=16777233 NSFileSize=96 NSFileGroupOwnerAccountID=20 NSFileOwnerAccountName=root NSFileCreationDate=2023-04-21 19:14:44 +0000 NSFilePosixPermissions=493 NSFileType=NSFileTypeDirectory NSFileGroupOwnerAccountName=staff NSFileReferenceCount=3 NSFileModificationDate=2023-04-21 22:03:12 +0000
Aug 23 21:29:23 raven shove[6981]: [src=unknown] /Users/donaldvawter/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin: unable to restore flags to destination due to failed lstat (error 2)
Aug 23 21:29:23 raven shove[6981]: [source=dir, dst=notExist] failed _relinkFile(/var/folders/kn/r5k_25m548jdqn91yltc9df00000gn/C/PKInstallSandboxManager/ED8C0D8A-926B-49EE-A309-CF9AD81577DB.activeSandbox/Root/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin, /Users/donaldvawter/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin): Permission denied
	srcPath = /var/folders/kn/r5k_25m548jdqn91yltc9df00000gn/C/PKInstallSandboxManager/ED8C0D8A-926B-49EE-A309-CF9AD81577DB.activeSandbox/Root/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin NSFileOwnerAccountID=501 NSFileSystemFileNumber=95857321 NSFileExtensionHidden=0 NSFileSystemNumber=16777233 NSFileSize=96 NSFileGroupOwnerAccountID=20 NSFileOwnerAccountName=donaldvawter NSFileCreationDate=2023-08-14 08:41:30 +0000 NSFilePosixPermissions=493 NSFileType=NSFileTypeDirectory NSFileGroupOwnerAccountName=staff NSFileReferenceCount=3 NSFileModificationDate=2023-08-14 08:41:30 +0000
	dstParentPath = /Users/donaldvawter/Library/Application Support/obs-studio/plugins NSFileOwnerAccountID=0 NSFileSystemFileNumber=65633344 NSFileExtensionHidden=0 NSFileSystemNumber=16777233 NSFileSize=96 NSFileGroupOwnerAccountID=20 NSFileOwnerAccountName=root NSFileCreationDate=2023-04-21 19:14:44 +0000 NSFilePosixPermissions=493 NSFileType=NSFileTypeDirectory NSFileGroupOwnerAccountName=staff NSFileReferenceCount=3 NSFileModificationDate=2023-04-21 22:03:12 +0000
Aug 23 21:29:23 raven installd[6191]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=120 "An unexpected error occurred while moving files to the final destination." UserInfo={NSLocalizedDescription=An unexpected error occurred while moving files to the final destination., arguments=(
	    "-f",
	    "-s",
	    "/var/folders/kn/r5k_25m548jdqn91yltc9df00000gn/C/PKInstallSandboxManager/ED8C0D8A-926B-49EE-A309-CF9AD81577DB.activeSandbox/Root",
	    "/Users/donaldvawter"
	), NSUnderlyingError=0x14f923f50 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}} {
	    NSLocalizedDescription = "An unexpected error occurred while moving files to the final destination.";
	    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=13 \"Permission denied\"";
	    arguments =     (
	        "-f",
	        "-s",
	        "/var/folders/kn/r5k_25m548jdqn91yltc9df00000gn/C/PKInstallSandboxManager/ED8C0D8A-926B-49EE-A309-CF9AD81577DB.activeSandbox/Root",
	        "/Users/donaldvawter"
	    );
	}
Aug 23 21:29:23 raven Installer[6941]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Aug 23 21:29:23 raven Installer[6941]: Displaying 'Install Failed' UI.
Aug 23 21:29:23 raven Installer[6941]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.




Okay so it is a permissions issue but there is no directory ops-studio under Application Support
The installer will not let me change the install location to All Users or make any other changes to location
That folder is not under the root Library Application Support either

**Comment by umireon** [comment]
You have to use admin privileges if you do not configure the installer.

You can change the installing destination by clicking the customize button on the left bottom corner of the second screen on the installer.
It should say that the installation target is under the current user's home directory.
Files must be installed under /Users/yourname/Library/Application Support/obs-studio/plugins/obs-backgroundremovsl.plugin, and not under /Library.

**Comment by donnievawter** [comment]
Thanks,
For some reason the plugins folder was owned by root.
Changing that solved the issue and installation succeeded.
You may resolve the issue and thanks again for the quick response.
