### ISSUE TITLE
Crashed on windows when applied to camera

### ISSUE THREAD

**Issue by siakc** [royshil/obs-backgroundremoval#43]
[carsh_report.txt](https://github.com/royshil/obs-backgroundremoval/files/7371642/carsh_report.txt)
A few seconds after the filter is added OBS Studio crashes.

**Comment by Serph91P** [comment]
Same error here.

**Comment by royshil** [comment]
i'm working on the v27.1.3 OBS compatible plugin...

**Comment by royshil** [comment]
Please try https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.4.0
@Serph91P @DirkUHofmann @siakc @Divinelight

**Comment by royshil** [comment]
new versions are more robust now
