### ISSUE TITLE
Background removal filter shows on all scenes in OBS

### ISSUE THREAD

**Issue by ddpetty** [royshil/obs-backgroundremoval#434]
I'm unable to switch scenes in one recording take due to the background removal showing on all scenes. I use the same camera for all of my scenes and would like to switch from my headshot scene to a screen display with my face showing. Instead, I have to record all the headshot scenes and display capture (with face showing) scenes separately. I wouldn't dare try live streaming with this limitation.

I'm currently searching for alternative OBS filter options, and I like this tool very much.

**Comment by umireon** [comment]
If you want to use a camera in different scenes with different settings of our plugin, #407 is the solution for you.

## Summary of #407
Our plugin can be applied to a group. You can put the same camera source without our plugin into the different groups with our plugin on the different scenes. In this way, you can have the different configurations of our plugin on each scene.

The video that demonstrates this configuration is available.
https://github.com/royshil/obs-backgroundremoval/assets/1067855/06a298bf-5404-425f-9216-4d3633903102
