### ISSUE TITLE
Installation not working on Mac

### ISSUE THREAD

**Issue by pongy20** [royshil/obs-backgroundremoval#437]
I downloaded the installer for mac (OS version: 13.5.1) but it don't works. There is no background removal filter in camera filters. Do you have any ideas ?

**Comment by umireon** [comment]
Please post here the screenshot and the log that show the plugin is not installed.

**Comment by pongy20** [comment]
THanks for the reply, i simple sownloaded the .pkg file from the assets sections and followed the installation process without any problem. THan i restarted OBS and tried to apply the filter but it was not shown. 
![image](https://github.com/royshil/obs-backgroundremoval/assets/19792979/2d0aa1a5-5937-448a-b814-5a0b25d39961)
![image](https://github.com/royshil/obs-backgroundremoval/assets/19792979/b4afb788-948f-4ee3-b13e-893397cc6299)
Is there something else i have to do to use this plugin?

**Comment by umireon** [comment]
Can you post here the log? Logs can be obtained from the help menu.

**Comment by pongy20** [comment]
[2023-09-05 21-53-41.txt](https://github.com/royshil/obs-backgroundremoval/files/12533946/2023-09-05.21-53-41.txt)
[2023-09-05 22-01-39.txt](https://github.com/royshil/obs-backgroundremoval/files/12533948/2023-09-05.22-01-39.txt)
[2023-09-05 22-05-00.txt](https://github.com/royshil/obs-backgroundremoval/files/12533949/2023-09-05.22-05-00.txt)
[2023-09-06 07-52-57.txt](https://github.com/royshil/obs-backgroundremoval/files/12533950/2023-09-06.07-52-57.txt)

I the logs there is the line that says: Module '/Users/ericdupont/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin/Contents/MacOS/obs-backgroundremoval' not loaded

**Comment by umireon** [comment]
The latest version of the plugin only supports OBS 29.1.2 or after. Your OBS is 29.0.2 and too old for the plugin.
Please update the OBS and try it again.

https://cdn-fastly.obsproject.com/downloads/obs-studio-29.1.3-macos-arm64.dmg

**Comment by pongy20** [comment]
Thanks man, works perfectly fine :)
