### ISSUE TITLE
facing a issue of background removal in mac using obs studio

### ISSUE THREAD

**Issue by ashishmeena786** [royshil/obs-backgroundremoval#438]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log and Crash Report**

Upload your OBS log file here (`Help`>`Log Files`>`Show Log Files`) to help us find cause of the problem.

If OBS is crashing, upload the crash report here as well (`Help`>`Crash Reports`>`Show Crash Reports`).

**Desktop (please complete the following information):**

 - OS: \[e.g. iOS\]
 - Browser: \[e.g. chrome, safari\]
 - Plugin Version: \[e.g. 0.5.1\]
 - OBS Version: \[e.g. 28.02\]

**Additional context**

**Comment by umireon** [comment]
I suppose this is an invalid issue.
