### ISSUE TITLE
Crash for OBS on windows 10 when applying Background Removal filter

### ISSUE THREAD

**Issue by Divinelight** [royshil/obs-backgroundremoval#44]
Added crash logs, would love some help or understanding why this does not work for me.

Thank you for this tool! :)

[Crash 2021-10-19 16-53-05.txt](https://github.com/royshil/obs-backgroundremoval/files/7374487/Crash.2021-10-19.16-53-05.txt)
[Crash 2021-10-19 16-53-39.txt](https://github.com/royshil/obs-backgroundremoval/files/7374488/Crash.2021-10-19.16-53-39.txt)
[Crash 2021-10-19 16-56-47.txt](https://github.com/royshil/obs-backgroundremoval/files/7374489/Crash.2021-10-19.16-56-47.txt)

**Comment by Serph91P** [comment]
Have the same error dunno why.

**Comment by royshil** [comment]
i'm working on the v27.1.3 OBS compatible plugin...

**Comment by royshil** [comment]
Please try https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.4.0 for v27.1.3 support

**Comment by VG08** [comment]
so am having the same problem, but I don't think there is an arch release for 0.40

**Comment by VG08** [comment]
fixed it my bumping the version of the pkgver in PKGBUILD and now it works

**Comment by royshil** [comment]
crashings dealt with in latest versions
