### ISSUE TITLE
Update OBS Version Support and Compatibility?

### ISSUE THREAD

**Issue by Zahrun** [royshil/obs-backgroundremoval#451]
I noticed that obs-backgroundremoval 1.1.6 seem to work fine in OBS 27.2.3 cf. https://github.com/pacstall/pacstall-programs/pull/4576#issuecomment-1734989686
Should OBS Version Support and Compatibility be updated in the README? https://github.com/royshil/obs-backgroundremoval/blob/bf44ccc1330100cc3e6a6d5c7b40ec74ea914020/README.md?plain=1#L50-L53

**Comment by umireon** [comment]
We don't want to keep the compatibility with OBS 27-.
I know our plugin works with OBS 27 when the plugin is compiled with CMake directly and not with .github/scripts/build-linux.zsh.
However, our official builds will be generated by .github/scripts/build-linux.zsh and the deb file we provide won't work with OBS 27.
In conclusion, we don't want to state that we support OBS 27-.

Best,
