### ISSUE TITLE
Add Peter Lin's RVM model support

### ISSUE THREAD

**Issue by coolsoftrf** [royshil/obs-backgroundremoval#46]
There's a great AI network model that seems to remove background much more effectively than all currently supported models. Could you integrate it into your plugin?
https://github.com/PeterL1n/RobustVideoMatting

**Comment by royshil** [comment]
i'm working on it right now, but that model has a bunch more inputs and outputs (recurrent states)...
it will need some abstracting since the inference code is starting to have a mess of `if` statements! 🤮

**Comment by royshil** [comment]
i added the RVM model but it doesn't perform any better than MediaPipe in terms of segmentation... and it seems slower. but i'll keep trying to get it to perform better

**Comment by royshil** [comment]
Please try https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.4.0 it has the new model

**Comment by royshil** [comment]
RVM implemented
