### ISSUE TITLE
CUDA mode is not working

### ISSUE THREAD

**Issue by HaoTao95** [royshil/obs-backgroundremoval#47]
I built a plugin with CUDA mode, 
But it shows "No properties available". 

I have a NVIDIA RTX 3009 installed in my pc

Can anyone help?

**Comment by royshil** [comment]
i'm looking into the CUDA release. it has to do with bundling the CUDA DLLs , i believe

but i appreciate any help!

**Comment by royshil** [comment]
windows builds support directML which should give acceleration
