### ISSUE TITLE
How install on Mac Catalina ?

### ISSUE THREAD

**Issue by 3xploiton3** [royshil/obs-backgroundremoval#48]
![image](https://user-images.githubusercontent.com/19517680/140005040-5c8cbf0b-09ed-4d35-bb3d-2fbd799043af.png)

but background remove filter doesnt show up,

![image](https://user-images.githubusercontent.com/19517680/140005130-ef708a4f-f286-44af-9a56-02ab66242c5a.png)

sorry, anyone can help me?

**Comment by royshil** [comment]
it's about the OBS version - I will release a new version very soon so you can use it in the latest OBS

**Comment by royshil** [comment]
Please try https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.4.0

**Comment by AlekseiSmirnov** [comment]
I got the same problem. How do I make OBS to detect the filter?
![image](https://user-images.githubusercontent.com/10200871/144632496-7d03543e-fda0-4e5c-8fe8-8e894ca4090d.png)

![Uploading image.png…]()

**Comment by royshil** [comment]
new Mac installers available
