### ISSUE TITLE
Missing dependency in docs on linux: libsimde-dev

### ISSUE THREAD

**Issue by koen-db** [royshil/obs-backgroundremoval#49]
Tested on ubuntu 20.10:
`cmake .. && cmake --build . && cmake --install .
-- Configuring done
-- Generating done
-- Build files have been written to: /home/k/Projects/Downloaded/obs-backgroundremoval/build
[ 33%] Building CXX object CMakeFiles/obs-backgroundremoval.dir/src/background-filter.cpp.o
In file included from /usr/include/obs/graphics/vec4.h:22,
                 from /usr/include/obs/graphics/vec3.h:21,
                 from /usr/include/obs/obs.h:26,
                 from /usr/include/obs/obs-module.h:20,
                 from /home/k/Projects/Downloaded/obs-backgroundremoval/src/background-filter.cpp:1:
/usr/include/obs/graphics/../util/sse-intrin.h:24:10: fatal error: simde/x86/sse2.h: No such file or directory
   24 | #include <simde/x86/sse2.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/obs-backgroundremoval.dir/build.make:82: CMakeFiles/obs-backgroundremoval.dir/src/background-filter.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/obs-backgroundremoval.dir/all] Error 2
gmake: *** [Makefile:149: all] Error 2`

This is the most relevant item:
`simde/x86/sse2.h: No such file or directory
`

I fixed this by installing `libsimde-dev`

**Comment by royshil** [comment]
@koen-db  can you plz make a pull request with this fix?

**Comment by ldsands** [comment]
How and where do you install libsimde-dev (I'm on KDE Neon which is built on 20.04)?

**Comment by royshil** [comment]
@ldsands `apt-get install` will work?

**Comment by ldsands** [comment]
I eventually figured it out and got it working. Though now I'm running Manjaro for unrelated reasons and installation there is trivial, so it's all moot to me now. I'll put my instructions (I created for myself) below. Maybe it'll be useful to someone else.

## OBS Extensions

- Install [OBS Studio](https://obsproject.com/) - `sudo apt-get install obs-studio`
    - Do not install using snap or flatpak

    ```sh
    sudo add-apt-repository ppa:obsproject/obs-studio
    sudo apt update
    sudo apt-get install -y \
        libc-dev-bin \
        libc6-dev git \
        build-essential \
        checkinstall \
        cmake \
        ffmpeg \
        v4l2loopback-dkms \ # this adds support for creating a virtual camera
        obs-studio \
        qtbase5-dev
    ```

- [OBS Plugin: Background Removal](https://github.com/royshil/obs-backgroundremoval) - This removes the background from the video in OBS

    ```sh
    cd ~/Downloads
    sudo apt install -y libopencv-dev language-pack-en wget git build-essential cmake
    # sudo apt install -y libobs-dev libopencv-dev language-pack-en wget git build-essential cmake
    wget https://github.com/microsoft/onnxruntime/releases/download/v1.7.0/onnxruntime-linux-x64-1.7.0.tgz
    sudo tar xzvf onnxruntime-linux-x64-1.7.0.tgz --strip-components=1 -C /usr/local/ --wildcards "*/include/*" "*/lib*/"
    # clone and enter the repo
    git clone https://github.com/royshil/obs-backgroundremoval.git
    cd obs-backgroundremoval
    # make and enter build directory
    mkdir build && cd build
    # compile the files needed for the plugin
    cmake .. && cmake --build . && sudo cmake --install .
    # add links because obs and the plugin are installed to different locations for older versions
    sudo ln -s /usr/local/lib/obs-plugins/obs-backgroundremoval.so /usr/lib/obs-plugins/
    sudo ln -s /usr/local/share/obs/obs-plugins/obs-backgroundremoval /usr/share/obs/obs-plugins/

**Comment by royshil** [comment]
latest builds take care of this
