### ISSUE TITLE
Installation on an M1 Mac w/Monterey

### ISSUE THREAD

**Issue by NuclearMonster** [royshil/obs-backgroundremoval#51]
Managed to get a little further than #48 via a few changes.

1) I observed how other plugins (_StreamFX_ & _obs-ndi_) had their file hierarchy on macos and changed it up to match the `/Library/Application Support/obs-studio/` here's what I ended up with:
<img width="710" alt="Screen Shot 2021-11-07 at 01 05 36" src="https://user-images.githubusercontent.com/903791/140642558-674e4f45-6ef9-400e-b49b-e361e8a424ea.png">

2) then I got busted by the code signature police:
<img width="248" alt="Screen Shot 2021-11-07 at 01 03 12" src="https://user-images.githubusercontent.com/903791/140642574-3ed25f88-8c74-4ee9-9b2f-0fb06773d8cc.png">

I can probably bypass number 2 by building it myself

**Comment by NuclearMonster** [comment]
> I can probably bypass number 2 by building it myself
That worked. Unfortunately I just get a black image:
![Screen Shot 2021-11-07 at 01 39 37](https://user-images.githubusercontent.com/903791/140643405-a4ae04ac-baf3-45c3-b571-04a76b63368b.png)

**Comment by NuclearMonster** [comment]
It does appear to be doing something, CPU usage for OBS gets way higher when the filter is enabled...

**Comment by royshil** [comment]
looks like it's working , if it's not crashing
but  maybe your particular camera is giving off a stream that the plugin can't handle
what kind of camera are you using?

**Comment by NuclearMonster** [comment]
I get the same result with any of the cameras I've tried, the built-in FaceTime camera, Epoc Cam (what I normally use) or a Logitech c920

**Comment by royshil** [comment]
M1 install all set now
