### ISSUE TITLE
Masking is sometimes incomplete

### ISSUE THREAD

**Issue by fishzle** [royshil/obs-backgroundremoval#55]
OBS 27.1.3, windows x64 and plugin version 0.4.0.
Occurs with all different models (mediapipe, selfie segmentation, the new one, the old ones)
Tried it with both CPU and GPU.

I've noticed that if I make an enclosed space, then the space doesn't get masked.

![mask 1](https://user-images.githubusercontent.com/8211862/142194802-45bdefa7-c5d1-4d63-9959-b8c3475a1bb8.png)

I think it's the same issue when the enclosed space is bounded by an edge
![mask 2](https://user-images.githubusercontent.com/8211862/142194796-72e2f45f-217c-4091-81e2-6cf6fc5fdc9b.png)

Is this expected behaviour?

**Comment by royshil** [comment]
Yes actually this is because i'm using a contour based post-processing step. it helps in removing noise from smaller spots of detection
if you disable "Contour Filter" - it should not be doing this kind of filtering. 
Try it out

**Comment by fishzle** [comment]
Awesome. That is exactly what I was missing.
I didn't understand "Contour Filter" when I first set it up. 

thank you.
