### ISSUE TITLE
arch linux obs problem

### ISSUE THREAD

**Issue by ghost** [royshil/obs-backgroundremoval#63]
ı dont see is this working ??
![2021-12-01-193526_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/144274945-e701b180-39b1-486b-aac9-aae29cf2c461.png)
![Screenshot_2021-12-01_19-37-10](https://user-images.githubusercontent.com/80429360/144274949-49282d57-c76c-42b6-979a-88a41bb6cb4e.png)

**Comment by PixelMelt** [comment]
Same issue on Kubuntu 21.04 x86_64

**Comment by tuxfoo** [comment]
It looks like you built the package but did not install it.
`pacman -U obs-backgroundremoval-0.4.0-1-x86_64.pkg.tar.zst`

Also, the PKGBUILD script is building version 0.3 which crashes obs >27
You can update it to build version 0.4. To do this you need to edit PKGBUILD and change the version and checksum
```
pkgver=0.4.0
sha256sums=('e88bbc902154b5efd46d8fc1dee52fcf079c8ff2ae6593d9f716017fdd1ef601'
            '0345f45f222208344406d79a6db3280ed2ccc884dc1e064ce6e6951ed4c70606')
```

**Comment by Danie10** [comment]
Thanks this version 0.4 fixed the crash for me on Manjaro KDE.
