### ISSUE TITLE
OBS Background Removal latest version crashing OBS.

### ISSUE THREAD

**Issue by ShanghaiTimes** [royshil/obs-backgroundremoval#64]
[2021-12-02 15-15-41.txt](https://github.com/royshil/obs-backgroundremoval/files/7643129/2021-12-02.15-15-41.txt)
[OBS Plugin Crash Report.txt](https://github.com/royshil/obs-backgroundremoval/files/7643130/OBS.Plugin.Crash.Report.txt)
These are two crash reports. On from Apple and one from OBS

**Comment by ifuchs** [comment]
I can confirm that the latest Background Removal tool crashes OBS v27.1.3 under Mojave v10.14.6

**Comment by cathblatter** [comment]
I can confirm this with OBSv27.1.3 and Big Sur 11.6.1

**Comment by OBS1227** [comment]
Hello, I want to share my experience. I installed an earlier version of BR and an earlier version of OBS Mac OS High Sierra. Royshilkrot answered my question that he had not upgraded it for OBS 27.1.3 yet.  Then he upgraded it for 27.1.3. I installed it the best way I knew how and everything is there except the webcam is black. You don't see me at all. I am using the internal Mac camera. He told me I didn't install all of the components I guess, but that was the last I heard from him. I truly appreciate the time and effort he put into this software and it's free, but would love to know what I am missing.  I can see the awesome potential and it would be built into OBS.

**Comment by anumerico** [comment]
Ubuntu 20.04, obs-studio installed through snap, OBS 27.1.3-modified installed through snap.
obs-background removal gives segmentation fault.
The last relevant lines and error messages for debugging:
https://pastebin.com/raw/4KaqtT1W
Hope you can help me figure it out.

**Comment by heather567** [comment]
Crashing OBS with High Sierra 10.13.6
I have installed correctly, OBS working fine before 'background remover' install. 
I can see it in the filter list, but crashes when in studio mode trying to do a simple transition, every time.
Is there anything else I can do to fix this from crashing, I SO want to use the plugin!
Thanks

**Comment by OBS1227** [comment]
I just wanted to say, "Kudos to Mr. Shilkrot for taking the time and work on creating this software". I can see the possibilities, but I'm going to take a break from it now. I didn't have any projects or anything that I wanted to do, so I had fun playing around with it. However, I am planning on using OBS to give Zoom music lessons and BR makes it crash a lot. Furthermore, it appears I can't use the built in Virtual Cam when BR is installed. This is the only way that I could get OBS through Zoom, so I can't keep it installed unfortunately. I can't wait for the upgrades! I hope one day that it becomes native to OBS and not an extra plugin.  Thanks!   Just an FYI: I am using an i7 imac 64 gb OS High Sierra. if this helps in future releases.

**Comment by faastcall** [comment]
Cannot replicate on Arch Linux x86_64, 5.16.1-zen1-1-zen, seems like specifically an issue with the MacOS build.

**Comment by OBS1227** [comment]
I couldn't wait for an answer. LOL. .Don't quote me on this, but it appears that your plug in doesn't show up in copies of OBS. Well at least in the right spot. LOL.  In the copy it shows up in effects filters and does nothing, so I'm hoping that I could play around with it and still use the unaffected copies OBS. Funny. I thought that when I installed it a day or so ago that it showed up in all the copies I had made of OBS, but I may have been tired or something. The true test is if the copies without BR will not crash. The only thing I did differently was threw out the installer and the folder of your plugin from the contents menu. However, when I do choose robust matting it crashes. But Virtual Camera works! Very cool! I will include a crash report or selecting Robust Matting. here. Keep in mind I did have it working a little in the past. Wow! So far so good! No crashing. Thanks
[2022-01-17 21-44-20.txt](https://github.com/royshil/obs-backgroundremoval/files/7886079/2022-01-17.21-44-20.txt)

**Comment by OBS1227** [comment]
Ok. So I am about to go to bed and Background Remover has not crashed in OS High Sierra 10.13. 6. It's been on for at least 25 min. YES!  I am really happy about that! But choosing  Robust Video Matting still crashes, but  everything else seems stable. Now, if others are getting good results I would work on trying to get the selection around some parts of your body to stop shimmering (don't know the proper term to use.) I wonder if it's in the software or I may need to experiment with lighting or the color of my clothes. Thanks so much Mr. Shilkrot!...I did read that Robust Video Matting has a small upgrade, but it's beyond anything I know how to do to install it. It's working! YES!!!!!

**Comment by OBS1227** [comment]
So it appears that Robust Video Matting works! However, I click on it OBS crashes. I reopen OBS and I select it one more time and it works. This is my log file. Thanks.: 
[2022-01-18 16-10-58.txt](https://github.com/royshil/obs-backgroundremoval/files/7893211/2022-01-18.16-10-58.txt)

**Comment by alphaville** [comment]
I'm having the same issue on MacOS. You can find my [log file here](https://pastebin.com/5hmq07t7) in case it helps.

**Comment by OBS1227** [comment]
I got it to work on OS Catalina Here goes. Good luck!:
The Installer Zip:
-Download BR to your hard drive.
-Unzip it. Place it where you can access it on your hard drive.
You will see two folders: Plugins and Resources. You will need to install the contents of the folders from them separately.

OBS app on your Mac:
-Go to your Mac applications folder.
- Right click on the OBS App. You’ll see “Show Package contents”
-Contents - then select the plugins folder.

Installer Zip to Mac OBS package:
- From the Background Removal zip Copy “the background removal.so file” into that plugins folder of OBS that is right below the Mac OS folder. There is another plugins folder, but not that one.You won’t see it yet.

Plugins from Zip to Mac OBS app:
-From the Background removal zip that you just unzipped go to resources -data - OBS Plugins folder and copy OBS Background removal folder from your zip into your OBS plugins folder on your Mac. This will be a sub folder to the data folder, called OBS-plugins. Paste it in there.
Close up OBS file structure and then open up OBS.
This should work.

Please let me know if it works!
OBS 1227 and
Want To Learn
[Quote](https://obsproject.com/forum/conversations/obs-background-removal-plugin.7127/reply?quote=17558) [Reply](https://obsproject.com/forum/conversations/obs-background-removal-plugin.7127/reply?quote=17558)

**Comment by patryk-bernasiewicz** [comment]
> Please let me know if it works!

@OBS1227  Unfortunately it still doesn't work - I still get the error that OBS is damaged and needs to be removed from Applications.

The tip to try and paste the files directly into the correct folders was a good try though!

**Comment by balathebug** [comment]
@OBS1227 Im facing the issue. it keep-on crashing after pasting it.

**Comment by missmah** [comment]
Can confirm this crashes on Ubuntu 18.04 and Ubuntu 20.04 as well! This bug has been open for years with no comment from maintainers?

**Comment by umireon** [comment]
Can you try v0.5.13? Just released 5 days ago.
https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.5.13

**Comment by umireon** [comment]
@missmah Can you try v0.5.13? Just released 5 days ago.
https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.5.13

**Comment by umireon** [comment]
Note that OBS 28+ is required for new versions so that on Ubuntu 18.04 this plugin require flatpak installation.

**Comment by missmah** [comment]
Trying to give it a try, but ppa and other ways haven't worked. So flatpak
is the preferred way? No direct install?

**Comment by missmah** [comment]
To be clear, I'm actually upgrading the distribution. I tried to build from
source on 20.04 but got stuck on Qt6, which looks like it needs 22.04
(sigh). So upgrading again now.

**Comment by umireon** [comment]
I suppose that building this plugin needs the very latest version of Ubuntu. You can try a pre-built plugin available as a deb package.
https://github.com/royshil/obs-backgroundremoval/releases/download/v0.5.13/obs-backgroundremoval-0.5.13-linux-x86_64.deb

**Comment by missmah** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}I tried the .deb package with the .ppa, but it was never able to find it as a plugin - it didn't show up under filters...                                                                                                                                                                          From: ***@***.***: March 17, 2023 9:56 PMTo: ***@***.***: ***@***.***: ***@***.***; ***@***.***: Re: [royshil/obs-backgroundremoval] OBS Background Removal latest version crashing OBS. (Issue #64)  
I suppose that building this plugin needs the very latest version of Ubuntu. You can try a pre-built plugin available as a deb package.
https://github.com/royshil/obs-backgroundremoval/releases/download/v0.5.13/obs-backgroundremoval-0.5.13-linux-x86_64.deb

**Comment by umireon** [comment]
@missmah Did you check effect filters?
The place this plugin appears is changed recently but this change is not reflected in the README yet.

**Comment by missmah** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}Yes, it was not showing up in either - on 22.04 it is properly showing up, though, and working now.                                                                                                                                                                          From: ***@***.***: March 17, 2023 10:20 PMTo: ***@***.***: ***@***.***: ***@***.***; ***@***.***: Re: [royshil/obs-backgroundremoval] OBS Background Removal latest version crashing OBS. (Issue #64)  
@missmah Did you check effect filters?
The place this plugin appears is changed recently but this change is not reflected in the README yet.

**Comment by ShanghaiTimes** [comment]
How do I enable this on M2 Mac Mini?  It installed ok it seems, but I don’t see it in FiltersThanks-----Robert ***@***.***_A_ChalmersOn 18 Mar 2023, at 2:18 am, Layla ***@***.***> wrote:﻿
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}I tried the .deb package with the .ppa, but it was never able to find it as a plugin - it didn't show up under filters...                                                                                                                                                                          From: ***@***.***: March 17, 2023 9:56 PMTo: ***@***.***: ***@***.***: ***@***.***; ***@***.***: Re: [royshil/obs-backgroundremoval] OBS Background Removal latest version crashing OBS. (Issue #64)  
I suppose that building this plugin needs the very latest version of Ubuntu. You can try a pre-built plugin available as a deb package.
https://github.com/royshil/obs-backgroundremoval/releases/download/v0.5.13/obs-backgroundremoval-0.5.13-linux-x86_64.deb

**Comment by umireon** [comment]
@ShanghaiTimes See https://github.com/royshil/obs-backgroundremoval/issues/146#issuecomment-1456343517
Background removal will appear on Effect filters.

**Comment by ShanghaiTimes** [comment]
It installed correctly, but isn’t appearing anywhere. Not in any kind of filters.Disappeared.-----Robert ***@***.***_A_ChalmersOn 18 Mar 2023, at 9:05 am, Kaito Udagawa ***@***.***> wrote:﻿
@ShanghaiTimes See #146 (comment)
Background removal will appear on Effect filters.

**Comment by umireon** [comment]
@ShanghaiTimes Post here logs please 🙇

**Comment by royshil** [comment]
@missmah  where does the plugin show up for you now? "Effect Filter" or "Audio/Video Filter"?

**Comment by ShanghaiTimes** [comment]
Effect filter-----Robert ***@***.***_A_ChalmersOn 18 Mar 2023, at 2:37 pm, Roy Shilkrot ***@***.***> wrote:﻿
@missmah  where does the plugin show up for you now? "Effect Filter" or "Audio/Video Filter"?

**Comment by jd-apprentice** [comment]
After I add the filter it crashses obs. Ubuntu 22.04 LTS Kernal 5.19

**Comment by umireon** [comment]
@jd-apprentice Can you open another separate issue and attach crashes and logs there?
