### ISSUE TITLE
GPU - DirectML setting does not appear to stick between opening OBS

### ISSUE THREAD

**Issue by koofka** [royshil/obs-backgroundremoval#65]
Have noticed that on an new open of OBS that CPU usage will spike higher then normal (35% or so with my current settings) and after debugging the issue it appears to be that the GPU - DirectML setting doesnt get set on reopening OBS.  The picklist item is selected, but if I open the Background Removal filter and choose CPU and then reselect GPU - DirectML the CPU usage drops again to the more anticipated 7% or so.  It could also be my frame calculation setting that is responsible as its currently set to 6 as I am rendering at 60fps and perhaps it is reset to the input value upon reselecting the Inference device.

Nice plugin and thanks for the work on it.

**Comment by royshil** [comment]
This is expected to work now in latest versions

**Comment by royshil** [comment]
We need to investigate using the plugin "Settings" options to persist the properties to disk after they are changed and load them up when the plugin loads. https://docs.obsproject.com/plugins#settings

**Comment by umireon** [comment]
@royshil Can we close this issue? The reporter no longer seems to be here

**Comment by royshil** [comment]
Yep makes sense to close.
