### ISSUE TITLE
Updated install instructions for Xubuntu

### ISSUE THREAD

**Issue by hothello** [royshil/obs-backgroundremoval#66]
I have installed OBS through the official PPA repository, which does not include the libobs-dev package. There are a number of issues with this route and several comments have addressed them. I am thus sharing an updated version of the install procedure. I hope this helps!
`sudo apt install -y libopencv-dev language-pack-en wget git build-essential cmake`
`wget https://github.com/microsoft/onnxruntime/releases/download/v1.7.0/onnxruntime-linux-x64-1.7.0.tgz`
`sudo tar xzvf onnxruntime-linux-x64-1.7.0.tgz --strip-components=1 -C /usr/ --wildcards "*/include/*" "*/lib*/"`
`git clone https://github.com/royshil/obs-backgroundremoval.git`
`cd obs-backgroundremoval`
`mkdir build && cd build`
`cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr && cmake --build .`
`sudo cmake --install .`
Note: cmake will fail to compile if you download the tar.gz archive, as it does not include the .git/ folder.

**Comment by dynamodan** [comment]
When trying to compile this on ubuntu 18.04, I get an error:

```
src/background-filter.cpp:578:1: sorry, unimplemented: non-trivial designated initializers not supported
```

**Comment by royshil** [comment]
Build system was redone
Should be good now for Ubuntu ish build
