### ISSUE TITLE
Package as a snap or flatpak for a simple user friendly installation on Linux

### ISSUE THREAD

**Issue by heidiwenger** [royshil/obs-backgroundremoval#67]
For an easy installation, say, clicking "Install" at Snap Store in Ubuntu, which is the first Linux distro for many new users now coming to Linux. Solus and Manjaro support snaps AND flatpak by default. Fedora defaults flatpak i think, Linux Mint too.

As i read here, many seemed to end up in the world of pain attempting to build from source. Maybe it is time to attempt a creation of a simple pre-package? I mean, why not aim for a simple user friendly way on getting obs-backgroundremoval to go on Linux?

Could this by any chance be possible? What other options there are apart from snaps and flatpaks?

Thank you.

**Comment by anumerico** [comment]
I am having trouble too, getting segmentation fault in ubuntu 20.04.

**Comment by tam7t** [comment]
I put together a flatpak definition that seems to work for v0.4.0: https://gist.github.com/tam7t/dfc8d08ee1042de52921f2cd8a0ce2db

I start with OBS installed through flatpak (`com.obsproject.Studio`, https://feaneron.com/2022/02/14/obs-studio-27-2-on-flathub-get-it-while-its-hot/) then build/install these files as a plugin:

```
$ flatpak-builder build-dir com.obsproject.Studio.Plugin.backgroundremoval.yaml --force-clean
$ flatpak-builder --user --install --force-clean build-dir com.obsproject.Studio.Plugin.backgroundremoval.yaml
```

**Comment by arpagon** [comment]
Nice, thanks @tam7t  [This](https://github.com/royshil/obs-backgroundremoval/issues/67#issuecomment-1140530459) 
 work as charm. 
@royshil Is possible to publish the plugin in flathub?

**Comment by heidiwenger** [comment]
> Nice, thanks @tam7t [This](https://github.com/royshil/obs-backgroundremoval/issues/67#issuecomment-1140530459) work as charm. @royshil Is possible to publish the plugin in flathub?

Oh yes that would be the optimal for the end user (and prolly for everyone else) and in my mind starting this thread.

Three files are required to publish on Flathub:

1. The Flatpak manifest containing the sources and dependencies of the plugin. This file may be either YAML or JSON.

2. AppStream metadata with useful information about your plugin, such as the name, a description, and the license.

3. flathub.json with Flathub build options.

**Comment by percybolmer** [comment]
I just tried this on an Ubuntu and got 

```bash
flatpak-builder --user --install --force-clean build-dir com.obsproject.Studio.Plugin.backgroundremoval.yaml
error: org.kde.Sdk/x86_64/5.15-21.08 not installed
Failed to init: Unable to find sdk org.kde.Sdk//5.15-21.08 version stable

```
Any Ideas?

**Comment by ADHDefy** [comment]
Bumping this, any chance of getting this on Flathub?

**Comment by royshil** [comment]
I'll get it on flathubMay take me a while as I'm swamped at work right now.I'll do my best! On Dec 15, 2022, at 6:39 PM, ADHDefy ***@***.***> wrote:﻿
Bumping this, any chance of getting this on Flathub?

**Comment by bergmannf** [comment]
I used @tam7t files and updated them a bit, to get it to work in a github workflow.
If anyone just wants a flatpak file they can download and install so it works, I left the last build in my fork up - so you can grab the artifact from there and it can be installed with `flatpak install --user <the_unzipped_file>`: https://github.com/bergmannf/obs-backgroundremoval/actions/runs/4204728714

**Comment by royshil** [comment]
@bergmannf We need help again with flatpak on the official ci build
Can you take a look in the pull request please? 🙏

**Comment by umireon** [comment]
This plugin is going to be registered on FlatHub 🎉 
https://github.com/flathub/flathub/pull/4016

**Comment by umireon** [comment]
You can install this plugin via this command:

```
flatpak install com.obsproject.Studio.Plugin.BackgroundRemoval
```
