### ISSUE TITLE
New model "BackgroundMattingV2"

### ISSUE THREAD

**Issue by Kryptortio** [royshil/obs-backgroundremoval#69]
I found a model developed at University of Washington, paper and examples can be found here
https://youtu.be/oMfPTeYDF9g
http://grail.cs.washington.edu/projects/background-matting-v2/
https://github.com/PeterL1n/BackgroundMattingV2

Also there is a virtual camera example here
https://github.com/andreyryabtsev/BGMv2-webcam-plugin-linux

Judging by the examples the results are very impressive so maybe it's something worth looking into for this project.

**Comment by louie-github** [comment]
Judging by the README, it seems that project has been mostly superseded by [Robust Video Matting](https://github.com/PeterL1n/RobustVideoMatting) by the same author.

This has already been implemented in commit 8a193d773c1a004206f372e9a2a1ef286138dfd6.

**Comment by Kryptortio** [comment]
Damn, guess I should have looker a bit deeper. I couldn't really imagine that it was based on the same thing because when I've tried it I haven't gotten anywhere near results that good even with an ideal background like a green screen.
