### ISSUE TITLE
Build without Git

### ISSUE THREAD

**Issue by blitz** [royshil/obs-backgroundremoval#71]
I'm currently trying to package this plugin for [NixOS](https://nixos.org/). For packaging this plugin, it would be nice to be able to build it without having to download the complete Git history. The build process requires this currently, though, due to:

```
include(external/MunkeiVersionFromGit.cmake)
version_from_git()
```

in `CMakeLists.txt`. I currently work around this by manually patching this away. Instead, it would be nice to be able to specify a version via cmake parameters.

**Comment by royshil** [comment]
build system was redone
