### ISSUE TITLE
Plugin doesnt Show up

### ISSUE THREAD

**Issue by Stoermy** [royshil/obs-backgroundremoval#72]
Hey, first the Folder Background removal is there but it doesnt show up in OBS 64 bit under Cam and Filters.... idk where the Problem ist.

It is installed right.

**Comment by taidos** [comment]
Im on the same situation with all the latest versions

**Comment by hunsnowboarder** [comment]
Same situation here....

**Comment by tabjy** [comment]
Possible duplicate of #37?

**Comment by brotons** [comment]
on My OBS version 27.2.4 also not showing up. I think this is still a bug problem.

**Comment by rohaanuv** [comment]
obs 28.0.3 can't show the  background removal plugin

**Comment by royshil** [comment]
very little information in this issue. i'm closing, and we're tracking this in other issues
