### ISSUE TITLE
Plugin not build for Apple Silicon (ARM64)

### ISSUE THREAD

**Issue by podycust** [royshil/obs-backgroundremoval#73]
When loading an ARM64 build of obs the plugin doesn't show up but if using an intel build its shows and works fine

**Comment by richtong** [comment]
It probably needs to be built as a universal binary

**Comment by smattar2020** [comment]
Please build this for Apple Silicon. This is sooooooo... slow when using the Intel version of OBS on M1.

**Comment by royshil** [comment]
Arm Macs now fully supported.
