### ISSUE TITLE
FPS drops to < 15

### ISSUE THREAD

**Issue by dontcrash** [royshil/obs-backgroundremoval#74]
When enabled either on GPU or CPU, the FPS in OBS drops from a solid 60 to less than 15, this is unusable.
My GPU and CPU also report low usage, I am not sure what is going on here.
The filter does work but is obviously slowing something down.

**Comment by metzger100** [comment]
#23

**Comment by royshil** [comment]
newer version have upgrades to onnxruntime and opencv and should resolve this on most OSs
