### ISSUE TITLE
Not available on browser-source

### ISSUE THREAD

**Issue by sudolcious** [royshil/obs-backgroundremoval#75]
Hey Guys, Hey Roy.

Amazing plugin, really. I would just like to ask if it would be possible to make it available on sources that aren't video inputs. In my case i'm specifically talking about browser sources, because my camera feed is going straight from my iPhone via vdo.ninja into obs. I'm not sure how much of a hassle it would be to implement this, but if it's not too much trouble I'd be delighted if you'd consider the possibility.

Thanks and major kudos for your work!

**Comment by royshil** [comment]
recent builds should allow it to work on browser source
