### ISSUE TITLE
Cmake error during installation on Ubuntu 

### ISSUE THREAD

**Issue by voltumna** [royshil/obs-backgroundremoval#78]
Hi, 
I have Ubuntu 21.04 and am trying to install this plugin, i followed the instructions to the letter,  but it fails at the **cmake** part:
it returns 
`CMake Error: The source directory "/home/.../Downloads" does not appear to contain CMakeLists.txt.`

![image](https://user-images.githubusercontent.com/1274922/152787016-eef655b4-5c84-41fd-820b-e77c88130097.png)

Can you help?.
thanks
Maurizio

**Comment by Sitolam** [comment]
You must also clone the project. Then you must make the build directory in the cloned directory.
