### ISSUE TITLE
Ubuntu installation of  pacstall -I obs-backgroundremoval-git fails

### ISSUE THREAD

**Issue by voltumna** [royshil/obs-backgroundremoval#79]
I am trying to install the background remover using pacstall on ubuntu 21 with OBS from the ubuntu version, which is the 26.1.2

`
rm -rf .config/obs-studio` 
`sudo apt remove obs-studio --auto-remove`
`sudo add-apt-repository ppa:obsproject/obs-studio -r` 
`sudo apt update && sudo apt install obs-studio`
`pacstall -I obs-backgroundremoval-git
`

but I am getting the following error,

![image](https://user-images.githubusercontent.com/1274922/152946970-e9a2106d-729d-4219-8797-88f3d460e730.png)

And of course, OBS does not have the background remover in the list of filters, 

Any help please,
thank you
Maurizio

**Comment by Zahrun** [comment]
Hello Maurizio,
These warnings are ok, the background remover should work.
Please check the filter section of a video capture item.
It will be in "Audio/Video filters" section, not the other one "Effect filters"
![image](https://user-images.githubusercontent.com/10415894/159121836-8e91aaf5-92c5-4a85-9232-7fac80c809e9.png)

**Comment by voltumna** [comment]
Thank you, 
I will check it out, but meanwhile I have to say that I have given up, 
you can close this case and possibly later I will try.

Thanks again
Maurizio
