### ISSUE TITLE
Version 0.4.0 does not work with OBS 27.2.0

### ISSUE THREAD

**Issue by jambt** [royshil/obs-backgroundremoval#80]
I updated OBS to 27.2.0 recently and OBS background removal stopped working. Even after a reinstall, the previously working configuration only shows empty controls and I cannot add the background removal as a new filter.

OS: MacOS 12.2.1
OBS: 27.2.0
obs-background-removal: 0.4.0

**Comment by javabrett** [comment]
@jambt that version combination is working for me here, but note that the OBS upgrade on MacOS will delete any previously-installed extra plugins like this one.  Have you reinstalled the plugin post-upgrade?

**Comment by jambt** [comment]
@javabrett : Thank you for your response. Indeed, after I updated to 27.2.1 today and reinstalled, it now works again. Probably a quirk on my machine then.
