### ISSUE TITLE
convertBGRToFrame is error

### ISSUE THREAD

**Issue by chfeizy** [royshil/obs-backgroundremoval#82]
<img width="901" alt="image" src="https://user-images.githubusercontent.com/6427629/156888165-aac8bdf5-aa6c-42b4-b96a-d7e78ed34189.png">

an I change the convertFrameToBGR

static cv::Mat convertFrameToBGR(
	struct obs_source_frame *frame,
	struct background_removal_filter *tf
) {
	const cv::Size frameSize(frame->width, frame->height);
	if (tf->scalerToBGR == nullptr) {
		// Lazy initialize the frame scale & color converter
		initializeScalers(frameSize, frame->format, tf);
	}
	cv::Mat imageYUV(frame->height, frame->width, CV_8UC2, frame->data[0]);
	cv::Mat imageBGR;
	cv::cvtColor(imageYUV, imageBGR, cv::ColorConversionCodes::COLOR_YUV2BGR_UYVY);
	return imageBGR;
}

**Comment by chfeizy** [comment]
<img width="663" alt="image" src="https://user-images.githubusercontent.com/6427629/156909369-bbfb44a8-c660-44f5-a6e5-c733267b2d44.png">
after imageBGR.setTo(tf->backgroundColor, backgroundMask);
the imageBGR.data

**Comment by chfeizy** [comment]
use obs 27.1.3 is the same error

**Comment by royshil** [comment]
@chfeizy its possible the problem is with the incoming frames
what are you using for video source? is it a camera? which kind?

**Comment by royshil** [comment]
stale
