### ISSUE TITLE
Fedora GPU Failed to load shared library

### ISSUE THREAD

**Issue by bentenjamin** [royshil/obs-backgroundremoval#86]
Hey, I am compiling from source on Fedora 35 and having issues trying to get the GPU compiled background removal to work.

Here are the steps that I followed:

- Installed the official nvidia drivers and confirmed that the cuda drivers are working by using their cuda samples
- $ export ONNX_VERSION=1.10.0
- $ wget https://github.com/microsoft/onnxruntime/releases/download/v${ONNX_VERSION}/onnxruntime-linux-x64-gpu-${ONNX_VERSION}.tgz
- $ sudo tar xzvf onnxruntime-linux-x64-gpu-${ONNX_VERSION}.tgz --strip-components=1 -C /usr/local/ --wildcards "*/include/*" "*/lib*/"
- $ sudo ldconfig
- mkdir build && cd build
- $ cmake -DWITH_CUDA=ON -DLIBOBS_INCLUDE_DIR="../../obs-studio/libobs" -DCMAKE_INSTALL_PREFIX=/usr -DLIBOBS_LIB="/usr/lib64/libobs.so" .. && cmake --build . && sudo cmake --install . # This is because the ubuntu libs in the tutorial dont exist for fedora. I cloned obs-studio and used that LibObs
- $ mkdir -p ~/.config/obs-studio/plugins/obs-backgroundremoval/bin/64bit
- $ cp obs-backgroundremoval.so ~/.config/obs-studio/plugins/obs-backgroundremoval/bin/64bit/
- $ cp ../data ~/.config/obs-studio/plugins/obs-backgroundremoval/

I can select background removal in the filters for my webcam but the output is black. When I check the logs I see there is `[obs-backgroundremoval] OrtSessionOptionsAppendExecutionProvider_Cuda: Failed to load shared library`. I have been trying to fix for 2 days without any luck, any ideas?

I can compile and run on CPU with onnxruntime 1.10 but Id prefer to use GPU.
I have tried onnxruntime 1.7 1.9 and 1.10 without any luck.
Please let me know if I can give any other logs or system info

**Comment by royshil** [comment]
@bentenjamin can you write the Fedora install instructions in the README plz? put a pull request...
