### ISSUE TITLE
Installation in fedora?

### ISSUE THREAD

**Issue by CarmeloCampos** [royshil/obs-backgroundremoval#89]
I have tried to follow the steps for ubuntu changing the commands for fedora, installing the libraries manually, and even so it gives me an error to get the libraries, I would like to know if you can implement a guide for fedora. <3

**Comment by royshil** [comment]
@CarmeloCampos i'm not a Fedora user as well... maybe you can find some help online? in a forum?
we can also make a docker script that will build the plugin on a fedora base.

**Comment by jessebl** [comment]
@CarmeloCampos , which libraries are you having trouble with? Most Fedora libraries are listed as `-devel` instead of `-dev`, and sometimes might have the `lib` prefix omitted.

**Comment by raag** [comment]
Hello I managed to found a way to install it in fedora, if you want you can check it out at this PR https://github.com/royshil/obs-backgroundremoval/pull/95
