### ISSUE TITLE
Current release crashing in Windows 10 x64

### ISSUE THREAD

**Issue by mrfixit2001** [royshil/obs-backgroundremoval#9]
Crash log:

https://dpaste.com/BVUYJL2YW

**Comment by royshil** [comment]
this is crashing within the filter, so i'm going to guess it's a color space issue.
i might be wrong though.

i'd need more information about how it's crashing, e.g. what camera are you connecting, etc.

if you have an option to select the color space in the camera properties - try changing to different values.

**Comment by mrfixit2001** [comment]
The webcam is an integrated camera into the dell latitude 5411. Device manager looks like it's attached to the usb bus, it's called "Integrated Webcam" and here's the hardware detail:
USB\VID_0BDA&PID_58FD&REV_8616&MI_02
USB\VID_0BDA&PID_58FD&MI_02

The color space and color range options are:
Color Space: 709 and 601
Color Range: Partial and Full

I have tried combinations of both, but none resolve the crash. I'm testing with the latest OBS studio download, version 26.1.1
I also went ahead and tried all the different config settings for the camera as well (resolution, fps, video format, and buffering) and so far I have not found a combination of settings that resolves the crash.

Open to any and all feedback, and willing to test anything you send!

**Comment by mrfixit2001** [comment]
It crashes immediately when I click "Ok" after naming the filter, and I'm leaving the name the default "Background Removal". I see the filter options appear on the screen, threshhold, contour, smooth silhousette, and background color, along with all the associated controls. but my video immediately freezes and the application then crashes.

**Comment by tikicoder** [comment]
has anyone tried installing https://github.com/microsoft/onnxruntime
I wonder if its not defaulting to the local ddl and trying to use the Global one that probably doesn't exist

**Comment by sgoeke** [comment]
I've got the same issue using a Logitech Brio webcam.

[Crash 2021-05-01 14-06-35.txt](https://github.com/royshil/obs-backgroundremoval/files/6409522/Crash.2021-05-01.14-06-35.txt)

**Comment by royshil** [comment]
I just committed a fix to the color space conversion that relies on libobs internal omni-converters. So it should now be able to handle any input colorspace.

If you can please build and test.
I will put up a new release of binaries later today.

**Comment by royshil** [comment]
Please  try the latest release for windows: https://github.com/royshil/obs-backgroundremoval/releases/tag/0.2-beta

**Comment by tocklime** [comment]
0.2 has fixed this problem for me.

**Comment by royshil** [comment]
@sgoeke @tikicoder @mrfixit2001  can y'all verify the latest Windows release works for you plz?

**Comment by sgoeke** [comment]
0.2 fixed it for me as well. Thank you for the effort!

**Comment by tikicoder** [comment]
yup thanks

**Comment by mrfixit2001** [comment]
Fixed for me now also, thanks!!
