### ISSUE TITLE
Add plugin to "Effect Filters" instead of "Audio/Video Filters"

### ISSUE THREAD

**Issue by OoiHS** [royshil/obs-backgroundremoval#90]
Greetings,
Is it possible to add this plugin under "Effects Filters" instead of "Audio/Video Filters".
This way we could perform background removal with any sources instead of only camera source.

![image](https://user-images.githubusercontent.com/45958279/160543688-ed302e8c-b1ff-446d-99c5-00f50faa0ee4.png)

**Comment by royshil** [comment]
Unfortunately this can't be done... the low level OBS frame processing API for filters only allows per-pixel "shaders" and not full processing of the entire image - which is needed for the neural network.

**Comment by joemarshall** [comment]
@royshil I think it might be possible using samplers - https://github.com/Xaymar/obs-StreamFX/blob/master/source/filters/filter-virtual-greenscreen.cpp

Or alternatively, there's no way to add alpha channel to the output of this?

**Comment by royshil** [comment]
the plugin now appears in "Effect Filters"
