### ISSUE TITLE
Updated installation steps on macOS 12 (Monterey)

### ISSUE THREAD

**Issue by bnoffer** [royshil/obs-backgroundremoval#92]
Hi everyone,

this might also apply already for macOS 11 (Big Sur). The installation guide provided in the release section will cause OBS to stop working since it will corrupt the Application Checksum and macOS will block execution.

Instead the plugin needs to be installed into ``/Library/Application Support/obs-studio/plugins`` with the following folder structure:
![Bildschirmfoto 2022-04-09 um 16 54 20](https://user-images.githubusercontent.com/9718314/162579510-6e9098a7-7900-4bf7-98ae-1653797f218f.png)

This keeps OBS.app intact and the plugin works like a charm.

**Comment by xgorjess** [comment]
Hi, thanks for this -- my obs crashed about 100x this morning after installing with initial instructions. HOWEVER, I do not have an obs-studio folder in my Application Support folder. What do I do??

**Comment by dangom** [comment]
Tried on Big Sur and this will still cause the app to crash.

**Comment by dangom** [comment]
Built from source. Still crashes.

**Comment by bnoffer** [comment]
I have folders in both locations, but plugins are in the `/Library/Application Support` folder and not in `~/Library/Application Support`and since installing this way 0 issues with the plugin except for the expected high cpu load when using it.

**Comment by royshil** [comment]
did https://github.com/royshil/obs-backgroundremoval/pull/85 resolve the problem?

**Comment by hughperkins** [comment]
Tried the approach from the head of thi thread, but still creashes

**Comment by royshil** [comment]
Mac installers now in place.
