### ISSUE TITLE
Install commands removes osb studio on Linux Mint 20.3

### ISSUE THREAD

**Issue by Supermagnum** [royshil/obs-backgroundremoval#93]
sudo apt-get install libobs0
that removes obs-studio.
Also, libobs-dev is dependent on libobs-dev.

Trying to reinbstall obs-studio removes the  libobs0 and  libobs-dev.

The obs studio version is from the ppa ( deb http://ppa.launchpad.net/obsproject/obs-studio/ubuntu focal main )

I have mentioned the issue on the linux mint forum:
https://forums.linuxmint.com/viewtopic.php?f=47&t=371867

**Comment by royshil** [comment]
@Supermagnum where are you seeing the instruction to `apt-get install libobs0`?

**Comment by Supermagnum** [comment]
> @Supermagnum where are you seeing the instruction to `apt-get install libobs0`?

What I did :
 I did sudo apt install -y libobs-dev libopencv-dev language-pack-en wget git build-essential cmake libsimde-dev .
libobs-dev is dependent of libobs0, and libsimde-dev cannot be found. 

Please chek that your bild and install instructions are up to date, as https://github.com/microsoft/onnxruntime/releases/download/v1.7.0/onnxruntime-linux-x64-1.7.0.tgz is replaced by 1.11x .

**Comment by Sudneo** [comment]
Just as a FYI, I also got tricked into install `libobs0` because of this message when running the suggested commands:

```
sudo apt install -y libobs-dev libopencv-dev language-pack-en wget git build-essential cmake libsimde-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cmake is already the newest version (3.16.3-1ubuntu1).
libopencv-dev is already the newest version (4.2.0+dfsg-5).
build-essential is already the newest version (12.8ubuntu1.1).
git is already the newest version (1:2.25.1-1ubuntu3.4).
language-pack-en is already the newest version (1:20.04+20220211).
wget is already the newest version (1.20.3-1ubuntu2).
libsimde-dev is already the newest version (0.7.2-4).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libobs-dev : Depends: libobs0 (= 25.0.3+dfsg1-2) but it is not going to be installed
```

This is on Ubuntu 20.04

**Comment by Supermagnum** [comment]
Any solution on this yet?

**Comment by royshil** [comment]
new linux build scripts should resolve this
