### ISSUE TITLE
droidcam obs

### ISSUE THREAD

**Issue by DarkVoidGames** [royshil/obs-backgroundremoval#94]
So I've installed the obs-backgroundremoval plugin, and it completely removes video feed from droidcam obs. I wanted to use the background removal plugin to remove my background instead of having to assemble my greenscreen when I wanna stream or record for YouTube and twitch and disassemble it when I wasn't using it. So I figured I'd try this out, pretty much doesn't work with droidcam obs, since it completely removes the video feed completely. not sure if I did something wrong or not, because I followed a youtubers guide to a T.

**Comment by royshil** [comment]
@DarkVoidGames are you still interested in trying to resolve this problem?
