### ISSUE TITLE
Can now Install. [Commit bedcaf9. Refer to @Zahrun] Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by ShadowStorm0** [royshil/obs-backgroundremoval#96]
Using OBS-STUDIO PPA

ERROR:

CMake Error at CMakeLists.txt:106 (find_package):
  By not providing "Findlibobs.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "libobs", but
  CMake did not find one.

  Could not find a package configuration file provided by "libobs" with any
  of the following names:

    libobsConfig.cmake
    libobs-config.cmake

  Add the installation prefix of "libobs" to CMAKE_PREFIX_PATH or set
  "libobs_DIR" to a directory containing one of the above files.  If "libobs"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by fstelte** [comment]
I have the same on ubuntu 22.04

**Comment by Sudneo** [comment]
Hello, I am having the same issue as @Zahrun . Once fixed the `libobs` issues, now getting:

```
  Could not find a package configuration file provided by "obs-frontend-api"
  with any of the following names:

    obs-frontend-apiConfig.cmake
    obs-frontend-api-config.cmake
```

The problem is that I cannot find any information at all about those files, unlike for the libobs config files:

```
sudo find / -name "*.cmake" | grep -i obs                                                                                     
/usr/lib/x86_64-linux-gnu/cmake/LibObs/libobsConfig.cmake
/usr/lib/x86_64-linux-gnu/cmake/LibObs/LibObsConfigVersion.cmake
/usr/lib/x86_64-linux-gnu/cmake/LibObs/LibObsTarget.cmake
/usr/lib/x86_64-linux-gnu/cmake/LibObs/LibObsTarget-none.cmake
/usr/lib/x86_64-linux-gnu/cmake/LibObs/LibObsConfig.cmake
```

It seems that none of the packages required for installation provide this file.
I tried to "fool" the build process by creating an empty file matching the name, just in case it was 'required' by mistake, but the execution then broke:

```
-- Configuring done
CMake Error at CMakeLists.txt:106 (add_library):
  Target "obs-backgroundremoval" links to target "OBS::libobs" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

So it seems that this is somehow required.

**Comment by ShadowStorm0** [comment]
@Sudneo I found the file "obs-frontend-apiConfig.cmake.in" in the Github Repository.
Any idea what the .in suffix means?

The Path: ~/obs-studio/UI/obs-frontend-api/cmake

**Comment by Sudneo** [comment]
That's a good find, I guess it could be 'init' maybe, I turned off my pc now, but tomorrow I think I will try again and I will try using that file. It should be picked up if placed in any $PATH location. I am not very familiar with Cpp in general, so I have quite a hard time dealing with this dependency issues, unfortunately.

**Comment by uniqueum** [comment]
Cannot really help out with the Linux side of this, just following the whole git, as I'd love to know about updates.
Nevertheless, seeing as a lot of things are happening here currently AND there doesn't seem to be a space - as such - for that, do join my Discord ( https://discord.gg/St3bssyX ) and head over to #obs-backgroundremoval for LIVE DISCUSSIONS.

Cheers!

**Comment by ShadowStorm0** [comment]
@Sudneo this is the Command I use now. I created a symbolic link to create a new file called 'obs-frontend-apiConfig.cmake' but it outputs an Unknown argument error.

Command:
`cmake` .. -Dlibobs_DIR=/usr/lib/cmake/LibObs -obs-frontend-api_DIR=/home/origins/Downloads/obs-studio/UI/obs-frontend-api/cmake && cmake --build . && sudo cmake --install .`

Error:
`CMake Error: Unknown argument -obs-frontend-api_DIR=/home/origins/Downloads/obs-studio/UI/obs-frontend-api/cmake`

**Comment by ShadowStorm0** [comment]
Actually now that I just noticed it, why is there a 'D' prefix in 'Dlibobs_DIR'.
I do not see it mentioned anywhere in the CMakeList

Asking because of the second symbolic link I created for "obs-frontend-apiConfig.cmake"

**Comment by Zahrun** [comment]
It seems even the github CI failed for the latest commit https://github.com/royshil/obs-backgroundremoval/runs/6264276409

So, as a workaround, until @royshil replies, I use this:
`git checkout bedcaf973424a05d2cfff1dc1295f5b516f82cd2`
To go back to the latest buildable state and then build as usual

**Comment by royshil** [comment]
Yes this is the new plugin architecture they released. Something changed and I'm figuring out what it is
You'll notice in the logs on OBS that the plugin complains about mismatched size of the info strict, this is because of versions discrepancy between the 27.2.4 branch and the main branch. Plugins are not backwards compatible

Still working it out...

**Comment by Zahrun** [comment]
> @royshil I just built commit [bedcaf9](https://github.com/royshil/obs-backgroundremoval/commit/bedcaf973424a05d2cfff1dc1295f5b516f82cd2), and it successfully installed, but I can not find it under the Audio/Video Filters list.
> 
> I installed it under `~/.config/obs-studio/plugins"` and `~/usr/local/share/obs/obs-plugins/`
> 
> Any idea why this is happening? I tried to match the file structure of StreamFX and I can now see the option, but the video turns to black and nothing seams to work.

In commit https://github.com/royshil/obs-backgroundremoval/commit/bedcaf973424a05d2cfff1dc1295f5b516f82cd2, the plugin will appear fine in Audio/Video Filters list.
The plugin .so file has to be installed in `/usr/lib/x86_64-linux-gnu/obs-plugins/`obs-backgroundremoval.so
And the folder in be in `/usr/share/obs/obs-plugins/`obs-backgroundremoval/ here you have the locale folder and onnx files

**Comment by ShadowStorm0** [comment]
@Zahrun For some reason there was no obs-plugins folder in `/usr/lib/x86_64-linux-gnu.` I dropped the .so file in `/usr/lib/obs-plugins,` and it worked. The locale folder and onnx files works in `/usr/share/obs/obs-plugins/`

**Comment by ascdi** [comment]
Even using bedcaf9 i get a similar error on ubuntu (20.04), now it can't find OpenCV:

```
cmake .. -Dlibobs_DIR=/usr/lib/cmake/LibObs && cmake --build . && sudo cmake --install .
-- Found LibObs: /usr/lib/x86_64-linux-gnu/libobs.so  
-- Found Onnxruntime: /usr/local/include  
CMake Error at CMakeLists.txt:107 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" (requested
  version 4.2) with any of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/asc/obs-backgroundremoval/build/CMakeFiles/CMakeOutput.log".
```

**Comment by dergyitheron** [comment]
Hey guys,

as I understand it now, there are some issues with plugin having different format in newer versions of OBS. I have the same issue with come .cmake files not being found. I was able to solve the `libobsConfig.cmake` missing by creating symlink mentioned earlier in this issue.

I now get message of not being able to find `obs-frontend-apiConfig.cmake`, which some of you mentioned earlier as well.

As I would like to get it working, is there at least max supported version of OBS which can be used to build this plugin and use?

Thank you.

**Comment by directrix1** [comment]
I have a pull request #108 that allows it to build on Ubuntu 22.04 . I haven't tested it with CUDA though.
