### ISSUE TITLE
request: install instructions on Linux mint

### ISSUE THREAD

**Issue by Supermagnum** [royshil/obs-backgroundremoval#97]
I have tried to install on Linux mint,- but ran in to the libobs depency issue described here:
https://github.com/royshil/obs-backgroundremoval/issues/93

It uses packages from :
  Distro: Linux Mint 20.3 Una base: Ubuntu 20.04 focal 

So, how do I get this to compile and solve the mentioned libobs depency issue ?

**Comment by brunofunnie** [comment]
Same here kudos for those who passed this error, those files simple cannot be found.

My distro is: Pop!_OS 22.04 clean install also installed all dependencies even those from #93

**Comment by Supermagnum** [comment]
Any updates on this?
