### ISSUE TITLE
Adding Filter Causes Black Screen

### ISSUE THREAD

**Issue by jaronklopstein** [royshil/obs-backgroundremoval#98]
I have successfully downloaded and installed the plugin. When I add the video filter to my video input it results in a black screen. As soon as I remove the filter, my video input works normally. 

Here is a log file: https://obsproject.com/logs/FWS7ZyMyCuL0ymeq

**Comment by Jamtart420** [comment]
I installed it and worked fine try just putting in what you want behind you and see if it works I'm no pro 
![obs](https://user-images.githubusercontent.com/106849270/172480044-3f454d71-7745-4989-821a-cacfc8af9c30.png)
)

**Comment by nambuco** [comment]
> I have successfully downloaded and installed the plugin. When I add the video filter to my video input it results in a black screen. As soon as I remove the filter, my video input works normally.
> 
> Here is a log file: https://obsproject.com/logs/FWS7ZyMyCuL0ymeq

Same problem here..... tested with two diferent cameras. Windows 10 machine with latested OBS / Plugin version

**Comment by nambuco** [comment]
Moving back to version v0.3.0 solved the problem for me.

**Comment by titioft** [comment]
I just downloaded the plugin on my macosx 12.4 with OBS 27.2.4. Same issue totally black screen even when changing the threshold value. Absolutely no effect still full black. I will try to use a different version v0.3.0.

**Comment by titioft** [comment]
> I just downloaded the plugin on my macosx 12.4 with OBS 27.2.4. Same issue totally black screen even when changing the threshold value. Absolutely no effect still full black. I will try to use a different version v0.3.0.

ok I solved my own issue. I was not installing the plug-in properly. I needed to install the model as well. Drag and drop is not working from the archive. I needed to run into command line. See below: 
unzip -o obs-backgroundremoval-macosx.zip -d /Applications/OBS.app/Contents/                                
Archive:  obs-backgroundremoval-macosx.zip
  inflating: /Applications/OBS.app/Contents/Plugins/obs-backgroundremoval.so  
   creating: /Applications/OBS.app/Contents/Resources/data/obs-plugins/obs-backgroundremoval/
   creating: /Applications/OBS.app/Contents/Resources/data/obs-plugins/obs-backgroundremoval/locale/
  inflating: /Applications/OBS.app/Contents/Resources/data/obs-plugins/obs-backgroundremoval/locale/en-US.ini  
  inflating: /Applications/OBS.app/Contents/Resources/data/obs-plugins/obs-backgroundremoval/modnet_simple.onnx  
  inflating: /Applications/OBS.app/Contents/Resources/data/obs-plugins/obs-backgroundremoval/mediapipe.onnx  
  inflating: /Applications/OBS.app/Contents/Resources/data/obs-plugins/obs-backgroundremoval/SINet_Softmax_simple.onnx  
  inflating: /Applications/OBS.app/Contents/Resources/data/obs-plugins/obs-backgroundremoval/rvm_mobilenetv3_fp32.onnx  
  inflating: /Applications/OBS.app/Contents/Resources/data/obs-plugins/obs-backgroundremoval/selfie_segmentation.onnx  

All worked like a charm after that. Great plug in !

**Comment by mpdelbuono** [comment]
I ran into this same problem and the same cause. I would recommend that instead of silently failing with a black screen, the plugin finds a way to emit an error message saying something like "model not found". It would save a lot of time troubleshooting. Of course it's the user's fault, but it's always good to have software that assumes users are stupid instead of leaving them blind to the problem.
